
#ifndef GUARD_CONSTANTS_BATTLE_PARTNERS_H
#define GUARD_CONSTANTS_BATTLE_PARTNERS_H

#define PARTNER_NONE             0
#define PARTNER_STEVEN           1
#define PARTNER_DAWN_PIPLUP      2
#define PARTNER_DAWN_TURTWIG     3
#define PARTNER_DAWN_CHIMCHAR    4
#define PARTNER_LUCAS_PIPLUP     5
#define PARTNER_LUCAS_TURTWIG    6
#define PARTNER_LUCAS_CHIMCHAR   7

#define PARTNER_COUNT            8

#endif // GUARD_CONSTANTS_BATTLE_PARTNERS_H
