#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from src/data/heal_locations.json and Inja template src/data/heal_locations.constants.json.txt
//


enum {
    HEAL_LOCATION_NONE,
    HEAL_LOCATION_TWINLEAF_TOWN_PLAYERS_HOUSE_2F,
    HEAL_LOCATION_TWINLEAF_TOWN_RIVALS_HOUSE_2F,
    HEAL_LOCATION_PETALBURG_CITY,
    HEAL_LOCATION_SLATEPORT_CITY,
    HEAL_LOCATION_MAUVILLE_CITY,
    HEAL_LOCATION_RUSTBORO_CITY,
    HEAL_LOCATION_FORTREE_CITY,
    HEAL_LOCATION_LILYCOVE_CITY,
    HEAL_LOCATION_MOSSDEEP_CITY,
    HEAL_LOCATION_SOOTOPOLIS_CITY,
    HEAL_LOCATION_EVER_GRANDE_CITY,
    HEAL_LOCATION_TWINLEAF_TOWN_PLAYERS_HOUSE,
    HEAL_LOCATION_TWINLEAF_TOWN_RIVALS_HOUSE,
    HEAL_LOCATION_SANDGEM_TOWN,
    HEAL_LOCATION_DEWFORD_TOWN,
    HEAL_LOCATION_LAVARIDGE_TOWN,
    HEAL_LOCATION_FALLARBOR_TOWN,
    HEAL_LOCATION_VERDANTURF_TOWN,
    HEAL_LOCATION_PACIFIDLOG_TOWN,
    HEAL_LOCATION_EVER_GRANDE_CITY_POKEMON_LEAGUE,
    HEAL_LOCATION_SOUTHERN_ISLAND_EXTERIOR,
    HEAL_LOCATION_BATTLE_FRONTIER_OUTSIDE_EAST,
    NUM_HEAL_LOCATIONS
};

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
