gText_Birch_HelloThere::
	.string "Hello there!\n"
	.string "It's so very nice to meet you!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "$"

gText_Birch_Welcome::
	.string "My name is Rowan.\p"
	.string "However, everyone just calls me\n"
	.string "the Pokémon Professor.\p"
	@ FODO: Implement intro help section
	@ .string "Before I go any further, is this\n"
	@ .string "your first adventure?\p"
	@ .string "If you need advice, I'm certainly \n"
	@ .string "capable of giving it\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "$"

gText_Birch_MainSpeech::
	@ FODO: Implement intro poke ball interaction
	@ .string "Here, I have a Poké Ball.\p"
	@ .string "Touch the button on the middle of\n"
	@ .string "the Poké Ball, if you'd please.\p"
	.string "We humans live alongside Pokémon\n"
	.string "as friends.\p"
	.string "At times we play together,\n"
	.string "and at other times we\l"
	.string "work together.\p"
	.string "Some people use their Pokémon\n"
	.string "to battle and develop\l"
	.string "closer bonds with them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may\n"
	.string "learn more about Pokémon.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, why don't you tell me\n"
	.string "a little bit about yourself?\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Tell me, what is your name?$"

gText_Birch_SoItsPlayer::
	.string "OK...\n"
	.string "So you're {PLAYER}{KUN}?\p"
	.string "$"

gText_Birch_YourePlayer::
	.string "A fine name that is!\p"
	@ FODO: Implement rival naming
	@ .string "Now, this boy here...\n"
	@ .string "I believe he's your friend.\p"
	.string "$"

gText_Birch_WhatsHisName::
	.string "What might his name be?$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}, the time\n"
	.string "has come.\p"
	.string "Your very own tale of grand\n"
	.string "adventure is about to unfold.\p"
	.string "On your journey, you will meet\n"
	.string "countless Pokémon and people.\p"
	.string "I'm sure that along the way you will\n"
	.string "discover many things, perhaps even\l"
	.string "something about yourself.\p"
	.string "Now, go on, leap into the world of\n"
	.string "Pokémon!\p"
	.string "$"
