gText_WouldYouLikeToRestYourPkmn::
	.string "Hello, and welcome to\n"
	.string "the Pokémon CENTER.\p"
	.string "We restore your tired Pokémon\n"
	.string "to full health.\p"
	.string "Would you like to rest your Pokémon?$"

gText_IllTakeYourPkmn::
	.string "Okay, I'll take your Pokémon for a few\n"
	.string "seconds.$"

gText_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\p"
	.string "We've restored your Pokémon to full\n"
	.string "health.$"

gText_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

gText_WelcomeCutShort::
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Thank you for waiting.$"

gText_WeHopeToSeeYouAgain2::
	.string "We hope to see you again!$"

gText_TrainerCard::
	.string "You may sign the back of your\n"
	.string "Trainer Card here.\p"
	.string "Would you like to sign your\n"
	.string "Trainer Card?$"
	
gText_ClubUnionRoom::
	.string "Welcome to the Pokemon Wireless\n"
	.string "Club Union Room.\p"
	.string "You may interact directly with\n"
	.string "many Trainers here.\p"
	.string "Would you like to enter the room?$"

gText_ClubColosseum::
	.string "Welcome to the Pokemon Communication\n"
	.string "Club Colosseum.\p"
	.string "You may battle with your friends\n"
	.string "here.\p"
	.string "Which Battle Mode would you like\n"
	.string "to play?$"

gText_PleaseDoVisitAgain::
	.string "Please do visit again.$"
