Ace_Trainer_AbelDefeat:
	.string "You’re not a Trainer that can be\n"
	.string "taken lightly!$"

Ace_Trainer_AbelPostBattle:
	.string "The Pokémon you’ll meet here won’t\n"
	.string "make it easy for you to move onward.$"

Ace_Trainer_AbelIntro:
	.string "The Trainers and Pokémon that gather\n"
	.string "here aren’t pushovers.\p"
	.string "They all have tricks up their sleeves!$"

Ace_Trainer_AliciaDefeat:
	.string "That’s right. A good Trainer will win,\n"
	.string "no matter what the situation may be.$"

Ace_Trainer_AliciaPostBattle:
	.string "The Trainer’s feelings...\n"
	.string "The Pokémon’s feelings...\p"
	.string "If they are one and the same, you\n"
	.string "will never lose.$"

Ace_Trainer_AliciaIntro:
	.string "Are you feeling all run-down?\p"
	.string "But a good Trainer is one who wins no\n"
	.string "matter the situation!$"

Ace_Trainer_AllenDefeat:
	.string "I kinda deserved that, didn’t I?\n"
	.string "I gotta stop mouthing off like that...$"

Ace_Trainer_AllenPostBattle:
	.string "I’ll remember you and your shifty\n"
	.string "Pokémon, too. I’m watching you...$"

Ace_Trainer_AllenIntro:
	.string "What, were you just dawdling around\n"
	.string "hoping I’d notice you for a battle?\p"
	.string "You know you’re going to get whupped\n"
	.string "here, don’t you?$"

Ace_Trainer_AlyssaDefeat:
	.string "Aiyeeeeh!\n"
	.string "We lost!$"

Ace_Trainer_AlyssaPostBattle:
	.string "How dare you beat us!\n"
	.string "Go away! Go!$"

Ace_Trainer_AlyssaIntro:
	.string "As an Ace Trainer, I have to take\n"
	.string "battles in stride.\p"
	.string "I need to stay cool and calm whether\n"
	.string "I win or lose.$"

Ace_Trainer_AlyssaRematch:
	.string "Last time, I got a little emotional\n"
	.string "over losing...\p"
	.string "I’ll stay cool and calm today!$"

Ace_Trainer_AntonDefeat:
	.string "What’s with your toughness?!$"

Ace_Trainer_AntonPostBattle:
	.string "You’ve battled all over, you say?\n"
	.string "That makes you tough, perhaps.$"

Ace_Trainer_AntonIntro:
	.string "We spend all our time battling in the\n"
	.string "blizzards of Snowpoint City.\p"
	.string "We’ll show you how it’s toughened\n"
	.string "us up!$"

Ace_Trainer_ArthurDefeat:
	.string "This defeat has the tang of my bitter\n"
	.string "tears...$"

Ace_Trainer_ArthurPostBattle:
	.string "I’m sorry, my Pokémon team...\p"
	.string "I promise, I’ll get better at this so\n"
	.string "you can get a taste of victory!$"

Ace_Trainer_ArthurIntro:
	.string "I want my Pokémon to get a taste of\n"
	.string "the sweetness that is victory.\p"
	.string "I can’t afford to lose this one!$"

Ace_Trainer_BlakeDefeat:
	.string "But, how...?\n"
	.string "Am I weak at battling, too?$"

Ace_Trainer_BlakePostBattle:
	.string "I’d rather be asleep in the lodge’s\n"
	.string "bed...\p"
	.string "I can’t take this cold...$"

Ace_Trainer_BlakeIntro:
	.string "I’m an elite battler, but cold is\n"
	.string "my nemesis!$"

Ace_Trainer_BlakeRematch:
	.string "I’m an elite at battling, but cold is\n"
	.string "my nemesis!$"

Ace_Trainer_BrandiDefeat:
	.string "But...\n"
	.string "This isn’t possible!$"

Ace_Trainer_BrandiPostBattle:
	.string "It’s not that you’ve won.\n"
	.string "It’s just that I lost!\p"
	.string "...It’s all the same.\n"
	.string "Go, me.$"

Ace_Trainer_BrandiIntro:
	.string "I will win. I am sure of it.\n"
	.string "Therefore, you will lose!$"

Ace_Trainer_BreannaDefeat:
	.string "My focus was too narrow minded...$"

Ace_Trainer_BreannaPostBattle:
	.string "Start by becoming friendly with your\n"
	.string "Pokémon. I mean really friendly.\p"
	.string "If you do that, you’ll learn naturally\n"
	.string "how you should battle with it.$"

Ace_Trainer_BreannaIntro:
	.string "By focusing on only one type, you can\n"
	.string "really see the strengths and\p"
	.string "weaknesses of that Pokémon.$"

Ace_Trainer_BrendaDefeat:
	.string "That was good.\n"
	.string "You’ve bonded well with your Pokémon.$"

Ace_Trainer_BrendaPostBattle:
	.string "Tough Pokémon...\n"
	.string "Tough Trainers...\p"
	.string "Their strength comes from their bond.\n"
	.string "And that’s something that can be\p"
	.string "made stronger anywhere.$"

Ace_Trainer_BrendaIntro:
	.string "Tough Pokémon...\n"
	.string "Tough Trainers...\p"
	.string "You tell me, where else can I find\n"
	.string "a place as good as this to train?$"

Ace_Trainer_BrennaDefeat:
	.string "I can’t believe how tough you are!$"

Ace_Trainer_BrennaPostBattle:
	.string "If you have wonderful friends, there\n"
	.string "is no limit to how far you can go.$"

Ace_Trainer_BrennaIntro:
	.string "I’ve only been involved with Pokémon\n"
	.string "for a short time.\p"
	.string "I managed to get this far because\n"
	.string "skilled friends toughened me up!$"

Ace_Trainer_CatherineDefeat:
	.string "You’re the kind of person who can keep\n"
	.string "going forward even into the unknown.$"

Ace_Trainer_CatherinePostBattle:
	.string "I think, sometimes, one has to make\n"
	.string "mistakes to learn what is right.$"

Ace_Trainer_CatherineIntro:
	.string "What does it feel like, taking one step\n"
	.string "after another into darkness?$"

Ace_Trainer_CesarDefeat:
	.string "Wow...\n"
	.string "I’m in the mood to sing a lullaby...$"

Ace_Trainer_CesarPostBattle:
	.string "Your earnest enthusiasm...\n"
	.string "I guess that kinda makes you an ace.\p"
	.string "Maybe you’re a Trainer who has the\n"
	.string "potential to surpass aces!$"

Ace_Trainer_CesarIntro:
	.string "An ace has the knowledge and\n"
	.string "experience of battling at high levels.\p"
	.string "I’ll demonstrate what that means to\n"
	.string "a noob like you!$"

Ace_Trainer_ClariceDefeat:
	.string "You got way too much!$"

Ace_Trainer_ClaricePostBattle:
	.string "Well, I don’t have any advice for\n"
	.string "someone as tough as you!$"

Ace_Trainer_ClariceIntro:
	.string "Let me see what you got there, kid.\n"
	.string "I could give you some advice.$"

Ace_Trainer_DaltonDefeat:
	.string "Your heart burns as hot as mine!$"

Ace_Trainer_DaltonPostBattle:
	.string "The weather clears up sometimes.\n"
	.string "The view is breathtaking then.$"

Ace_Trainer_DaltonIntro:
	.string "This cold is but nothing compared\n"
	.string "to the fire that burns in my heart!$"

Ace_Trainer_DaltonRematch:
	.string "We’ll come at you with our hearts\n"
	.string "ablaze!$"

Ace_Trainer_DanaDefeat:
	.string "Your love of Pokémon really shows!$"

Ace_Trainer_DanaPostBattle:
	.string "I grew up together with Felix and\n"
	.string "my team, right from my childhood.\p"
	.string "All our memories, we’ve always shared\n"
	.string "them.$"

Ace_Trainer_DanaIntro:
	.string "You’re willing to battle?\n"
	.string "Let me see what you have?$"

Ace_Trainer_DanaRematch:
	.string "Oh, hi, we meet again.\p"
	.string "May I see what you’ve done with your\n"
	.string "Pokémon?$"

Ace_Trainer_DeannaDefeat:
	.string "I’ve found a tough adversary in\n"
	.string "you...$"

Ace_Trainer_DeannaPostBattle:
	.string "How much you believe in your\n"
	.string "Pokémon...\p"
	.string "That’s a critical factor in how a\n"
	.string "battle will turn out.$"

Ace_Trainer_DeannaIntro:
	.string "Worthy opponents... The search for\n"
	.string "them drives me to travel far.$"

Ace_Trainer_DeannaRematch:
	.string "We’ve faced many challengers since\n"
	.string "we met, but they were all weak...\p"
	.string "I relish the tough resistance that\n"
	.string "only you can provide!$"

Ace_Trainer_DennisDefeat:
	.string "You won and I lost, but the both of\n"
	.string "us gained something from this.$"

Ace_Trainer_DennisPostBattle:
	.string "In a Pokémon battle, it doesn’t\n"
	.string "matter how old or young you are.\p"
	.string "Your gender doesn’t matter, either.\n"
	.string "Nothing like that means anything!$"

Ace_Trainer_DennisIntro:
	.string "I’ll take on anyone!\n"
	.string "It can only make me stronger!$"

Ace_Trainer_DennisRematch:
	.string "I’ll battle against people who’ve\n"
	.string "beaten me again and again.\p"
	.string "By doing that, we both grow a little\n"
	.string "as Trainers.$"

Ace_Trainer_DestinyDefeat:
	.string "Your power is thrilling...\n"
	.string "I’m thrilled down to my toes!$"

Ace_Trainer_DestinyPostBattle:
	.string "I’m so glad that there are Pokémon!\p"
	.string "There isn’t much else that gives me\n"
	.string "the thrill that Pokémon do!$"

Ace_Trainer_DestinyIntro:
	.string "I’m not just looking for tough\n"
	.string "Trainers to battle.\p"
	.string "I’ve been battling here because\n"
	.string "I want to feel the rush!$"

Ace_Trainer_ErnestDefeat:
	.string "Haha!\n"
	.string "A total loss for me!$"

Ace_Trainer_ErnestPostBattle:
	.string "You seem to have an abundance of\n"
	.string "talent. It’s pretty amazing.$"

Ace_Trainer_ErnestIntro:
	.string "You seem to have a lot of confidence.\n"
	.string "Let’s see if it’s justified!$"

Ace_Trainer_ErnestRematch:
	.string "When I lost to you last time, I was\n"
	.string "just unlucky.$"

Ace_Trainer_FelixDefeat:
	.string "Did you enjoy the show?\n"
	.string "Super fabulous, wasn’t it?$"

Ace_Trainer_FelixPostBattle:
	.string "I’ll be happy to battle you again!\n"
	.string "Let’s battle again sometime, yeah?$"

Ace_Trainer_FelixIntro:
	.string "Welcome to my Pokémon show!$"

Ace_Trainer_FelixRematch:
	.string "Welcome to my new Pokémon show!$"

Ace_Trainer_GarrettDefeat:
	.string "Good job!\n"
	.string "That was an excellent battle.$"

Ace_Trainer_GarrettPostBattle:
	.string "If you don’t play for keeps, you’ll\n"
	.string "lose battles you should be dominating.$"

Ace_Trainer_GarrettIntro:
	.string "I always play for keeps!\n"
	.string "This isn’t practice!$"

Ace_Trainer_GarrettRematch:
	.string "When I lost to you last time, I was\n"
	.string "battling for keeps.\p"
	.string "But this time, I really mean it.\n"
	.string "This is seriously for keeps!$"

Ace_Trainer_GrahamDefeat:
	.string "It needs to be leveled more?!$"

Ace_Trainer_GrahamPostBattle:
	.string "My Pokémon...\p"
	.string "They’re the first friends I ever\n"
	.string "caught. They mean everything to me!$"

Ace_Trainer_GrahamIntro:
	.string "I took great pains raising my partners.\n"
	.string "I’ll show you how strong I made them!$"

Ace_Trainer_GrahamRematch:
	.string "...When I close my eyes, I can picture\n"
	.string "how we lost to you in vivid detail.\p"
	.string "But, I’ve raised them since then! I’ll\n"
	.string "throw their strength in your face!$"

Ace_Trainer_HenryDefeat:
	.string "That wasn’t how I planned the final\n"
	.string "chapter to go in my writing class...$"

Ace_Trainer_HenryPostBattle:
	.string "If you don’t give up, you can reach\n"
	.string "your goal.\p"
	.string "That perseverance is what’s important\n"
	.string "to Trainers. That’s in my book, too.$"

Ace_Trainer_HenryIntro:
	.string "Victory Road... Somehow, it feels as\n"
	.string "if my journey is now coming to an end.\p"
	.string "But, before the final chapter is\n"
	.string "written, I must pen your defeat!$"

Ace_Trainer_IsaiahDefeat:
	.string "You weren’t even fazed...$"

Ace_Trainer_IsaiahPostBattle:
	.string "I’ve battled countless Trainers\n"
	.string "and many more Pokémon still.\p"
	.string "My spirit has been hardened from all\n"
	.string "the battles I have fought.$"

Ace_Trainer_IsaiahIntro:
	.string "My willpower was shaped and tempered\n"
	.string "by howling blizzards.\p"
	.string "I’ll bring it to bear on you!$"

Ace_Trainer_JakeDefeat:
	.string "I’m burning with jealousy over your\n"
	.string "talent!$"

Ace_Trainer_JakePostBattle:
	.string "I think keeping up the effort to\n"
	.string "better yourself is a talent in itself.$"

Ace_Trainer_JakeIntro:
	.string "They call me an Ace Trainer.\p"
	.string "Allow me to demonstrate the talent\n"
	.string "that makes me so!$"

Ace_Trainer_JakeRematch:
	.string "Last time, you beat me before I had\n"
	.string "a chance to show you my skill.\p"
	.string "This time, I’ll shows you why they\n"
	.string "consider me an ace!$"

Ace_Trainer_JamieDefeat:
	.string "...Things don’t always work out\n"
	.string "according to my calculations...$"

Ace_Trainer_JamiePostBattle:
	.string "I had a lot of fun battling with\n"
	.string "you, though.\p"
	.string "I wonder if I can analyze the\n"
	.string "battle data properly?\p"
	.string "I could use a rematch to get\n"
	.string "some additional data.$"

Ace_Trainer_JamieIntro:
	.string "I constantly analyze Pokémon and\n"
	.string "various battles on my laptop.$"

Ace_Trainer_JamieRematch:
	.string "I analyzed our last battle on my\n"
	.string "laptop.$"

Ace_Trainer_JasminDefeat:
	.string "And another...\n"
	.string "A new memory was born.$"

Ace_Trainer_JasminPostBattle:
	.string "For me, space is where memories are\n"
	.string "made...$"

Ace_Trainer_JasminIntro:
	.string "Can you answer this for me?\n"
	.string "What is space?$"

Ace_Trainer_JonahDefeat:
	.string "You know, I would have really enjoyed\n"
	.string "a win there. Would’ve been real nice.$"

Ace_Trainer_JonahPostBattle:
	.string "This mine’s been abandoned, but\n"
	.string "now it’s home to many Pokémon.\p"
	.string "I guess everything finds a place\n"
	.string "to call home someday...$"

Ace_Trainer_JonahIntro:
	.string "If we were to battle, your Pokémon \n"
	.string "would become tougher.\p"
	.string "Likewise, my Pokémon would also\n"
	.string "become tougher.\p"
	.string "It’s all good.\n"
	.string "This calls for a battle!$"

Ace_Trainer_JoseDefeat:
	.string "Hmm. I like how you attack.$"

Ace_Trainer_JosePostBattle:
	.string "Pokémon and numbers...\n"
	.string "Who cares about that stuff?\p"
	.string "Winning is what’s important.\n"
	.string "Numbers aren’t everything.$"

Ace_Trainer_JoseIntro:
	.string "Have you any knowledge of levels\n"
	.string "or the stats of Pokémon? Well, I do!$"

Ace_Trainer_JoseRematch:
	.string "Pokémon battles aren’t decided by\n"
	.string "numbers.\p"
	.string "It’s the bond you share with your\n"
	.string "Pokémon that decides outcomes!$"

Ace_Trainer_KassandraDefeat:
	.string "Your dedication won out.$"

Ace_Trainer_KassandraPostBattle:
	.string "The Pokémon here must battle each\n"
	.string "other all the time.\p"
	.string "That must be why they are so strong\n"
	.string "in this area.$"

Ace_Trainer_KassandraIntro:
	.string "You’ve come all this way for Pokémon?\n"
	.string "You must be dedicated.$"

Ace_Trainer_KeenanDefeat:
	.string "I grow less certain still...$"

Ace_Trainer_KeenanPostBattle:
	.string "Perhaps there is no meaning to\n"
	.string "victory, but still I will battle!\p"
	.string "That is what makes me a Trainer!$"

Ace_Trainer_KeenanIntro:
	.string "What it means to win battles...\n"
	.string "That is what I seek.\p"
	.string "Teach me if you will!$"

Ace_Trainer_LauraDefeat:
	.string "Hunh?!$"

Ace_Trainer_LauraPostBattle:
	.string "Perhaps I should maybe change into\n"
	.string "a more comfy outfit...$"

Ace_Trainer_LauraIntro:
	.string "I’m fully kitted up and equipped!\n"
	.string "Anytime will be fine!$"

Ace_Trainer_LauraRematch:
	.string "I’m fully equipped again today!\n"
	.string "Anytime you’re ready will be fine!$"

Ace_Trainer_MariaDefeat:
	.string "Oh, yeah?\n"
	.string "Eat snowball, punk!$"

Ace_Trainer_MariaPostBattle:
	.string "You can make all the preparations in\n"
	.string "the world, but if it doesn’t work, it\p"
	.string "doesn’t work.$"

Ace_Trainer_MariaIntro:
	.string "To be ready to answer any call!\n"
	.string "To be ready to accept any challenge!\p"
	.string "That is the way of a Trainer!$"

Ace_Trainer_MariaRematch:
	.string "I got everything ready so we could\n"
	.string "have a rematch whenever you come.$"

Ace_Trainer_MariahDefeat:
	.string "So, that’s how you battled...?$"

Ace_Trainer_MariahPostBattle:
	.string "Once you emerge from Victory Road,\n"
	.string "the Pokémon League lies directly\p"
	.string "ahead...\p"
	.string "But many Trainers fail to ever find\n"
	.string "their way on Victory Road...$"

Ace_Trainer_MariahIntro:
	.string "Show me how you’ve battled to get\n"
	.string "here! Let’s do this!$"

Ace_Trainer_MayaDefeat:
	.string "You made me lose my confidence...$"

Ace_Trainer_MayaPostBattle:
	.string "I think about Pokémon all day long.\n"
	.string "I was confident, you know.$"

Ace_Trainer_MayaIntro:
	.string "I’m taking the Veilstone Gym\n"
	.string "challenge. But first...$"

Ace_Trainer_MayaRematch:
	.string "Oh, it’s you again!\p"
	.string "I’ve regained my confidence.\n"
	.string "Let’s have another battle!$"

Ace_Trainer_MeaganDefeat:
	.string "Yowch!$"

Ace_Trainer_MeaganPostBattle:
	.string "I heard that somewhere there’s\n"
	.string "someone who teaches Pokémon moves.$"

Ace_Trainer_MeaganIntro:
	.string "What sort of moves have you taught?\n"
	.string "That tells me how good you are!$"

Ace_Trainer_MeaganRematch:
	.string "Have you taught your team any new\n"
	.string "moves since last time?$"

Ace_Trainer_MicahDefeat:
	.string "Your Pokémon have a real peppy feel to\n"
	.string "them!$"

Ace_Trainer_MicahPostBattle:
	.string "Whether you’re talking to people or\n"
	.string "Pokémon, it’s important to always look\p"
	.string "them square in the eyes.$"

Ace_Trainer_MicahIntro:
	.string "When Trainers lock eyes...\p"
	.string "That’s right! It’s time to let\n"
	.string "their Pokémon go wild!$"

Ace_Trainer_MikaylaDefeat:
	.string "Wow, there are Pokémon that\n"
	.string "wonderful!$"

Ace_Trainer_MikaylaPostBattle:
	.string "There is always something to like\n"
	.string "about any Pokémon.\p"
	.string "It’s so hard to decide which ones\n"
	.string "I should raise.$"

Ace_Trainer_MikaylaIntro:
	.string "The world is huge, and there are\n"
	.string "so many different Pokémon!\p"
	.string "What kinds of Pokémon are with you?\n"
	.string "Please, I want to have a look!$"

Ace_Trainer_MikaylaRematch:
	.string "If I’m having trouble deciding,\n"
	.string "I go with my favorites!$"

Ace_Trainer_MoiraDefeat:
	.string "Hmm...$"

Ace_Trainer_MoiraPostBattle:
	.string "I feel invigorated from that battle,\n"
	.string "even though we lost.\p"
	.string "After all, we gave it everything we\n"
	.string "had.$"

Ace_Trainer_MoiraIntro:
	.string "Please don’t hold anything back.$"

Ace_Trainer_MoiraRematch:
	.string "Hello again! Please don’t hold\n"
	.string "anything back, just like before.$"

Ace_Trainer_MoniqueDefeat:
	.string "Aww...\n"
	.string "I’m out of useful items!$"

Ace_Trainer_MoniquePostBattle:
	.string "We came completely unprepared for\n"
	.string "this little adventure...$"

Ace_Trainer_MoniqueIntro:
	.string "We’re all good to go!\n"
	.string "We just have to battle now!$"

Ace_Trainer_NatashaDefeat:
	.string "But...\n"
	.string "I had a win streak going...$"

Ace_Trainer_NatashaPostBattle:
	.string "Train more at the Battle Tower...\n"
	.string "That’s what I’ll do.$"

Ace_Trainer_NatashaIntro:
	.string "I came here after winning my way\n"
	.string "through the Battle Tower!$"

Ace_Trainer_OliviaDefeat:
	.string "Whew...\n"
	.string "You’re overtrained for me.$"

Ace_Trainer_OliviaPostBattle:
	.string "Around these parts, perhaps because\n"
	.string "of all the snow, there are many\p"
	.string "folktales of hauntings...$"

Ace_Trainer_OliviaIntro:
	.string "Wh-what is it?\n"
	.string "P-Pokémon battle?!$"

Ace_Trainer_OliviaRematch:
	.string "This isn’t like last time. See how\n"
	.string "much I’ve trained since then!$"

Ace_Trainer_OmarDefeat:
	.string "You’re as tough as you look.$"

Ace_Trainer_OmarPostBattle:
	.string "One day, people will run to the other\n"
	.string "side of the road when I walk by ’em.\p"
	.string "It’s a goal of mine I’m working on.$"

Ace_Trainer_OmarIntro:
	.string "You... One look at you tells me\n"
	.string "you’re a real contender!$"

Ace_Trainer_QuinnDefeat:
	.string "My bunch got schooled, and how!$"

Ace_Trainer_QuinnPostBattle:
	.string "I fed my gang Protein, Carbos...\n"
	.string "You name it, I pumped ’em full of it.$"

Ace_Trainer_QuinnIntro:
	.string "I’ve pumped up my gang till they can’t\n"
	.string "get pumped no more.\p"
	.string "They’re going to school your Pokémon!$"

Ace_Trainer_QuinnRematch:
	.string "Hey! You’re that Trainer who schooled\n"
	.string "me and my Pokémon!\p"
	.string "OK, this time we’ll return the favor!\n"
	.string "We’ll be doing the schooling!$"

Ace_Trainer_RodolfoDefeat:
	.string "I see it now...$"

Ace_Trainer_RodolfoPostBattle:
	.string "Battling you was an eye-opener.\p"
	.string "I learned something very important\n"
	.string "in that short time.$"

Ace_Trainer_RodolfoIntro:
	.string "There is something missing in the\n"
	.string "way I battle...\p"
	.string "I’ve come here to find it.$"

Ace_Trainer_RodolfoRematch:
	.string "What’s missing from my game...\n"
	.string "Have you discovered yours yet?$"

Ace_Trainer_RubenDefeat:
	.string "You’re at a different level of\n"
	.string "expertise for sure!$"

Ace_Trainer_RubenPostBattle:
	.string "You’ve won countless times...\n"
	.string "That has made you very powerful.$"

Ace_Trainer_RubenIntro:
	.string "There’s something about you...\n"
	.string "You’re not just anybody.\p"
	.string "I challenge you!$"

Ace_Trainer_RubenRematch:
	.string "There’s something about you...\n"
	.string "You still remain extraordinary.\p"
	.string "I challenge you again!$"

Ace_Trainer_SandraDefeat:
	.string "You won’t let me win?$"

Ace_Trainer_SandraPostBattle:
	.string "I suddenly remembered what it was \n"
	.string "like when I had my first battle.\p"
	.string "I wonder why that would be?$"

Ace_Trainer_SandraIntro:
	.string "When eyes meet...\n"
	.string "That’s when a battle starts!$"

Ace_Trainer_SandraRematch:
	.string "When eyes meet...\n"
	.string "That’s when a battle starts!\p"
	.string "That’s what makes us Trainers!$"

Ace_Trainer_SaulDefeat:
	.string "I shouldn’t have paid attention\n"
	.string "to my urge...$"

Ace_Trainer_SaulPostBattle:
	.string "So long as my partner’s alongside me,\n"
	.string "I’m willing to take on the world!$"

Ace_Trainer_SaulIntro:
	.string "I’ve got the urge to battle with you.\n"
	.string "Hope you’re willing to oblige!$"

Ace_Trainer_SaulRematch:
	.string "The urge to battle you again has\n"
	.string "struck me. Humor me!$"

Ace_Trainer_SavannahDefeat:
	.string "You were surprisingly cool...\n"
	.string "At least I have my warm boots.$"

Ace_Trainer_SavannahPostBattle:
	.string "Your Pokémon look so hot in battle.\n"
	.string "So hot, they’re cool! Hahah!$"

Ace_Trainer_SavannahIntro:
	.string "Is the Gym’s trick floor making you\n"
	.string "a little hot under the collar?\p"
	.string "If you can’t maintain your cool in\n"
	.string "battle, you’ll freeze up.$"

Ace_Trainer_SergioDefeat:
	.string "This result...\n"
	.string "...It’s cold. Bitter cold.$"

Ace_Trainer_SergioPostBattle:
	.string "The higher up you slide from, the\n"
	.string "more speed you’ll have to smash\p"
	.string "those big snowballs.$"

Ace_Trainer_SergioIntro:
	.string "...It’s t-too cold.\n"
	.string "I can’t even feel my t-tongue.$"

Ace_Trainer_ShannonDefeat:
	.string "I see...\n"
	.string "I have to concede defeat.$"

Ace_Trainer_ShannonPostBattle:
	.string "Beaten in battle, but not in spirit.\n"
	.string "That’s the mark of a real Ace Trainer.$"

Ace_Trainer_ShannonIntro:
	.string "Really? So you think you can beat me?\n"
	.string "I’m an Ace Trainer, you do realize?$"

Ace_Trainer_ShannonRematch:
	.string "Ace Trainers always work to improve\n"
	.string "their natural-born talents.$"

Ace_Trainer_SkylarDefeat:
	.string "We went down...\n"
	.string "We couldn’t stick it out...$"

Ace_Trainer_SkylarPostBattle:
	.string "You can level all you want, but that\n"
	.string "won’t guarantee you any wins.\p"
	.string "But we keep trying to get better.\n"
	.string "That’s what makes us Trainers.$"

Ace_Trainer_SkylarIntro:
	.string "I was born in Floaroma Town.\n"
	.string "I’m sure thrilled to be here.\p"
	.string "It took a long time to get here.\n"
	.string "We’re not going to lose again!$"

Ace_Trainer_StefanDefeat:
	.string "Another memory...\n"
	.string "In a chain of memories.$"

Ace_Trainer_StefanPostBattle:
	.string "For me, time is the fabric woven by\n"
	.string "memories, one after another...$"

Ace_Trainer_StefanIntro:
	.string "Let me ask to see if you know.\n"
	.string "What is time?$"

Ace_Trainer_SydneyDefeat:
	.string "That battle just now must make you\n"
	.string "tougher than everyone in the world.$"

Ace_Trainer_SydneyPostBattle:
	.string "It doesn’t appear as if anyone could\n"
	.string "even try to stand against your might.\p"
	.string "The Elite Four should just surrender.$"

Ace_Trainer_SydneyIntro:
	.string "This total stranger’ll be a good way\n"
	.string "to see if I have what it takes to own\p"
	.string "the Pokémon League’s Elite Four!$"

Ace_Trainer_ZacheryDefeat:
	.string "What makes your Pokémon\n"
	.string "so special?$"

Ace_Trainer_ZacheryPostBattle:
	.string "As a challenger, you’re one tough\n"
	.string "Trainer.$"

Ace_Trainer_ZacheryIntro:
	.string "Wow! I’m surprised you’ve come this\n"
	.string "far, but you’ll have to turn back.\p"
	.string "There isn’t any chance that you\n"
	.string "could ever beat me!$"

Arcade_Star_Dahlia_DummyDefeat:
	.string "You are good, you!\n"
	.string "My Pokémon, they have enjoyed it, too!$"

Aroma_Lady_AlisonDefeat:
	.string "Waaah! You’re too much!$"

Aroma_Lady_AngelaDefeat:
	.string "Just like your inability to conceal\n"
	.string "your abundant skill.$"

Aroma_Lady_AngelaPostBattle:
	.string "Your next opponent is under four\n"
	.string "flowers.$"

Aroma_Lady_AngelaIntro:
	.string "Even concealed, there is no hiding\n"
	.string "the aroma of flowers.$"

Aroma_Lady_ElizabethDefeat:
	.string "Did you understand what I meant?\n"
	.string "Didn’t my Pokémon smell nice?$"

Aroma_Lady_ElizabethPostBattle:
	.string "If you plant lots of Berries, you\n"
	.string "can be surrounded by sweet scents.$"

Aroma_Lady_ElizabethIntro:
	.string "I love Pokémon that smell sweet.\n"
	.string "Like this one--get a whiff of this!$"

Aroma_Lady_ElizabethRematch:
	.string "Sniff... Oh?\n"
	.string "Your Pokémon smells nice!$"

Aroma_Lady_HannahDefeat:
	.string "Oh, you have us beaten.$"

Aroma_Lady_HannahPostBattle:
	.string "You and your Pokémon have so much\n"
	.string "energy.\p"
	.string "I think you would do well in\n"
	.string "Contests, too.$"

Aroma_Lady_HannahIntro:
	.string "Oh, you want to have a battle?\p"
	.string "I was meaning to enter a Contest,\n"
	.string "but beating you won’t take long...$"

Aroma_Lady_HannahRematch:
	.string "Oh, didn’t we meet before?\p"
	.string "I was meaning to enter a Contest,\n"
	.string "but let’s have a quick battle first.$"

Aroma_Lady_JennaDefeat:
	.string "The more beautiful a flower,\n"
	.string "the faster it withers...$"

Aroma_Lady_JennaPostBattle:
	.string "Oh, that’s right...\n"
	.string "A hint about the next Trainer...\p"
	.string "In the middle of three trees.\n"
	.string "That’s my hint. Good luck.$"

Aroma_Lady_JennaIntro:
	.string "My Grass-type Pokémon can dole out\n"
	.string "special attacks...\p"
	.string "I won’t let you win easily!$"

Aroma_Lady_TaylorDefeat:
	.string "It was a strong Trainer who was drawn\n"
	.string "here by the scent of flowers!$"

Aroma_Lady_TaylorPostBattle:
	.string "By the way, have you collected new\n"
	.string "apps from the Pokétch Company?$"

Aroma_Lady_TaylorIntro:
	.string "What kind of person are you, to be\n"
	.string "drawn here by the scent of flowers?$"

Aroma_Lady_TaylorRematch:
	.string "You came back to me because you\n"
	.string "couldn’t forget the smell of flowers!$"

Artist_IsmaelDefeat:
	.string "Does this mean I’m only talented as\n"
	.string "an Artist?$"

Artist_WilliamDefeat:
	.string "Magnificent!\n"
	.string "I am aglow with inspiration!$"

Artist_WilliamPostBattle:
	.string "That battle will surely become a\n"
	.string "stupendous masterpiece painting!\p"
	.string "I shall title it...\p"
	.string "“My Pokémon Is Fight”!$"

Artist_WilliamIntro:
	.string "You and I!\p"
	.string "Let us create a scene!\n"
	.string "A fantastic tableau of battle!$"

Artist_WilliamRematch:
	.string "The key to becoming a good painter\n"
	.string "is to be observant.\p"
	.string "That is the same for battling.\n"
	.string "One must be observant!$"

Battle_Girl_HelenDefeat:
	.string "No way! Give us another battle!\n"
	.string "...Oh, right. I’m out of Pokémon.$"

Battle_Girl_HelenPostBattle:
	.string "Yup! Good going!\n"
	.string "I like the way you battle!$"

Battle_Girl_HelenIntro:
	.string "OK, OK!\n"
	.string "Let’s be quick about this!$"

Battle_Girl_HelenRematch:
	.string "What took you so long?\n"
	.string "We’ve waited here a long time for\p"
	.string "a rematch with you!$"

Battle_Girl_KelseyDefeat:
	.string "I... I concede!\n"
	.string "I think you’re on a different level...$"

Battle_Girl_KelseyPostBattle:
	.string "Hiyah! You put me in my place!\n"
	.string "I appreciate it!$"

Battle_Girl_KelseyIntro:
	.string "Hiyah!\n"
	.string "There’s no holding anything back!$"

Battle_Girl_KelseyRematch:
	.string "Hiyah! This time, there really is no\n"
	.string "holding anything back!$"

Battle_Girl_TylerDefeat:
	.string "How could I lose now?!\n"
	.string "This is beyond aggravating!$"

Battle_Girl_TylerPostBattle:
	.string "I wish I could beat Maylene in\n"
	.string "Veilstone City one day...$"

Battle_Girl_TylerIntro:
	.string "Beating you would be my 100th\n"
	.string "straight win! Here’s to a fun battle!$"

Beauty_CyndyDefeat:
	.string "That’s how you attack?\n"
	.string "So harshly?$"

Beauty_CyndyPostBattle:
	.string "You’re so much more of a Trainer\n"
	.string "than you look!$"

Beauty_CyndyIntro:
	.string "Let me demonstrate my technique.\n"
	.string "It’s how this grown-up battles.$"

Beauty_CyndyRematch:
	.string "Give this grown-up another chance to\n"
	.string "demonstrate her technique.$"

Beauty_DevonDefeat:
	.string "Wow, is that right?$"

Beauty_DevonPostBattle:
	.string "There are so many kinds of Pokémon.\n"
	.string "I can’t decide which one to pamper.$"

Beauty_DevonIntro:
	.string "Oh? A little kid like you is going to\n"
	.string "teach me about Pokémon?$"

Beauty_DevonRematch:
	.string "Yoohoo, little kid! Can you teach me\n"
	.string "some more about Pokémon?$"

Beauty_GabriellaDefeat:
	.string "You’re a lucky one...$"

Beauty_HarleyDefeat:
	.string "I think I have what it takes to\n"
	.string "become a successful model!$"

Beauty_LindsayDefeat:
	.string "Aww, boo!\n"
	.string "Look, you’ve beaten me!$"

Beauty_LindsayPostBattle:
	.string "Giggle! There’s only our Gym Leader\n"
	.string "left. Go on, don’t be afraid!$"

Beauty_LindsayIntro:
	.string "Giggle! You found me!\n"
	.string "Of course, let’s battle!$"

Beauty_NicolaDefeat:
	.string "Enchanting.$"

Beauty_NicolaPostBattle:
	.string "Personally, I would much rather pamper\n"
	.string "Pokémon than make them battle.$"

Beauty_NicolaIntro:
	.string "After enjoying a meal at the hotel\n"
	.string "restaurant, one has a battle.\p"
	.string "That’s the social etiquette.$"

Beauty_NicolaRematch:
	.string "I only seem to run into you after\n"
	.string "I go to the restaurant.\p"
	.string "Etiquette calls for a battle after a\n"
	.string "meal. Shall we?$"

Bird_Keeper_AlexandraDefeat:
	.string "Oh, you!\n"
	.string "I’m going to peck you for that!$"

Bird_Keeper_AlexandraPostBattle:
	.string "There’s a bird Pokémon that can learn\n"
	.string "human speech! Did you know that?$"

Bird_Keeper_AlexandraIntro:
	.string "Look at these beautiful wings!$"

Bird_Keeper_AlexandraRematch:
	.string "My bird Pokémon has such gorgeous\n"
	.string "wings.\p"
	.string "It must have been some sort of a\n"
	.string "mistake that we lost last time!$"

Bird_Keeper_AudreyDefeat:
	.string "Sheesh... I arrive in a new place and\n"
	.string "it turns out to be the Battle Zone...$"

Bird_Keeper_AudreyPostBattle:
	.string "I was born in the Hoenn region.\n"
	.string "I’ve only just recently flown here.$"

Bird_Keeper_AudreyIntro:
	.string "I let my bird Pokémon carry me to\n"
	.string "wherever. And so, here I am!$"

Bird_Keeper_AudreyRematch:
	.string "I let my bird Pokémon do as they\n"
	.string "wish. And so, we train here daily!$"

Bird_Keeper_AutumnDefeat:
	.string "Don’t you have an Achilles’ heel?$"

Bird_Keeper_AutumnPostBattle:
	.string "I want to become stronger, but only\n"
	.string "with my favorite Pokémon.$"

Bird_Keeper_AutumnIntro:
	.string "The sharp vision of my bird Pokémon\n"
	.string "will see through your weaknesses!$"

Bird_Keeper_BriannaDefeat:
	.string "Wow. I admit to being surprised.$"

Bird_Keeper_BriannaPostBattle:
	.string "The sight of you battling...\n"
	.string "It was simply a wonder to watch!$"

Bird_Keeper_BriannaIntro:
	.string "I’ll teach you about the charms of\n"
	.string "bird Pokémon!$"

Bird_Keeper_BriannaRematch:
	.string "Are you finally getting the attractive\n"
	.string "qualities of bird Pokémon?$"

Bird_Keeper_GenevaDefeat:
	.string "How could you be tougher than\n"
	.string "Mother Nature?$"

Bird_Keeper_GenevaPostBattle:
	.string "Most of the time, my Pokémon return\n"
	.string "to their Poké Balls right away.\p"
	.string "But sometimes, they just fall asleep\n"
	.string "on top of my head. That gets messy.$"

Bird_Keeper_GenevaIntro:
	.string "My Pokémon grew up in the arms of\n"
	.string "Mother Nature. They’re tough!$"

Bird_Keeper_GenevaRematch:
	.string "The desire to win... That should be\n"
	.string "evident in every Trainer!$"

Bird_Keeper_HanaDefeat:
	.string "It seems I’ve been grounded...$"

Bird_Keeper_HanaPostBattle:
	.string "The wings of freedom...\p"
	.string "I know I’ll find them if I can win\n"
	.string "my way through the Pokémon League...$"

Bird_Keeper_HanaIntro:
	.string "I keep battling so I can soar\n"
	.string "ever higher into the skies!$"

Bird_Keeper_KatherineDefeat:
	.string "We did our best. That’s what\n"
	.string "matters. Right?$"

Bird_Keeper_KatherinePostBattle:
	.string "Even on cold days, just being with\n"
	.string "my NOCTOWL keeps me warm!$"

Bird_Keeper_KatherineIntro:
	.string "I go everywhere with my NOCTOWL.\n"
	.string "We’re gonna show you owl best! Ha!$"

Bird_Keeper_KatherineRematch:
	.string "I curled up inside my NOCTOWL’s wings\n"
	.string "and waited for you to return!$"

Bird_Keeper_KrystalDefeat:
	.string "We failed to get off the ground...$"

Bird_Keeper_KrystalPostBattle:
	.string "The HM Fly isn’t useful inside caves.\n"
	.string "It’s such a shame.$"

Bird_Keeper_KrystalIntro:
	.string "With one mighty flap, my birds blow\n"
	.string "away the embers of aggression!$"

Black_Belt_AdamDefeat:
	.string "B-but!\n"
	.string "My buff physique!$"

Black_Belt_AdamPostBattle:
	.string "Why? Is it because my training isn’t\n"
	.string "enough?!$"

Black_Belt_AdamIntro:
	.string "This buff physique isn’t just for\n"
	.string "show!$"

Black_Belt_AdamRematch:
	.string "My buff physique!\n"
	.string "Feast your eyes on it again!$"

Black_Belt_CarlDefeat:
	.string "The squad failed to hit its stride...$"

Black_Belt_CarlPostBattle:
	.string "Hmm...\p"
	.string "Gazing out over the sea doesn’t do a\n"
	.string "thing for toughening up my Pokémon!$"

Black_Belt_CarlIntro:
	.string "All right, my Pokémon squad!\n"
	.string "Get out there and kick up a storm!$"

Black_Belt_CarlRematch:
	.string "Ah, it’s been a long time!\p"
	.string "I have been toughening my fists\n"
	.string "against the sea, just as before!$"

Black_Belt_ColbyDefeat:
	.string "Argh! Crunched!$"

Black_Belt_ColbyPostBattle:
	.string "Your Pokémon sure are tough!\p"
	.string "But our Gym Leader Maylene will\n"
	.string "break you like a stack of bricks!$"

Black_Belt_ColbyIntro:
	.string "We’re the Karate Quads!\p"
	.string "I will strike a blow for love with my\n"
	.string "fist! Hiyah, looooooooove!$"

Black_Belt_DarrenDefeat:
	.string "I couldn’t force my way to victory...$"

Black_Belt_DarrenPostBattle:
	.string "To overwhelm by force...\n"
	.string "That is my ideal beat-down style.\p"
	.string "It doesn’t seem to work that way\n"
	.string "with Pokémon, however.$"

Black_Belt_DarrenIntro:
	.string "We’re the Karate Quads!\p"
	.string "I will strike a blow for courage with\n"
	.string "my fist! Hiyah, couraaaaaaaaaaage!$"

Black_Belt_DavidDefeat:
	.string "That was...\n"
	.string "A complete trashing!$"

Black_Belt_DavidPostBattle:
	.string "I must rededicate myself to training.\n"
	.string "The road extends into infinity...$"

Black_Belt_DavidIntro:
	.string "Aiyaah! We’re coming out swinging\n"
	.string "with super-heavy judo chops!$"

Black_Belt_DavonDefeat:
	.string "My spirit is broken...$"

Black_Belt_DavonPostBattle:
	.string "I thought I couldn’t win before it\n"
	.string "became a fact...\p"
	.string "I’ve let down my Pokémon...\p"
	.string "They go to battle with faith in\n"
	.string "their Trainer...$"

Black_Belt_DavonIntro:
	.string "My quest for power brought me here.\p"
	.string "It was beneath the desert sand that\n"
	.string "I toughened my body and soul.\p"
	.string "Accept my challenge! Uraah!$"

Black_Belt_DavonRematch:
	.string "This time! This time I will win!\n"
	.string "My spirit is renewed and strong!$"

Black_Belt_DerekDefeat:
	.string "You’ve dulled its sharpness...$"

Black_Belt_DerekPostBattle:
	.string "Back to training for us!$"

Black_Belt_DerekIntro:
	.string "Check the sharpness of my fighting\n"
	.string "Pokémon’s moves.$"

Black_Belt_DerekRematch:
	.string "I sharpened my Pokémon’s moves more\n"
	.string "for when I saw you again!$"

Black_Belt_EddieDefeat:
	.string "D  n     i\n"
	.string "  o  e     n...$"

Black_Belt_EddiePostBattle:
	.string "We’re gonna go ahead and leave...\n"
	.string "You know, go train elsewhere.$"

Black_Belt_EddieIntro:
	.string "I trained all of my gnarly Pokémon\n"
	.string "at the Fighting Dojo in Kanto!$"

Black_Belt_GregoryDefeat:
	.string "Gurgle...$"

Black_Belt_GregoryPostBattle:
	.string "If I lose here, I wouldn’t stand a\n"
	.string "chance at the Battle Frontier.\p"
	.string "Not against those hard-core pros,\n"
	.string "I wouldn’t!$"

Black_Belt_GregoryIntro:
	.string "You come along with your heart\n"
	.string "pounding!\p"
	.string "You think you can win like that?!\n"
	.string "Hiyah!$"

Black_Belt_GregoryRematch:
	.string "Am I lost, you ask?\n"
	.string "I merely feigned it! Hiyah!$"

Black_Belt_GriffinDefeat:
	.string "Ha-choo! Sniffle...$"

Black_Belt_GriffinPostBattle:
	.string "All that time under the waterfall...\n"
	.string "Seems I’ve caught a cold.$"

Black_Belt_GriffinIntro:
	.string "I have meditated under a waterfall\n"
	.string "to temper my spirit.\p"
	.string "Allow me to demonstrate its strength!$"

Black_Belt_GriffinRematch:
	.string "Since the day I lost to you, I’ve\n"
	.string "meditated under a waterfall!$"

Black_Belt_JarrettDefeat:
	.string "Losing made it clear to me.\n"
	.string "You’re crazy about Pokémon!$"

Black_Belt_JarrettPostBattle:
	.string "I love seeing people who love Pokémon\n"
	.string "more than anything!$"

Black_Belt_JarrettIntro:
	.string "Hear the howl of my iron fists!\n"
	.string "Howdy! I’m crazy for karate!$"

Black_Belt_JefferyDefeat:
	.string "I’m so hungry, kid...\n"
	.string "I don’t have any strength left...$"

Black_Belt_JefferyPostBattle:
	.string "I lost because I didn’t eat\n"
	.string "enough pizza.\p"
	.string "...No. Anything I say will sound\n"
	.string "like I’m making excuses.$"

Black_Belt_JefferyIntro:
	.string "We’re the Karate Quads!\p"
	.string "I will strike a blow for tears with\n"
	.string "my fist! Hiyah, teeeeeeaaaaaaaaars!$"

Black_Belt_KendalDefeat:
	.string "I’m so sorry...\n"
	.string "I got a bit mouthy there, didn’t I?$"

Black_Belt_KendalPostBattle:
	.string "So, I’m gonna try and shatter steel!\p"
	.string "I wonder how many more years it\n"
	.string "would take for me to do that?$"

Black_Belt_KendalIntro:
	.string "I’ll pound the fear of my fists into\n"
	.string "you all karate style, punk!$"

Black_Belt_KyleDefeat:
	.string "We got pulverized...$"

Black_Belt_KylePostBattle:
	.string "It’s obvious I need to train myself\n"
	.string "and my Pokémon harder.\p"
	.string "Hey, if you’ve got a Vs. Seeker, you’d\n"
	.string "better put it to good use.\p"
	.string "Nothing beats some repeated battling\n"
	.string "for toughening up your Pokémon.$"

Black_Belt_KyleIntro:
	.string "This karate man’s going to pulverize\n"
	.string "you!$"

Black_Belt_KyleRematch:
	.string "This karate man hasn’t forgotten\n"
	.string "being pulverized by you!$"

Black_Belt_LukeDefeat:
	.string "Achoo!$"

Black_Belt_LukePostBattle:
	.string "Maybe I’ll dress warm and come back.\n"
	.string "Hiyah!$"

Black_Belt_LukeIntro:
	.string "I dress light wherever I go.\n"
	.string "Hiyah!$"

Black_Belt_LukeRematch:
	.string "Lightly dressed like always.\n"
	.string "Hiyah!$"

Black_Belt_MilesDefeat:
	.string "I’ve met my match in strength!$"

Black_Belt_MilesPostBattle:
	.string "I’ve made it this far in life using the\n"
	.string "karate I learned on the Internet!$"

Black_Belt_MilesIntro:
	.string "My Pokémon knows karate!\n"
	.string "I’m warning you, it’s a tough one!$"

Black_Belt_NathanielDefeat:
	.string "I should be lighter by the amount of\n"
	.string "sweat I just shed!$"

Black_Belt_NathanielPostBattle:
	.string "It’s time for another workout.\n"
	.string "The more I sweat, the tougher I get!$"

Black_Belt_NathanielIntro:
	.string "Every drop of sweat I shed makes\n"
	.string "me that much stronger!$"

Black_Belt_NathanielRematch:
	.string "We’re going to win this time!\p"
	.string "Don’t believe me?\n"
	.string "Then you test it out!$"

Black_Belt_PhilipDefeat:
	.string "Huh? It’s over, you say?$"

Black_Belt_PhilipPostBattle:
	.string "Oh, gosh, this is bad! I think I’m\n"
	.string "losing feeling all over my body!$"

Black_Belt_PhilipIntro:
	.string "I can withstand this cold. That means\n"
	.string "I can take any kind of attack!$"

Black_Belt_PhilipRematch:
	.string "Oh? I’ve seen your face before.\n"
	.string "What say we battle?$"

Black_Belt_RafaelDefeat:
	.string "We came up short, but not by much.$"

Black_Belt_RafaelPostBattle:
	.string "I’ll have to redo my training, though.\n"
	.string "Maylene’s gonna trample me again...$"

Black_Belt_RafaelIntro:
	.string "We’re the Karate Quads!\p"
	.string "I will strike a blow for hope with my\n"
	.string "fist! Hiyah, hoooooooooooooope!$"

Black_Belt_RayDefeat:
	.string "We weren’t up to the task!$"

Black_Belt_RayPostBattle:
	.string "Even though my team could break\n"
	.string "bricks and shatter boulders, they\p"
	.string "failed to dent your spirits!$"

Black_Belt_RayIntro:
	.string "My Pokémon can destroy anything.\n"
	.string "And you think you can win?!$"

Black_Belt_RickyDefeat:
	.string "I never gave up, but still I failed to\n"
	.string "win...$"

Black_Belt_RickyPostBattle:
	.string "If you give up, well, that’s when\n"
	.string "everything ends for you!$"

Black_Belt_RickyIntro:
	.string "Steel represents an unbending spirit!\p"
	.string "If one refuses to accept defeat,\n"
	.string "the path to victory reveals itself!$"

Black_Belt_SeanDefeat:
	.string "I don’t get why we can’t win.$"

Black_Belt_SeanPostBattle:
	.string "I don’t reminisce over yesterday.\n"
	.string "I don’t think about tomorrow.\p"
	.string "I only live today to the fullest.\n"
	.string "That’s my policy!$"

Black_Belt_SeanIntro:
	.string "Hah! Hah!\n"
	.string "I’m psyched for this! Here goes!$"

Black_Belt_SeanRematch:
	.string "Hiyah! Hiyah! Hiyah! Hiyah!\n"
	.string "This time, I’m properly psyched!$"

Black_Belt_WillieDefeat:
	.string "Wrroar!\n"
	.string "Judo chop defeated!$"

Black_Belt_WilliePostBattle:
	.string "I’ll forget that we lost!\p"
	.string "...Wait, if I did that, we’d never\n"
	.string "learn from our mistakes...$"

Black_Belt_WillieIntro:
	.string "Judo chop!\n"
	.string "Pokémon battle!$"

Breeder_AlbertDefeat:
	.string "Good stuff! Your Pokémon are in\n"
	.string "impeccable condition.$"

Breeder_AlbertPostBattle:
	.string "It’s obvious you raise your Pokémon\n"
	.string "with a lot of love.$"

Breeder_AlbertIntro:
	.string "Let me see how much you’ve raised\n"
	.string "your Pokémon.$"

Breeder_AlbertRematch:
	.string "I’ve raised my Pokémon since we met.\n"
	.string "How much have you raised yours?$"

Breeder_AmberDefeat:
	.string "It’s all right!\n"
	.string "I’m still a rookie!$"

Breeder_AmberPostBattle:
	.string "The best way to raise Pokémon?\p"
	.string "...Hmm, when it comes right down to it,\n"
	.string "isn’t it all about love?$"

Breeder_AmberIntro:
	.string "I’m a rookie breeder, but I’ll do\n"
	.string "my very best!$"

Breeder_AmberRematch:
	.string "I can’t be a rookie forever.\n"
	.string "I’ve learned a lot since we last met.$"

Breeder_JenniferDefeat:
	.string "Giggle...\n"
	.string "They’re raised with a lot of care!$"

Breeder_JenniferPostBattle:
	.string "Raise your Pokémon with lots of love,\n"
	.string "and they’ll bond closely with you.$"

Breeder_JenniferIntro:
	.string "Please, let me battle the Pokémon\n"
	.string "you’ve raised!$"

Breeder_JenniferRematch:
	.string "I don’t want to ever battle with\n"
	.string "people who don’t treat Pokémon nice!\p"
	.string "But I know you treat yours kindly.\n"
	.string "I’ll battle you anytime!$"

Breeder_KahlilDefeat:
	.string "Hey, hey, did you take a good look?$"

Breeder_KahlilPostBattle:
	.string "The Veilstone Department Store is\n"
	.string "pretty impressive!\p"
	.string "Did you know they even sell Poffins?$"

Breeder_KahlilIntro:
	.string "Hey, check this out! Look at the\n"
	.string "luster of my Pokémon’s fur!$"

Breeder_KahlilRematch:
	.string "I brushed my party a lot.\n"
	.string "So we’d be ready for a rematch!$"

Breeder_KayleeDefeat:
	.string "You know, I had confidence before\n"
	.string "heading into this.$"

Buck_BattlegroundDefeat:
	.string "Heeheehee!\n"
	.string "So hot, you!$"

Bug_Catcher_BrandonDefeat:
	.string "I’m not going to be able to explain\n"
	.string "the charms of bug Pokémon this way!$"

Bug_Catcher_BrandonPostBattle:
	.string "Bug Pokémon grow quickly, and they do\n"
	.string "stuff like poison and paralyze, and\p"
	.string "they’re cute and yet cool.\p"
	.string "You gotta believe me. They’re good!$"

Bug_Catcher_BrandonIntro:
	.string "Hey, hey, let me show off my bug\n"
	.string "Pokémon!$"

Bug_Catcher_BrandonRematch:
	.string "So, listen. Tell me you’ve grown to\n"
	.string "like bug Pokémon since we last met.$"

Bug_Catcher_DonaldDefeat:
	.string "Awawawawah...$"

Bug_Catcher_DonaldPostBattle:
	.string "I thought it was a rare Pokémon, but\n"
	.string "it turned out to be just a Trainer!$"

Bug_Catcher_DonaldIntro:
	.string "My senses tingle...\n"
	.string "I’ve spotted a rare Pokémon!$"

Bug_Catcher_JackDefeat:
	.string "Don’t ignore bug Pokémon!\n"
	.string "That really bugs me!$"

Bug_Catcher_JackPostBattle:
	.string "It would seem that coolness alone\n"
	.string "doesn’t add up to any wins...$"

Bug_Catcher_JackIntro:
	.string "What’s cool, you might ask? No?\n"
	.string "I’ll tell you anyway: bug Pokémon!$"

Bug_Catcher_PhillipDefeat:
	.string "Whoooh...$"

Bug_Catcher_PhillipPostBattle:
	.string "There’s a Pokémon ability named Swarm.$"

Bug_Catcher_PhillipIntro:
	.string "Here comes the swarm!$"

Cameraman_DarrylDefeat:
	.string "That’s quite the demonstration.$"

Cameraman_TevinDefeat:
	.string "My camera’s too heavy.\n"
	.string "I couldn’t battle effectively...$"

Cameraman_Tevin_UnusedDefeat:
	.string "My camera’s too heavy.\n"
	.string "I couldn’t battle effectively...$"

Cameraman_Tevin_UnusedPostBattle:
	.string "The lively expressions on you and\n"
	.string "your Pokémon’s faces...\p"
	.string "It sure makes for some great TV!$"

Cameraman_Tevin_UnusedIntro:
	.string "I’ve spotted a charismatic Trainer!\n"
	.string "We just might have a scoop here!$"

Camper_AnthonyDefeat:
	.string "Oh...\n"
	.string "We lost...$"

Camper_AnthonyPostBattle:
	.string "Dig for Fossils in the Underground.\p"
	.string "The mining museum might be able to\n"
	.string "bring back the ancient Pokémon!$"

Camper_AnthonyIntro:
	.string "Go for it, my Pokémon!\n"
	.string "I’ll do my best, too!$"

Camper_AnthonyRematch:
	.string "Go for it, my Pokémon!\n"
	.string "I’ll do more than my best this time!$"

Camper_DiegoDefeat:
	.string "You didn’t really have to win!\n"
	.string "I’m not going to guide you now!$"

Camper_DiegoPostBattle:
	.string "I’m not lost, I tell you!\n"
	.string "I’m camping! That’s my story!$"

Camper_DiegoIntro:
	.string "Humph! You’re lost, aren’t you?\n"
	.string "I’ll guide you if you can beat me.$"

Camper_DrewDefeat:
	.string "Yeah, whatever.\n"
	.string "You can battle, too...$"

Camper_DrewPostBattle:
	.string "I’m gonna visit new places and find\n"
	.string "new Pokémon so I’ll be a know-it-all!$"

Camper_DrewIntro:
	.string "I’ve been to all sorts of places.\n"
	.string "That means I know tons of things!$"

Camper_JacobDefeat:
	.string "That really dampened my spirits.$"

Camper_JacobPostBattle:
	.string "I heard that really tough Pokémon\n"
	.string "appear in Eterna Forest.\p"
	.string "I need to be more prepared than this!$"

Camper_JacobIntro:
	.string "Hey, how about you and me battle before\n"
	.string "I go into Eterna Forest?$"

Camper_JacobRematch:
	.string "You’ve been to Eterna Forest\n"
	.string "already, right? How was it?$"

Camper_LawrenceDefeat:
	.string "I should’ve just stuck to\n"
	.string "camping out here...$"

Camper_LawrencePostBattle:
	.string "When I’m with my Pokémon, I can camp\n"
	.string "just about anywhere I want!$"

Camper_LawrenceIntro:
	.string "Yeah, I like to camp! So what?\n"
	.string "Let’s battle!$"

Camper_ParkerDefeat:
	.string "Lost?\n"
	.string "There’s nothing lost about this kid!$"

Camper_ParkerPostBattle:
	.string "I got separated from my friends...\p"
	.string "I’ve got my Pokémon with me, so I’m\n"
	.string "OK, but...$"

Camper_ParkerIntro:
	.string "Huh? Are you lost too?\n"
	.string "No? It doesn’t matter.\p"
	.string "Let’s have a quick Pokémon battle!$"

Camper_ZackaryDefeat:
	.string "Wawawaah!\n"
	.string "I’m out of Pokémon that can battle!$"

Camper_ZackaryPostBattle:
	.string "Camping with Pokémon!\n"
	.string "Do you have any idea how fun that is?$"

Camper_ZackaryIntro:
	.string "It’s a long way between Floaroma\n"
	.string "and Eterna City. So, let’s battle!$"

Camper_ZackaryRematch:
	.string "While I was enjoying camping, my\n"
	.string "Pokémon got all big and buffed up!$"

Castle_Valet_Darach_DummyDefeat:
	.string "My Pokémon can’t be faulted with\n"
	.string "anything.\p"
	.string "Your brilliance carried the day.$"

Champion_CynthiaDefeat:
	.string "...Just a few minutes ago, you were\n"
	.string "the most powerful challenger.\p"
	.string "And just now, you became the most\n"
	.string "powerful of all the Trainers.\p"
	.string "You are now our newest Champion!$"

Cheryl_BattlegroundDefeat:
	.string "Striking the right balance of offense\n"
	.string "and defense... It’s not easy to do.$"

Clown_LeeDefeat:
	.string "Oh, no, no, no!\n"
	.string "Mwahahah?$"

Clown_Lee_UnusedDefeat:
	.string "Oh, no, no, no!\n"
	.string "Mwahahah?$"

Clown_Lee_UnusedPostBattle:
	.string "A clown’s makeup is a face that’s\n"
	.string "crying while laughing. Mwahahah!\p"
	.string "It defines what we do!$"

Clown_Lee_UnusedIntro:
	.string "Are we all ready to have some fun?\n"
	.string "I sure am! Aren’t you having fun?!\p"
	.string "Let’s make it fun! OK?! Mwahahah!$"

Collector_BradyDefeat:
	.string "Your Pokédex fills me with such envy,\n"
	.string "envy, envy...$"

Collector_BradyPostBattle:
	.string "There’s all kinds of Trainers with all\n"
	.string "sorts of Pokémon with them.\p"
	.string "The more you battle, the more your\n"
	.string "Pokédex is filled!$"

Collector_BradyIntro:
	.string "What’s that?!\p"
	.string "You say you have a Pokédex?\n"
	.string "An authentic one!$"

Collector_BradyRematch:
	.string "Ooh, thank you!\p"
	.string "You came back to show me your Pokédex\n"
	.string "because I don’t have one!$"

Collector_DeanDefeat:
	.string "Youch! You sure showed me how tough\n"
	.string "you were.$"

Collector_DeanPostBattle:
	.string "Oh, what have we here?\n"
	.string "That’s a Pokédex!\p"
	.string "It records Pokémon data upon\n"
	.string "sight? I’ve never seen one before!\p"
	.string "I heard you can move the sun or\n"
	.string "moon icon to check the Pokémon\p"
	.string "habitat map by time of day!$"

Collector_DeanIntro:
	.string "I’m proud of my Pokémon!\n"
	.string "Here, I’ll show you why!$"

Collector_DeanRematch:
	.string "I take down details in my notebook\n"
	.string "about Pokémon I’ve battled.\p"
	.string "I’ll write more data down about your\n"
	.string "Pokémon!$"

Collector_DouglasDefeat:
	.string "That attack right then was remarkable!\n"
	.string "You ought to be proud of it!$"

Collector_DouglasPostBattle:
	.string "I take pride in having Pokémon that\n"
	.string "others don’t.\p"
	.string "Oh, I’m also proud about winning second\n"
	.string "prize in one of Jubilife TV’s drawings.$"

Collector_DouglasIntro:
	.string "For the sake of my collection, I\n"
	.string "take on people I know I can’t beat.\p"
	.string "That’s what a Collector does.$"

Collector_DouglasRematch:
	.string "For the sake of my collection, I\n"
	.string "keep battling people I can’t beat.\p"
	.string "That’s what a Collector does.$"

Collector_EdwinDefeat:
	.string "What’ve you done to my Pokémon?!\p"
	.string "It took me forever to catch it using\n"
	.string "Honey!$"

Collector_EdwinPostBattle:
	.string "I went through a lot of bother to catch\n"
	.string "my Pokémon.\p"
	.string "But since I’ve not raised it, it’s\n"
	.string "as weak as when I caught it.$"

Collector_EdwinIntro:
	.string "I’m a Collector, and I love Honey!$"

Collector_EugeneDefeat:
	.string "I don’t care if I lose.\n"
	.string "I’m still a happy guy.$"

Collector_FernandoDefeat:
	.string "Knowledge alone isn’t everything,\n"
	.string "you know...$"

Collector_FernandoPostBattle:
	.string "I’m more knowledgeable than anyone\n"
	.string "else!\p"
	.string "I have a rare Pokémon!\p"
	.string "But, I’m weak at battling...\n"
	.string "That’s a Pokémon Collector for you...$"

Collector_FernandoIntro:
	.string "We were having a heated discussion\n"
	.string "over Pokémon the way Collectors do.$"

Collector_IvanDefeat:
	.string "You’re one enthusiastic Trainer.$"

Collector_IvanPostBattle:
	.string "Pal Park, huh? I wonder what kinds\n"
	.string "of Pokémon you can see there?$"

Collector_IvanIntro:
	.string "Are you going to the Pal Park, too?\p"
	.string "For you, I’m willing to show off my\n"
	.string "prized Pokémon!$"

Collector_IvanRematch:
	.string "Pal Park, huh? I wonder what kinds\n"
	.string "of Pokémon you can see there?$"

Collector_JamalDefeat:
	.string "But they’re rare Pokémon!$"

Collector_JamalPostBattle:
	.string "If you’re trying to find the Pokémon\n"
	.string "you want, you need to go everywhere!\p"
	.string "Not just east and west, either.\n"
	.string "South and north are important, too!$"

Collector_JamalIntro:
	.string "To find my favorite Pokémon, I’ll go\n"
	.string "east, west, or any which way!$"

Collector_JamalRematch:
	.string "For my favorite Pokémon, I’ll go\n"
	.string "east, west, or any which way!\p"
	.string "...Saying that, I’ve been wandering\n"
	.string "around here all this time.$"

Collector_TerryDefeat:
	.string "You didn’t have a single Pokémon\n"
	.string "I wanted... You’re no Collector!$"

Collector_TerryPostBattle:
	.string "I’m very picky, so I want to collect\n"
	.string "every Pokémon without anyone’s help.\p"
	.string "...I do have friends, though.\n"
	.string "No, seriously! I do!$"

Collector_TerryIntro:
	.string "You look like you might just have\n"
	.string "the Pokémon I’ve been looking for!$"

Commander_Jupiter_Spear_PillarDefeat:
	.string "Humph! You’ve toughened up.\n"
	.string "But you’re no match for our boss.$"

Commander_Jupiter_Stark_MountainDefeat:
	.string "Humph! Quit flaunting your toughness!\n"
	.string "It’s not cute in the least!$"

Commander_Jupiter_Team_Galactic_Eterna_BuildingDefeat:
	.string "Losing to some child...\n"
	.string "Being careless cost me too much.$"

Commander_Mars_Lake_VerityDefeat:
	.string "...!\n"
	.string "Again and again...$"

Commander_Mars_Spear_PillarDefeat:
	.string "Sheesh... I should have done the\n"
	.string "fighting myself.$"

Commander_Mars_Stark_MountainDefeat:
	.string "What’s with you?!\n"
	.string "Do you have a vendetta against me?!$"

Commander_Mars_Valley_WindworksDefeat:
	.string "This can’t be?! I lost?!\n"
	.string "You...you uppity brat!$"

Commander_Saturn_Galactic_HqDefeat:
	.string "You’re tough, kid!\n"
	.string "But, I still pity the likes of you.$"

Commander_Saturn_Valor_CavernDefeat:
	.string "...You, my friend, are tough!\n"
	.string "I can see why you defy us so...$"

Cowgirl_ShelleyDefeat:
	.string "Fancy folks like you have fancy\n"
	.string "Pokémon too, it looks like.$"

Cowgirl_ShelleyPostBattle:
	.string "While working the ranch, I get to raise\n"
	.string "my Pokémon, too.\p"
	.string "I’d say it’s the best of both worlds!$"

Cowgirl_ShelleyIntro:
	.string "Say, honey, where’d you come from?\n"
	.string "What kinds of Pokémon are you with?$"

Cowgirl_ShelleyRematch:
	.string "Oh, howdy! Come visiting again?\n"
	.string "What kinds of Pokémon’d you bring?$"

Cyclist_AxelDefeat:
	.string "Hey, not bad, you!$"

Cyclist_AxelPostBattle:
	.string "This Cycling Road is one fine place--\n"
	.string "great bikes, superb Pokémon,\p"
	.string "and awesome Trainers all around!$"

Cyclist_AxelIntro:
	.string "Yo! Cycling and Pokémon!\n"
	.string "Which do you prefer?$"

Cyclist_AxelRematch:
	.string "I’m sure I’ve seen your face before.\n"
	.string "Did we maybe battle?$"

Cyclist_JamesDefeat:
	.string "Despite all the effort, I’m just spinning\n"
	.string "my wheels...\p"
	.string "It’s always that way with me!$"

Cyclist_JamesPostBattle:
	.string "I might try racing through Cycling\n"
	.string "Road in one long shot.$"

Cyclist_JamesIntro:
	.string "Ding-ding! Watch out, you!\n"
	.string "Or, did you want to battle?$"

Cyclist_JamesRematch:
	.string "There you are!\p"
	.string "I’ve been riding in this spot so I’d\n"
	.string "get a rematch with you!$"

Cyclist_JohnDefeat:
	.string "Crash! Tinkle...$"

Cyclist_JohnPostBattle:
	.string "The 3-speed makes for easy turning,\n"
	.string "and the 4-speed’s for going fast.\p"
	.string "I love them both!$"

Cyclist_JohnIntro:
	.string "That Bike you’ve got there...it’s the\n"
	.string "type that can change gears!\p"
	.string "You gotta love that!\n"
	.string "Sure, I’ll give you a battle!$"

Cyclist_JohnRematch:
	.string "Is your bicycle geared to 3-speed now?\n"
	.string "Or do you have it set to 4-speed?$"

Cyclist_KaylaDefeat:
	.string "Kerrrash!$"

Cyclist_KaylaPostBattle:
	.string "Aww!\n"
	.string "Why did you beat me?!\p"
	.string "I hope you get so lost in Wayward Cave\n"
	.string "you cry! Boo-hoo-hoo!$"

Cyclist_KaylaIntro:
	.string "If you beat me, you can count on\n"
	.string "something rotten coming your way!$"

Cyclist_KaylaRematch:
	.string "I had to get my revenge on you.\p"
	.string "I trained my Pokémon while lost and\p"
	.string "wandering in the Wayward Cave!$"

Cyclist_MeganDefeat:
	.string "Whew!\n"
	.string "You worked us over.$"

Cyclist_MeganPostBattle:
	.string "I like spinning the pedals backward\n"
	.string "while sailing downhill.$"

Cyclist_MeganIntro:
	.string "Cycling feels great!\p"
	.string "It will feel even better when I beat\n"
	.string "you in a battle!$"

Cyclist_MeganRematch:
	.string "It feels great on my Bike!\p"
	.string "I’m already sweaty, so let’s have a\n"
	.string "rematch!$"

Cyclist_NicoleDefeat:
	.string "Oh, geez...\n"
	.string "I seem to have fallen off my Bike.$"

Cyclist_NicolePostBattle:
	.string "I should have challenged you to a race,\n"
	.string "not a battle!$"

Cyclist_NicoleIntro:
	.string "The both of us are on Bikes, and we\n"
	.string "both have Pokémon!\p"
	.string "I can’t let you get the better of me!$"

Cyclist_NicoleRematch:
	.string "I hate knowing you’ve beaten me.\n"
	.string "This time, I’m going to win!$"

Cyclist_RachelDefeat:
	.string "You’re a speedy technician!$"

Cyclist_RachelPostBattle:
	.string "I enjoy the scenery.\p"
	.string "Don’t you think the area below\n"
	.string "Cycling Road looks nice?$"

Cyclist_RachelIntro:
	.string "Some people compete over speed, and\n"
	.string "some compete over technique.\p"
	.string "Which kind are you?$"

Cyclist_RachelRematch:
	.string "I polished up both my speed and\n"
	.string "techniques. Can you beat me now?$"

Cyclist_RyanDefeat:
	.string "Gasp... Gasp... Gasp...$"

Cyclist_RyanPostBattle:
	.string "My Pokémon and I are plumb worn out.\n"
	.string "We should be getting home to rest...$"

Cyclist_RyanIntro:
	.string "A bike will carry you a long way.\p"
	.string "The only thing that limits you is your\n"
	.string "own endurance!$"

Cyclist_RyanRematch:
	.string "We took a recuperative rest.\n"
	.string "We’re not losing this time!$"

Dragon_Tamer_ClintonDefeat:
	.string "That’s why I like it here; I get to\n"
	.string "battle tough characters like you.$"

Dragon_Tamer_ClintonPostBattle:
	.string "When two roads diverge, you must\n"
	.string "choose the path less traveled...$"

Dragon_Tamer_ClintonIntro:
	.string "This is a place where tough Trainers\n"
	.string "naturally congregate.\p"
	.string "It’s ideal for training!$"

Dragon_Tamer_DarienDefeat:
	.string "Arrrgh! My Pokémon...$"

Dragon_Tamer_DarienPostBattle:
	.string "I failed my Pokémon!\n"
	.string "I wasn’t prepared enough to lead it!\p"
	.string "I don’t ever want my precious Pokémon\n"
	.string "to be humiliated again!$"

Dragon_Tamer_DarienIntro:
	.string "My Pokémon and I seek only victory!$"

Dragon_Tamer_DarienRematch:
	.string "You’ve beaten us once before, but we\n"
	.string "won’t make the same mistake!$"

Dragon_Tamer_DrakeDefeat:
	.string "Losing isn’t a happy occasion...$"

Dragon_Tamer_DrakePostBattle:
	.string "My Pokémon seem to like it here\n"
	.string "a lot.$"

Dragon_Tamer_DrakeIntro:
	.string "Dragons and a fiery mountain...\n"
	.string "It’s a totally classic setup!$"

Dragon_Tamer_GeoffreyDefeat:
	.string "Raising abilities alone doesn’t mean\n"
	.string "I can win either...$"

Dragon_Tamer_GeoffreyPostBattle:
	.string "A Dragon Tamer Champion...\p"
	.string "I’ll need to train so much more to\n"
	.string "even come close to coming close...$"

Dragon_Tamer_GeoffreyIntro:
	.string "See the potential of dragon Pokémon!\n"
	.string "The Championship is within my sights!$"

Dragon_Tamer_GeoffreyRematch:
	.string "I’ve cranked up my dragon Pokémon’s\n"
	.string "abilities!\p"
	.string "I’ve been looking forward to seeing\n"
	.string "you again!$"

Dragon_Tamer_HaydenDefeat:
	.string "Your battle style...$"

Dragon_Tamer_HaydenPostBattle:
	.string "It’s been several years since I left\n"
	.string "the Dragon’s Den.\p"
	.string "I’ve got to say, your Pokémon are\n"
	.string "in the top class for toughness.$"

Dragon_Tamer_HaydenIntro:
	.string "My dragon Pokémon chose to become\n"
	.string "powerful here. They sure like it!$"

Dragon_Tamer_HaydenRematch:
	.string "My dragon Pokémon chose to remain\n"
	.string "here to become powerful.$"

Dragon_Tamer_JoeDefeat:
	.string "I lost? But how is that possible?!$"

Dragon_Tamer_JoePostBattle:
	.string "Getting the best out of any Pokémon...\n"
	.string "That’s what makes a good Trainer...$"

Dragon_Tamer_JoeIntro:
	.string "Learning how to manage tough Pokémon\n"
	.string "is the shortcut to getting tough.$"

Dragon_Tamer_KeeganDefeat:
	.string "Not good enough!\n"
	.string "We’re still not strong enough!$"

Dragon_Tamer_KeeganPostBattle:
	.string "It’s not good enough for a Pokémon\n"
	.string "to just be tough.\p"
	.string "It’s not good enough for a Trainer\n"
	.string "to just work hard.\p"
	.string "Both have to grow together!$"

Dragon_Tamer_KeeganIntro:
	.string "Dragon Pokémon are sacred beings...\n"
	.string "That’s what my master taught me.\p"
	.string "And now I’ll prove it to you!$"

Dragon_Tamer_KeeganRematch:
	.string "This time we’ll get it right!\p"
	.string "Marvel at the exquisite combination of\n"
	.string "my Pokémon and myself!$"

Dragon_Tamer_KennyDefeat:
	.string "There’s nothing left...$"

Dragon_Tamer_KennyPostBattle:
	.string "The mythical Pokémon that sleeps\n"
	.string "deep in a volcano...\p"
	.string "Could it be a dragon Pokémon?$"

Dragon_Tamer_KennyIntro:
	.string "Are you seeking the mythical\n"
	.string "Pokémon, too? Let’s battle, then!$"

Dragon_Tamer_OndrejDefeat:
	.string "There’s no way I could have won!$"

Dragon_Tamer_OndrejPostBattle:
	.string "How should I teach the most powerful\n"
	.string "of the Dragon-type moves...?$"

Dragon_Tamer_OndrejIntro:
	.string "I take Pokémon that are tough to begin\n"
	.string "with and toughen them up even more.\p"
	.string "You can help me!$"

Dragon_Tamer_PatrickDefeat:
	.string "Oh... My... Gosh...$"

Dragon_Tamer_PatrickPostBattle:
	.string "A dragon Pokémon’s real power is\n"
	.string "nothing like mine!$"

Dragon_Tamer_PatrickIntro:
	.string "Try not to be shocked when you lay your\n"
	.string "eyes on my Pokémon!$"

Dragon_Tamer_PatrickRematch:
	.string "You again?\p"
	.string "You must really like that dragon\n"
	.string "Pokémon I use.$"

Dragon_Tamer_StanleyDefeat:
	.string "Victory!\n"
	.string "That is, victory for you...$"

Dragon_Tamer_StanleyPostBattle:
	.string "It seems to me, there’s this certain\n"
	.string "image that goes with a Dragon Tamer.\p"
	.string "But me, I’d much sooner take it easy,\n"
	.string "take it slow, and take it my own way.\p"
	.string "I figure there’s more than my style\n"
	.string "that I need to work on first.$"

Dragon_Tamer_StanleyIntro:
	.string "How do you do?\n"
	.string "I’m Stanley, and I’m a Dragon Tamer.\p"
	.string "What do you say we let our Pokémon\n"
	.string "have it out? Sound OK to you?$"

Dragon_Tamer_StanleyRematch:
	.string "Hey, how do you do again?\p"
	.string "What do you say we let our Pokémon\n"
	.string "have at it again? Sound OK to you?$"

Elite_Four_AaronDefeat:
	.string "I will now concede defeat.\p"
	.string "But I think you came to see how\n"
	.string "great Bug-type Pokémon can be.\p"
	.string "I hope you also realized what you’re\n"
	.string "up against in the Pokémon League.\p"
	.string "Battling is a deep and complex\n"
	.string "affair...$"

Elite_Four_BerthaDefeat:
	.string "Well! Dear child, I must say, that\n"
	.string "was most impressive.\p"
	.string "Your Pokémon believed in you and did\n"
	.string "their best to earn you the win.\p"
	.string "Even though I’ve lost, I find myself\n"
	.string "with this silly grin!$"

Elite_Four_FlintDefeat:
	.string "...!\p"
	.string "I don’t believe it! I lost!\n"
	.string "I didn’t take you for granted...\p"
	.string "But I never expected you to win!\n"
	.string "I’d never even considered it!\p"
	.string "I’m blown away by this!\n"
	.string "You and your Pokémon are hot stuff!$"

Elite_Four_Flint_Fight_AreaDefeat:
	.string "...$"

Elite_Four_LucianDefeat:
	.string "I see...\p"
	.string "Your getting past the three before\n"
	.string "me was no fluke. Your power is real.$"

Factory_Head_Thorton_DummyDefeat:
	.string "Wow!\n"
	.string "You’re out of this world!$"

Fisherman_AlecDefeat:
	.string "You sure showed me up.$"

Fisherman_AlecPostBattle:
	.string "I like to fish.\n"
	.string "You’re a traveler.\p"
	.string "Farewell, until we meet again!$"

Fisherman_AlecIntro:
	.string "Hi, traveler!\n"
	.string "How would you like to battle?$"

Fisherman_AlecRematch:
	.string "Hi, traveler!\p"
	.string "I’ve forgotten your name, but we’ve\n"
	.string "battled before, haven’t we?$"

Fisherman_AndrewDefeat:
	.string "Well, that didn’t do anything for me...$"

Fisherman_AndrewPostBattle:
	.string "!\p"
	.string "Yank your fishing rod when that\n"
	.string "appears. That’s how you fish.$"

Fisherman_AndrewIntro:
	.string "Nothing’s biting...\n"
	.string "I could use a break, I suppose.$"

Fisherman_AndrewRematch:
	.string "All right! I caught some tough\n"
	.string "Pokémon. I’m ready for battle!$"

Fisherman_BrettDefeat:
	.string "A bittersweet smile is on my lips.$"

Fisherman_BrettPostBattle:
	.string "I’ve gone down in defeat.\n"
	.string "Whatever more is there to say?$"

Fisherman_BrettIntro:
	.string "Well, I am fishing, but...\p"
	.string "Very well!\n"
	.string "I accept your challenge!$"

Fisherman_BrettRematch:
	.string "Well, just as before, I’m fishing, but...\p"
	.string "Very well!\n"
	.string "I accept your challenge!$"

Fisherman_CodyDefeat:
	.string "Restraint is my favorite word.\n"
	.string "Like...from crushing my opponents.$"

Fisherman_CodyPostBattle:
	.string "You need a Good Rod if you want to\n"
	.string "catch good Pokémon.$"

Fisherman_CodyIntro:
	.string "Muhihi...\n"
	.string "I’ll haul you up and out!$"

Fisherman_CodyRematch:
	.string "Muhihi... There won’t be any\n"
	.string "restraint this time, OK?$"

Fisherman_ColeDefeat:
	.string "I don’t know how, but I lost!$"

Fisherman_ColePostBattle:
	.string "Oh, right...\n"
	.string "I was fishing, wasn’t I?$"

Fisherman_ColeIntro:
	.string "If I stare at the water’s surface\n"
	.string "for too long, I begin to forget what\p"
	.string "I was doing in the first place.$"

Fisherman_ColeRematch:
	.string "When I looked up from staring at the\n"
	.string "water’s surface, I saw your face.\p"
	.string "I’m not sure about what I was just\n"
	.string "doing, but do you want to battle?$"

Fisherman_CoryDefeat:
	.string "Sploosh!$"

Fisherman_CoryPostBattle:
	.string "If you don’t know how to fish, you’re\n"
	.string "missing half of life’s enjoyment.\p"
	.string "If you don’t know Pokémon...\n"
	.string "You’re missing out on all of it!$"

Fisherman_CoryIntro:
	.string "I like fishing, no question.\n"
	.string "But battling? That’s what I love!$"

Fisherman_CoryRematch:
	.string "Come on, battle me again!\n"
	.string "You know I love to fish and battle!$"

Fisherman_ErickDefeat:
	.string "Being number one in the world doesn’t\n"
	.string "mean a thing...$"

Fisherman_ErickPostBattle:
	.string "I figure I got too wrapped up in\n"
	.string "fishing and neglected training.$"

Fisherman_ErickIntro:
	.string "I’ve landed the most fish Pokémon\n"
	.string "in the world. I’m next!$"

Fisherman_GeorgeDefeat:
	.string "I’ve been done in...$"

Fisherman_GeorgePostBattle:
	.string "Thanks for that!\n"
	.string "It was a good change of pace for me.$"

Fisherman_GeorgeIntro:
	.string "I’m getting bored of fishing.\n"
	.string "Let’s have a quick battle!$"

Fisherman_GeorgeRematch:
	.string "Yo! I remember how our battle was a\n"
	.string "good change of pace before.\p"
	.string "Let’s have another quick battle!$"

Fisherman_JosephDefeat:
	.string "I let a big win slip away...$"

Fisherman_JosephPostBattle:
	.string "Do you have a fishing rod?\n"
	.string "Catch some big ones!$"

Fisherman_JosephIntro:
	.string "How about that!\n"
	.string "I’ve netted me a feisty Trainer!$"

Fisherman_JosephRematch:
	.string "Hey, you feisty tyke! I caught me\n"
	.string "a big one! Let’s battle again!$"

Fisherman_JoshDefeat:
	.string "Sure, so I lost.\n"
	.string "But I’ll keep on fishing.$"

Fisherman_JoshPostBattle:
	.string "If you know of any ladies that like\n"
	.string "fishing, help me reel ’em in!$"

Fisherman_JoshIntro:
	.string "I wish some fishing-loving lady’d come\n"
	.string "along. But no, it’s all just Trainers.$"

Fisherman_JoshRematch:
	.string "Umm... Yeah. Weren’t you that person\n"
	.string "who preferred Pokémon over fishing?$"

Fisherman_JuanDefeat:
	.string "How do you like that?\n"
	.string "Both my catch and the win got away!$"

Fisherman_JuanPostBattle:
	.string "Fishing and battling are delicate\n"
	.string "things--as am I. Is that wrong?$"

Fisherman_JuanIntro:
	.string "Can’t you see I’m fishing?\n"
	.string "Don’t talk! You’ll spook the fish!$"

Fisherman_JuanRematch:
	.string "You can see I’m fishing, can’t you?\n"
	.string "Then don’t talk to me! Geez!$"

Fisherman_KennethDefeat:
	.string "You need to have more respect for\n"
	.string "a grown-up...$"

Fisherman_KennethPostBattle:
	.string "Go on. Don’t be shy about going up to\n"
	.string "people to hear what they have to say...\p"
	.string "Just don’t you talk to me.$"

Fisherman_KennethIntro:
	.string "Waah! Now! Just now!\n"
	.string "I was just about to reel it in!$"

Fisherman_KennethRematch:
	.string "Waah! Now! Just now!\n"
	.string "I was just about to reel it in!\p"
	.string "...Right. You again!$"

Fisherman_LucDefeat:
	.string "Can’t catch a fish!\n"
	.string "Can’t catch a break!$"

Fisherman_LucPostBattle:
	.string "I was counting on strength in numbers,\n"
	.string "but...\p"
	.string "Packing it in and going home sounds good\n"
	.string "at a time like this...$"

Fisherman_LucIntro:
	.string "Yeah, yeah...\n"
	.string "Nothing’s biting!$"

Fisherman_LucRematch:
	.string "Yeah, yeah...\n"
	.string "Nothing’s biting today either.$"

Fisherman_MiguelDefeat:
	.string "Gwaaah!\n"
	.string "This is hurting!$"

Fisherman_MiguelPostBattle:
	.string "Oh, right... My shouting is scaring\n"
	.string "away the Pokémon.$"

Fisherman_MiguelIntro:
	.string "Outdoor fishing for the win!\p"
	.string "Shouting doesn’t help my fishing any,\n"
	.string "but shout I must!$"

Fisherman_MiguelRematch:
	.string "Super outdoor fishing!\n"
	.string "Shouting still doesn’t help!$"

Fisherman_TravisDefeat:
	.string "Oof. Just got trampled right under\n"
	.string "your feet that time!$"

Fisherman_TravisPostBattle:
	.string "Yup, a kid like you should be running\n"
	.string "around outside, rain or shine.$"

Fisherman_TravisIntro:
	.string "Water Pokémon sure get happy when\n"
	.string "it rains. So do I!$"

Fisherman_TravisRematch:
	.string "I’ve been fishing here ever since\n"
	.string "I lost to you.$"

Fisherman_WalterDefeat:
	.string "But the kid wins anyway!\n"
	.string "I’m just bowled over!$"

Fisherman_WalterPostBattle:
	.string "The water rising and falling is tricky,\n"
	.string "but don’t let it annoy you.\p"
	.string "If you lose sight of yourself, that’s\n"
	.string "when you’re set to lose.$"

Fisherman_WalterIntro:
	.string "I wield the stupendous power of water!\n"
	.string "Don’t think you can win!$"

Fisherman_ZacharyDefeat:
	.string "Losing to a kid has me gasping like\n"
	.string "a MAGIKARP...$"

Fisherman_ZacharyPostBattle:
	.string "My feet are tangled, too!\n"
	.string "Ouch! Ouch!$"

Fisherman_ZacharyIntro:
	.string "I fished up some tough Pokémon!\n"
	.string "Let’s have ourselves a battle!$"

Fisherman_ZacharyRematch:
	.string "I’m going to win this time!\n"
	.string "I said I’ll win, and I mean it!$"

Galactic_Boss_Cyrus_Celestic_Town_RuinsDefeat:
	.string "Impressive.\n"
	.string "Your prowess is notable.$"

Galactic_Boss_Cyrus_Distortion_WorldDefeat:
	.string "I won’t accept this!\n"
	.string "This can’t be!\p"
	.string "Not after all the sacrifices we’ve made\n"
	.string "to get this far!\p"
	.string "What of my new world?!\n"
	.string "Of my new galaxy?!\p"
	.string "Was this all a dream to be swept away\n"
	.string "by your reality?!$"

Galactic_Boss_Cyrus_Galactic_HqDefeat:
	.string "Interesting.\n"
	.string "And quite curious.$"

Galactic_Grunt_Celestic_TownDefeat:
	.string "I just got worked over!\n"
	.string "And by a kid no less...$"

Galactic_Grunt_Floaroma_Meadow_1Defeat:
	.string "...This is why I’m gonna be stuck as\n"
	.string "a grunt forever...$"

Galactic_Grunt_Floaroma_Meadow_2Defeat:
	.string "...I want a promotion so I can get some\n"
	.string "tougher Pokémon...$"

Galactic_Grunt_Galactic_Hq_1fDefeat:
	.string "A tough little Trainer is what you\n"
	.string "are...$"

Galactic_Grunt_Galactic_Hq_1fPostBattle:
	.string "In our HQ, we get around by taking\n"
	.string "warp panels.\p"
	.string "I’d like to see you figure out how\n"
	.string "they connect.$"

Galactic_Grunt_Galactic_Hq_1fIntro:
	.string "Who do you think you are?\n"
	.string "Desecrating the halls of our HQ?!$"

Galactic_Grunt_Galactic_Hq_2f_1Defeat:
	.string "...I wish this never happened.$"

Galactic_Grunt_Galactic_Hq_2f_1PostBattle:
	.string "Losing sets me back to square one...\p"
	.string "I’ll probably get busted down to the\n"
	.string "gruntiest of the grunts... Humph!$"

Galactic_Grunt_Galactic_Hq_2f_1Intro:
	.string "I’m, like, this close to getting my\n"
	.string "promotion to Commander.\p"
	.string "I’ll impress our great boss by making\n"
	.string "you my newest trophy!$"

Galactic_Grunt_Galactic_Hq_2f_2Defeat:
	.string "Your trailblazing streak lives on!$"

Galactic_Grunt_Galactic_Hq_2f_2PostBattle:
	.string "So what, you have momentum...\n"
	.string "It’s too late. The experiment’s done!$"

Galactic_Grunt_Galactic_Hq_2f_2Intro:
	.string "Having fun scampering around our HQ,\n"
	.string "you sneaky intruder?\p"
	.string "Your trail blazing will go out in\n"
	.string "a blaze of glory right now!$"

Galactic_Grunt_Galactic_Hq_2f_3Defeat:
	.string "What? I don’t get it.\n"
	.string "What’s your rush?$"

Galactic_Grunt_Galactic_Hq_2f_3PostBattle:
	.string "Pokémon are that important to you?\n"
	.string "Is that what this is all about?$"

Galactic_Grunt_Galactic_Hq_2f_3Intro:
	.string "You should be tired out by now.\n"
	.string "It’s Team Galactic’s turn to shine!$"

Galactic_Grunt_Galactic_Hq_3f_1Defeat:
	.string "I failed to read the flow of battle, and\n"
	.string "your power was unfathomable...$"

Galactic_Grunt_Galactic_Hq_3f_1PostBattle:
	.string "Come on, I said something cool before\n"
	.string "the battle.\p"
	.string "You need to read the dramatic situation\n"
	.string "better here!$"

Galactic_Grunt_Galactic_Hq_3f_1Intro:
	.string "You’re too young to understand the\n"
	.string "changing times!\p"
	.string "Stand aside and let Team Galactic\n"
	.string "shape the future!$"

Galactic_Grunt_Galactic_Hq_3f_2Defeat:
	.string "Oh, it was my own Pokémon’s smell...$"

Galactic_Grunt_Galactic_Hq_3f_2PostBattle:
	.string "How could we arouse suspicion?\n"
	.string "We’re Team Galactic, and this is our HQ!$"

Galactic_Grunt_Galactic_Hq_3f_2Intro:
	.string "Intruder alert!\n"
	.string "There’s something smelly about you!$"

Galactic_Grunt_Galactic_Hq_3f_3Defeat:
	.string "Let me do what I want!$"

Galactic_Grunt_Galactic_Hq_3f_3PostBattle:
	.string "It doesn’t matter what happens to\n"
	.string "the Team Galactic HQ building.\p"
	.string "Soon, all will belong to Team\n"
	.string "Galactic, anyway!$"

Galactic_Grunt_Galactic_Hq_3f_3Intro:
	.string "Are you enjoying your unescorted,\n"
	.string "unauthorized, and unsettling tour\p"
	.string "of Team Galactic HQ?$"

Galactic_Grunt_Galactic_Hq_3f_4Defeat:
	.string "I just blew my promotion...$"

Galactic_Grunt_Galactic_Hq_3f_4PostBattle:
	.string "What’s so special about you anyway?\p"
	.string "You’re just like any other little kid\n"
	.string "Trainer you can find anywhere!$"

Galactic_Grunt_Galactic_Hq_3f_4Intro:
	.string "Hey there, little Trainer!\n"
	.string "You’re famous among Team Galactic.\p"
	.string "The order has been issued--we get\n"
	.string "a promotion if we put you down!$"

Galactic_Grunt_Galactic_Hq_B2f_1Defeat:
	.string "You’re lost but you won!\n"
	.string "That burns me up to eleven!$"

Galactic_Grunt_Galactic_Hq_B2f_1PostBattle:
	.string "You barged right into our HQ?\n"
	.string "You must not know what fear is, kid!$"

Galactic_Grunt_Galactic_Hq_B2f_1Intro:
	.string "Well, what have we here?\n"
	.string "A Trainer who’s lost their way?$"

Galactic_Grunt_Galactic_Hq_B2f_2Defeat:
	.string "Oh, sure. Why don’t you just get\n"
	.string "all cocky about it!$"

Galactic_Grunt_Galactic_Hq_B2f_2PostBattle:
	.string "Without our special card key, you’re\n"
	.string "not going to get very far.\p"
	.string "Well, non-Team Galactic member?\n"
	.string "What’s your next move?$"

Galactic_Grunt_Galactic_Hq_B2f_2Intro:
	.string "What with that creepy Charon and a kid\n"
	.string "like you around, the HQ’s not the\p"
	.string "same anymore.\p"
	.string "Like, you characters changed the,\n"
	.string "well, character of the place!$"

Galactic_Grunt_Iron_Island_1Defeat:
	.string "I want to cry...\n"
	.string "My heart is shattered...$"

Galactic_Grunt_Iron_Island_2Defeat:
	.string "They’re too tough to handle!\n"
	.string "What a combination!$"

Galactic_Grunt_Jubilife_City_1Defeat:
	.string "How is this madness possible?\n"
	.string "The two of us, losing to children?$"

Galactic_Grunt_Jubilife_City_2Defeat:
	.string "This won’t do... Time to retreat.\n"
	.string "This mission is a failure.$"

Galactic_Grunt_Lake_Valor_1Defeat:
	.string "Your Pokémon attack with phenomenal\n"
	.string "power...$"

Galactic_Grunt_Lake_Valor_1PostBattle:
	.string "But so what?\n"
	.string "You aim to take us all on?\p"
	.string "Dream on!\n"
	.string "Team Galactic is huge in number.\p"
	.string "Even as we speak, other members should\n"
	.string "be near Twinleaf Town.\p"
	.string "That’s right, they’re on the way to\n"
	.string "Lake Verity!$"

Galactic_Grunt_Lake_Valor_1Intro:
	.string "We set off the Galactic Bomb!\n"
	.string "Its blast force was phenomenal!$"

Galactic_Grunt_Lake_Valor_2Defeat:
	.string "Grr...\n"
	.string "I took the punishment...$"

Galactic_Grunt_Lake_Valor_2PostBattle:
	.string "We’re Team Galactic!\n"
	.string "The no. 1 syndicate in the world!\p"
	.string "To defy us is to defy the universe!$"

Galactic_Grunt_Lake_Valor_2Intro:
	.string "I’ll punish you in place of our\n"
	.string "boss for defying Team Galactic!$"

Galactic_Grunt_Lake_Valor_3Defeat:
	.string "...Overwhelming!$"

Galactic_Grunt_Lake_Valor_3PostBattle:
	.string "I played you for a child, and paid\n"
	.string "a stiff price for my arrogance...\p"
	.string "However, you’re much too late.\p"
	.string "Team Galactic has already found the\n"
	.string "sunken island under the lake.\p"
	.string "And the Pokémon that lay in it?\n"
	.string "Well, what do you think?$"

Galactic_Grunt_Lake_Valor_3Intro:
	.string "...Would you like to join the MAGIKARP\n"
	.string "and flop around in the mud?$"

Galactic_Grunt_Lake_Verity_1Defeat:
	.string "Losing was a part of my job, too.\n"
	.string "...I feel better by saying that.$"

Galactic_Grunt_Lake_Verity_1PostBattle:
	.string "From three lakes, we must secure three\n"
	.string "Pokémon.\p"
	.string "You simply mustn’t interfere!$"

Galactic_Grunt_Lake_Verity_1Intro:
	.string "It is our mission to stall you.\n"
	.string "Sorry, but we gotta do our job.$"

Galactic_Grunt_Lake_Verity_2Defeat:
	.string "You’re too young to understand.$"

Galactic_Grunt_Lake_Verity_2PostBattle:
	.string "Our boss always had plans for\n"
	.string "the three lakes...\p"
	.string "While you were blissfully ignorant,\n"
	.string "our work went ahead...$"

Galactic_Grunt_Lake_Verity_2Intro:
	.string "In order for us to bring peace to\n"
	.string "the world, we must control it!$"

Galactic_Grunt_Lake_Verity_3Defeat:
	.string "My mind is going orbital!$"

Galactic_Grunt_Lake_Verity_3PostBattle:
	.string "The Pokémon here has already been\n"
	.string "taken to our HQ in Veilstone.\p"
	.string "So, you see?\n"
	.string "A child like you can’t touch us!$"

Galactic_Grunt_Lake_Verity_3Intro:
	.string "I’ll knock your Pokémon into orbit!$"

Galactic_Grunt_Lake_Verity_4Defeat:
	.string "There goes our bonus...\n"
	.string "This is an epic tragedy...$"

Galactic_Grunt_Lake_Verity_4PostBattle:
	.string "I want Team Galactic to become\n"
	.string "powerful. That is all I want.$"

Galactic_Grunt_Lake_Verity_4Intro:
	.string "If this mission is successful, we\n"
	.string "will get a nice bonus.$"

Galactic_Grunt_Mt_Coronet_3f_1Defeat:
	.string "When’s it gonna be my turn...$"

Galactic_Grunt_Mt_Coronet_3f_1PostBattle:
	.string "It’s too late!\p"
	.string "No amount of desperation from a kid\n"
	.string "like you will make a difference!$"

Galactic_Grunt_Mt_Coronet_3f_1Intro:
	.string "Our time has come!\n"
	.string "It’s Team Galactic’s time now!$"

Galactic_Grunt_Mt_Coronet_3f_2Defeat:
	.string "I don’t accept this!\n"
	.string "I will not accept this!$"

Galactic_Grunt_Mt_Coronet_3f_2PostBattle:
	.string "Join Team Galactic and then abide\n"
	.string "by our rules.\p"
	.string "That would solve all our problems!$"

Galactic_Grunt_Mt_Coronet_3f_2Intro:
	.string "We Grunts have two jobs.\p"
	.string "One, ensure the success of our\n"
	.string "operation at the summit.\p"
	.string "Two, utterly destroy any intruders\n"
	.string "to stop their meddling!$"

Galactic_Grunt_Mt_Coronet_4f_1Defeat:
	.string "Gyah!$"

Galactic_Grunt_Mt_Coronet_4f_1PostBattle:
	.string "You can struggle all you want, but\n"
	.string "you can’t stop Team Galactic alone!\p"
	.string "It doesn’t matter how many Pokémon\n"
	.string "you try to use as your tools!$"

Galactic_Grunt_Mt_Coronet_4f_1Intro:
	.string "Our time is coming!\n"
	.string "A time for us alone!\p"
	.string "We’ll send you back in time.\n"
	.string "A time before you started training!$"

Galactic_Grunt_Mt_Coronet_4f_2Defeat:
	.string "Not standing up to the mighty is\n"
	.string "foolish, you say...$"

Galactic_Grunt_Mt_Coronet_4f_2PostBattle:
	.string "It doesn’t matter if you’re an adult\n"
	.string "or a kid if you have Pokémon...\p"
	.string "Pokémon are the equalizers.\n"
	.string "I should have realized sooner...$"

Galactic_Grunt_Mt_Coronet_4f_2Intro:
	.string "Team Galactic is all powerful!\p"
	.string "Only a fool would show defiance to\n"
	.string "the mighty might of Team Galactic!$"

Galactic_Grunt_Mt_Coronet_5f_1Defeat:
	.string "All you gave me was the taste of\n"
	.string "defeat...$"

Galactic_Grunt_Mt_Coronet_5f_1PostBattle:
	.string "...Is our boss about to ditch us\n"
	.string "and claim everything for himself?$"

Galactic_Grunt_Mt_Coronet_5f_1Intro:
	.string "Team Galactic will take control of\n"
	.string "everything!\p"
	.string "You can try all you want, but you\n"
	.string "can’t do anything alone!$"

Galactic_Grunt_Mt_Coronet_5f_2Defeat:
	.string "You’re not supposed to work me\n"
	.string "over like that.$"

Galactic_Grunt_Mt_Coronet_5f_2PostBattle:
	.string "All my excitement’s gone now...\p"
	.string "This whole Mt. Coronet trip is too\n"
	.string "rough, long, and draining...$"

Galactic_Grunt_Mt_Coronet_5f_2Intro:
	.string "...Our boss is going to do something\n"
	.string "huge at the summit.\p"
	.string "But here I am dealing with some pesky\n"
	.string "intruder.\p"
	.string "You’re spoiling the atmosphere.\n"
	.string "You can lose quickly, right?$"

Galactic_Grunt_Mt_Coronet_6fDefeat:
	.string "Wh-- How dare you! That’s how you\n"
	.string "respond to my generosity?$"

Galactic_Grunt_Mt_Coronet_6fPostBattle:
	.string "We couldn’t stop you...\n"
	.string "We’ll be discarded as useless...\p"
	.string "Our boss is ruthless that way...$"

Galactic_Grunt_Mt_Coronet_6fIntro:
	.string "You’ve worked so hard to get here.\n"
	.string "You should be proud of yourself!\p"
	.string "And now, I’ll send you packing home\n"
	.string "with only that happy thought!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_1Defeat:
	.string "Where do you get that power?!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_1PostBattle:
	.string "Mt. Coronet...\p"
	.string "I might be just a grunt, but even I\n"
	.string "can tell it has a weird energy!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_1Intro:
	.string "I can’t believe you chased me here...\n"
	.string "OK, let’s see how tough you are.$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_2Defeat:
	.string "You turned the tables on me...\n"
	.string "I call interference...$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_2PostBattle:
	.string "The closer you are to the peak,\n"
	.string "the closer you are to space!\p"
	.string "Soon, Team Galactic will... Uh...\n"
	.string "Team Galactic will achieve greatness!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_2Intro:
	.string "This is our final operation.\n"
	.string "No one will interfere!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_3Defeat:
	.string "See? You’ve left me brokenhearted,\n"
	.string "too...$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_3PostBattle:
	.string "Someone’s joy is another person’s\n"
	.string "sorrow...\p"
	.string "Everyone be happy and laughing?\n"
	.string "How ridiculous!\p"
	.string "Team Galactic should be doing all the\n"
	.string "laughing!$"

Galactic_Grunt_Mt_Coronet_Tunnel_Room_3Intro:
	.string "Say, listen, do you realize you’re\n"
	.string "breaking hearts by being successful?\p"
	.string "It’s your fault that Team Galactic\n"
	.string "members are in so much pain...$"

Galactic_Grunt_Spear_Pillar_1Defeat:
	.string "The toughest of all the grunts!\n"
	.string "That was me...$"

Galactic_Grunt_Spear_Pillar_2Defeat:
	.string "Arrgh!\n"
	.string "I let some little kid beat me!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_1Defeat:
	.string "I feel like I got meddled with...$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_1PostBattle:
	.string "Our astonishing undertaking is\n"
	.string "most certainly breathtaking.\p"
	.string "If you ever hope to see its glorious\n"
	.string "unveiling, then don’t meddle with us!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_1Intro:
	.string "We are acquiring Pokémon for a most\n"
	.string "astonishing undertaking!\p"
	.string "Your meddling won’t be tolerated!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_2Defeat:
	.string "B-but, deary, you’re just a kid!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_2PostBattle:
	.string "You wanted to go up?\n"
	.string "Well, why didn’t you?$"

Galactic_Grunt_Team_Galactic_Eterna_Building_1f_2Intro:
	.string "So sorry, sweetie.\n"
	.string "Team Galactic has no room for kiddies!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_1Defeat:
	.string "What was I fighting for, again?$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_1PostBattle:
	.string "What do you have against taking\n"
	.string "Pokémon from others?\p"
	.string "Look in any field or forest!\n"
	.string "Those things aren’t exactly rare!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_1Intro:
	.string "Our objectives are incredible!\n"
	.string "Too incredible for me to understand!\p"
	.string "I’ll fight blindly to defend them,\n"
	.string "and your intrusion won’t be forgiven!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_2Defeat:
	.string "What is this?!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_2PostBattle:
	.string "Wimpy little Pokémon...\p"
	.string "When I get promoted, I’ll demand\n"
	.string "better stolen Pokémon.$"

Galactic_Grunt_Team_Galactic_Eterna_Building_2f_2Intro:
	.string "Let’s see how good this Pokémon is!\n"
	.string "I stole it from some weak Trainer.$"

Galactic_Grunt_Team_Galactic_Eterna_Building_3fDefeat:
	.string "What do you think you’re doing?!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_3fPostBattle:
	.string "You can catch Pokémon anywhere.\n"
	.string "What’s so special about them?\p"
	.string "Trainers that lose theirs should\n"
	.string "quit whining and catch some more!$"

Galactic_Grunt_Team_Galactic_Eterna_Building_3fIntro:
	.string "Why, thank you!\p"
	.string "We love it when people come to us\n"
	.string "to donate their Pokémon!$"

Galactic_Grunt_Valley_Windworks_1Defeat:
	.string "Yeah, like I’m really supposed to\n"
	.string "win with a Pokémon like this...$"

Galactic_Grunt_Valley_Windworks_2Defeat:
	.string "What...?!\n"
	.string "Some brat messed up my job...$"

Galactic_Grunt_Valley_Windworks_2PostBattle:
	.string "Team Galactic needs electricity for\n"
	.string "doing something big!$"

Galactic_Grunt_Valley_Windworks_2Intro:
	.string "Oi! This is no fun and games!\n"
	.string "This is proper work, I tell you!$"

Galactic_Grunt_Valley_Windworks_3Defeat:
	.string "I really don’t like kids who also\n"
	.string "happen to be tough Trainers...$"

Galactic_Grunt_Valley_Windworks_3PostBattle:
	.string "You don’t have an inkling of what\n"
	.string "Team Galactic is trying to achieve!\p"
	.string "Of course, they don’t tell a grunt\n"
	.string "like me anything, either... But still!$"

Galactic_Grunt_Valley_Windworks_3Intro:
	.string "Collecting electricity from the Valley\n"
	.string "Windworks... That’s our mission.$"

Galactic_Grunt_Valor_LakefrontDefeat:
	.string "Fweh... If I didn’t run...\n"
	.string "I could’ve...battled harder...$"

Galactic_Grunt_Veilstone_City_1Defeat:
	.string "Done in by two kids?!\n"
	.string "This isn’t right!$"

Galactic_Grunt_Veilstone_City_2Defeat:
	.string "I should have kept my head down and\n"
	.string "just watched our warehouse...$"

Gentleman_JeremyDefeat:
	.string "Your handling of Pokémon is\n"
	.string "impeccable.$"

Gentleman_JeremyPostBattle:
	.string "Hahaha! I was invited by the master of\n"
	.string "the Pokémon Mansion.\p"
	.string "He’s promised to show me through\n"
	.string "his prized garden of Pokémon.$"

Gentleman_JeremyIntro:
	.string "If it pleases you, may I challenge you\n"
	.string "to a battle?$"

Gentleman_JeremyRematch:
	.string "If it pleases, would you care for a\n"
	.string "rematch with me?$"

Gentleman_LeonardoDefeat:
	.string "Ack! I lost...\n"
	.string "Check, please!\n"
	.string "$"

Guitarist_ArturoDefeat:
	.string "You beat me, but...\n"
	.string "I feel totally amped to jam harder!$"

Guitarist_Arturo_UnusedDefeat:
	.string "You beat me, man, but...\n"
	.string "I feel totally amped to jam harder!$"

Guitarist_Arturo_UnusedPostBattle:
	.string "Rock is about your spirit!\n"
	.string "Battling is about spirit, too!\p"
	.string "That’s why battles rock! Rawk!$"

Guitarist_Arturo_UnusedIntro:
	.string "Your spirit’s vibes, man... I can feel\n"
	.string "that you’ve got rock in your soul!$"

Guitarist_JerryDefeat:
	.string "We couldn’t win...\n"
	.string "No encores for us...$"

Guitarist_JerryPostBattle:
	.string "The Trainer’s desire to win!\p"
	.string "If you don’t lose that, there’s\n"
	.string "no limit on what you can become!$"

Guitarist_JerryIntro:
	.string "I want to win!\n"
	.string "That desire I pour into my guitar!\p"
	.string "I want to win!\n"
	.string "That passion compels my Pokémon!$"

Guitarist_LonnieDefeat:
	.string "My skills seem to have let me down.\n"
	.string "I must have been out of tune!$"

Guitarist_LonniePostBattle:
	.string "The way you battle, I can feel the\n"
	.string "very heart of rock and roll.\p"
	.string "Tell me, are you maybe a fan of\n"
	.string "rocking out?$"

Guitarist_LonnieIntro:
	.string "Whether you’re a Trainer or a\n"
	.string "Guitarist, it takes dedication to\p"
	.string "improve your mad skills!$"

Guitarist_PrestonDefeat:
	.string "Spark...$"

Guitarist_PrestonPostBattle:
	.string "We were lacking energy...\p"
	.string "No, we lacked more than that. We\n"
	.string "didn’t want the win enough.$"

Guitarist_PrestonIntro:
	.string "Spark!\p"
	.string "This is what our Gym Leader did\n"
	.string "to the Gym out of boredom!$"

Guitarist_TonyDefeat:
	.string "Can you hear it?\n"
	.string "That’s my guitar weeping...$"

Guitarist_TonyPostBattle:
	.string "I’m too torn up to sing anymore...\n"
	.string "I am so cool that way...$"

Guitarist_TonyIntro:
	.string "Let it rock!\n"
	.string "It’s the rhythm of battle!$"

Guitarist_TonyRematch:
	.string "Rock ’n’ roll!\n"
	.string "We’ll beat it out again!\p"
	.string "Our rhythm of battle!$"

Hall_Matron_Argenta_DummyDefeat:
	.string "Oh, dear... The trouble with fun is that\n"
	.string "it is over so quickly.$"

Hiker_AlexanderDefeat:
	.string "Ohh... Yo...\n"
	.string "Yodelay...$"

Hiker_AlexanderPostBattle:
	.string "Here’s good advice from the Echo Man!\p"
	.string "If you’re at a loss as to where you\n"
	.string "should be going, check the Town Map!$"

Hiker_AlexanderIntro:
	.string "They call me the Echo Man!\n"
	.string "Battle with me! Yahoo!$"

Hiker_AlexanderRematch:
	.string "Oh, hi there! Remember us?\n"
	.string "I’m the Echo Man!\p"
	.string "Let’s have another battle!\n"
	.string "Yahoo!$"

Hiker_DamonDefeat:
	.string "Whew... Crazy, delicious sugar!\n"
	.string "I think I’ve calmed down now...$"

Hiker_DamonPostBattle:
	.string "If it’s called a mountain, you can\n"
	.string "be sure I’ll be climbing it.\p"
	.string "Even if it’s a mountain of food, I’ll\n"
	.string "still be stickin’ my flag on top!$"

Hiker_DamonIntro:
	.string "Every good Hiker gets a boost of\n"
	.string "energy when surrounded by boulders!\p"
	.string "Wrooooar! Coming at you!\n"
	.string "Let me blow off some steam!$"

Hiker_DanielDefeat:
	.string "Oh, yeah!\n"
	.string "A refreshing battle that was!$"

Hiker_DanielPostBattle:
	.string "You can find the same kinds of\n"
	.string "Pokémon in all sorts of places.\p"
	.string "There’s no law saying a Hiker can’t\n"
	.string "go searching off in the mountains!$"

Hiker_DanielIntro:
	.string "There’s no mountain here, but I’m\n"
	.string "dressed to hike! Gahaha! Here goes!$"

Hiker_DanielRematch:
	.string "If you meet someone in the mountains,\n"
	.string "they’re no longer strangers.\p"
	.string "Meet them twice, and they’re your\n"
	.string "friend!$"

Hiker_JonathanRematch:
	.string "I, uh, chowed down my packed lunch\n"
	.string "before we started climbing.\p"
	.string "If I beat you this time, share some\n"
	.string "food with me!$"

Hiker_JustinDefeat:
	.string "Whoops!\n"
	.string "Taken down easily!$"

Hiker_JustinPostBattle:
	.string "We need to rest up in Oreburgh City\n"
	.string "before heading to Mt. Coronet again.$"

Hiker_JustinIntro:
	.string "I just got through Mt. Coronet, but\n"
	.string "I’ve still got energy to burn!$"

Hiker_JustinRematch:
	.string "I just got through Mt. Coronet,\n"
	.string "and who do I see?\p"
	.string "A Trainer who we’ve battled before!$"

Hiker_KevinDefeat:
	.string "Wahahaha! There’s nothing that\n"
	.string "I can do but laugh!$"

Hiker_KevinPostBattle:
	.string "Wahahahaha!\n"
	.string "...Go ahead, laugh at me--the loser!$"

Hiker_KevinIntro:
	.string "Wahaha!\n"
	.string "Laughter brings good fortune!$"

Hiker_KevinRematch:
	.string "Wahaha!\p"
	.string "Laughter brings good fortune!\n"
	.string "Forgetting your gloves brings a cold!$"

Hiker_LorenzoDefeat:
	.string "Bleff! Hurk!\n"
	.string "I think...I’m getting better...$"

Hiker_LorenzoPostBattle:
	.string "I hear there’s a Pokémon that has\n"
	.string "mushrooms growing on its back.\p"
	.string "Not around here, somewhere far away.\n"
	.string "I wonder if they taste any good?$"

Hiker_LorenzoIntro:
	.string "Wandering around, I got hungry, so\n"
	.string "I ate some wild mushrooms...\p"
	.string "They gave me gas, and now I can’t\n"
	.string "stop burping! Bluurrf!$"

Hiker_LouisDefeat:
	.string "You loom before me as a giant presence!$"

Hiker_LouisPostBattle:
	.string "Mt. Coronet has long been known as\n"
	.string "an ancient and mysterious mountain.$"

Hiker_LouisIntro:
	.string "See how Mt. Coronet towers above us.\n"
	.string "I want to be big like that one day!$"

Hiker_LouisRematch:
	.string "Hmm?! \n"
	.string "You loom before me again?!\p"
	.string "You’re like Mt. Coronet that way!$"

Hiker_MauriceDefeat:
	.string "Yahoo!$"

Hiker_MauricePostBattle:
	.string "Actually, when you’re up in the\n"
	.string "mountains, a simple hi’d do if\p"
	.string "you walk past someone.\p"
	.string "Oh, and this isn’t the mountains.$"

Hiker_MauriceIntro:
	.string "When you’re up in the mountains,\n"
	.string "a battle’d do for a proper greeting!$"

Hiker_NicholasDefeat:
	.string "Having lost his way, the Trainer lost\n"
	.string "the battle too...$"

Hiker_NicholasPostBattle:
	.string "From being lost in the mountains so\n"
	.string "long, I became a Hiker...$"

Hiker_NicholasIntro:
	.string "I’ve lost my way...\n"
	.string "Here of all places...$"

Hiker_NicholasRematch:
	.string "I’ve lost my way again...\p"
	.string "Yes, it’s me again with no sense of\n"
	.string "direction...$"

Hiker_ReginaldDefeat:
	.string "I strayed from the battle plan!$"

Hiker_ReginaldPostBattle:
	.string "Me? No, I’m not lost.\n"
	.string "I live here!$"

Hiker_ReginaldIntro:
	.string "Look! A Trainer lost in Wayward Cave!$"

Hiker_RobertDefeat:
	.string "Oh my, a big man like me got schooled\n"
	.string "by a little kid like you!$"

Hiker_RobertPostBattle:
	.string "Wow, you’re sure impressive!\p"
	.string "I guess it makes no difference if\n"
	.string "you’re young or old in battles.$"

Hiker_RobertIntro:
	.string "Gahahaha! You’re just a little kid!\p"
	.string "How’re you supposed to beat a big\n"
	.string "man like me?$"

Hiker_RobertRematch:
	.string "Hey, you, tough little kid!\n"
	.string "Throw us a rematch, will you?$"

Hiker_TheodoreDefeat:
	.string "Your power startles me!$"

Hiker_TheodorePostBattle:
	.string "We Hikers are bighearted guys!\n"
	.string "Losing doesn’t bother us!$"

Hiker_TheodoreIntro:
	.string "Whoa! You startled me!\n"
	.string "Well, we may as well battle!$"

Hiker_TheodoreRematch:
	.string "Whoa! You startled me!\n"
	.string "We may as well have a rematch!$"

Idol_GraceDefeat:
	.string "Ouch! Are you one of those loyal\n"
	.string "fans? You sure are rowdy!$"

Idol_Grace_UnusedDefeat:
	.string "Ouch! Are you one of those loyal\n"
	.string "fans? You sure are rowdy!$"

Idol_Grace_UnusedPostBattle:
	.string "Well, that’s me and my Pokémon!\n"
	.string "Thank you for being such a fan!\p"
	.string "Just so you know, our latest single\n"
	.string "is “Jigglin’ Pokémon Wub”!$"

Idol_Grace_UnusedIntro:
	.string "I’ll let you join my fan club if you can\n"
	.string "beat me!$"

Jogger_CraigDefeat:
	.string "My pace is completely off...$"

Jogger_CraigPostBattle:
	.string "Sticking to one’s own goal is more\n"
	.string "important than it seems.\p"
	.string "If you match your goal with someone\n"
	.string "else, you’ll lose your identity.$"

Jogger_CraigIntro:
	.string "If I battle now, won’t it mess up my\n"
	.string "usual pace?$"

Jogger_CraigRematch:
	.string "If I battle now, won’t it mess up my\n"
	.string "usual pace?$"

Jogger_RaulDefeat:
	.string "It’s a goal of sorts, I’d say!$"

Jogger_RaulPostBattle:
	.string "If I get out of rhythm, I can’t get my\n"
	.string "act together.$"

Jogger_RaulIntro:
	.string "Jogging is about rhythm.\n"
	.string "Battling is about rhythm, too!$"

Jogger_RaulRematch:
	.string "Jogging is about rhythm.\n"
	.string "Battling is about rhythm, too.\p"
	.string "Our rematch is also about rhythm!$"

Jogger_RichardDefeat:
	.string "Oops!\n"
	.string "You threw off my running rhythm.$"

Jogger_RichardPostBattle:
	.string "Nothing beats being fit and healthy!\p"
	.string "Come on, won’t you run with me?\n"
	.string "To a better tomorrow!$"

Jogger_RichardIntro:
	.string "I jog every morning to keep my\n"
	.string "Pokémon fit.$"

Jogger_RichardRematch:
	.string "When I go on my jogs, I pass by lots\n"
	.string "of people.\p"
	.string "I have trouble remembering faces,\n"
	.string "but we did meet before, right?$"

Jogger_ScottDefeat:
	.string "Huff-huff, we-huff lose-huff.$"

Jogger_ScottPostBattle:
	.string "Bye-huff now-huff.\n"
	.string "Huff-huff, huff-huff.$"

Jogger_ScottIntro:
	.string "Hufff-huff, huff-huff.\n"
	.string "Want-huff a battle-huff?$"

Jogger_ScottRematch:
	.string "Huff-huff, huff-huff.\n"
	.string "We-huff meet-huff again-huff?$"

Jogger_WyattDefeat:
	.string "...Oh, serious woe.\n"
	.string "I wasn’t prepared emotionally for this.$"

Jogger_WyattPostBattle:
	.string "I wish I could just run from all this...\n"
	.string "Just joking.$"

Jogger_WyattIntro:
	.string "I’m warmed up and limber.\n"
	.string "I’m OK to battle!$"

Jogger_WyattRematch:
	.string "I’ve been training so I can have\n"
	.string "a rematch with you.\p"
	.string "I’m OK to battle!$"

Lady_CelesteDefeat:
	.string "Oh, dear me!$"

Lady_KylieDefeat:
	.string "Ohh... How could I lose at dear\n"
	.string "Papa’s restaurant?$"

Lady_MelissaDefeat:
	.string "Oh, how very impressive of you.$"

Lady_MelissaPostBattle:
	.string "You... You must have one fantastic\n"
	.string "teacher to be so good.$"

Lady_MelissaIntro:
	.string "I’d like to begin now.\n"
	.string "Are you quite prepared?$"

Lady_MelissaRematch:
	.string "Oh, I’m delighted to see you again.\n"
	.string "Are you prepared?$"

Lass_BlytheDefeat:
	.string "I was with my daddy, too...$"

Lass_BrianaDefeat:
	.string "Oh, you!$"

Lass_BrianaPostBattle:
	.string "You can’t avoid bug Pokémon ever in\n"
	.string "the forest.\p"
	.string "I didn’t have any Antidotes with me,\n"
	.string "either. It was the worst!$"

Lass_BrianaIntro:
	.string "We’re just out on a power walk!$"

Lass_CarolineDefeat:
	.string "Giggle...\n"
	.string "The clock will turn now.$"

Lass_CarolinePostBattle:
	.string "OK, the next Trainer is at the end,\n"
	.string "past two boulders.$"

Lass_CarolineIntro:
	.string "A forest inside a Gym...\n"
	.string "Shocking, isn’t it?$"

Lass_Carrie_Unused_1Defeat:
	.string "Huh? It’s over already?!\n"
	.string "I thought I’d win for sure!$"

Lass_Carrie_Unused_1PostBattle:
	.string "You’re too tough!\n"
	.string "I won’t battle you again!\p"
	.string "Just joking! I’ll challenge you again\n"
	.string "when I level up my Pokémon.$"

Lass_Carrie_Unused_1Intro:
	.string "Hi, what kinds of Pokémon do you\n"
	.string "have with you?\p"
	.string "I’ll show you my Pokémon while we\n"
	.string "have a battle.$"

Lass_Carrie_Unused_2Defeat:
	.string "Huh? It’s over already?!\n"
	.string "I thought I’d win for sure!$"

Lass_Carrie_Unused_2PostBattle:
	.string "You’re too tough!\n"
	.string "I won’t battle you again!\p"
	.string "Just joking! I’ll challenge you again\n"
	.string "when I level up my Pokémon.$"

Lass_Carrie_Unused_2Intro:
	.string "Hi, what kinds of Pokémon do you\n"
	.string "have with you?\p"
	.string "I’ll show you my Pokémon while we\n"
	.string "have a battle.$"

Lass_Carrie_Unused_3Defeat:
	.string "Huh? It’s over?!\n"
	.string "I thought I’d win!$"

Lass_Carrie_Unused_3PostBattle:
	.string "You’re too tough!\n"
	.string "I won’t battle you again!\p"
	.string "Just joking! I’ll challenge you again\n"
	.string "when I level up my Pokémon.$"

Lass_Carrie_Unused_3Intro:
	.string "Hi, what kinds of Pokémon do you\n"
	.string "have with you?\p"
	.string "I’ll show you my Pokémon while we\n"
	.string "have a battle.$"

Lass_CassidyDefeat:
	.string "Sniffle... W-who’s crying now?$"

Lass_CassidyPostBattle:
	.string "Speaking of crying, I’m positive I\n"
	.string "heard crying from deeper in the cave.$"

Lass_CassidyIntro:
	.string "Hush now, lost little Pokémon, don’t\n"
	.string "you cry.\p"
	.string "I’m here to take care of you!$"

Lass_KaitlinRematch:
	.string "I found a familiar-looking Trainer!$"

Lass_MadelineRematch:
	.string "I got a nifty-keen Gym Badge from\n"
	.string "the Gym Leader in Oreburgh City!\p"
	.string "...Did I show you already?$"

Lass_MollyDefeat:
	.string "Uh, whoopsie!\n"
	.string "That didn’t end well!$"

Lass_MollyPostBattle:
	.string "Since you’re here, you might as well\n"
	.string "take on every Trainer.$"

Lass_MollyIntro:
	.string "Boo! Did I scare you?\n"
	.string "This battle will!$"

Lass_NatalieRematch:
	.string "Oh, hi!\n"
	.string "I remember you, Trainer!\p"
	.string "A battle, please!$"

Lass_SamanthaRematch:
	.string "Oh, thank you for that last battle.\p"
	.string "May I please trouble you for\n"
	.string "another one?$"

Lass_SarahRematch:
	.string "Hi, pretty-tough Trainer!\n"
	.string "Will you give me a rematch?$"

Leader_ByronDefeat:
	.string "Hmm!\n"
	.string "My sturdy Pokémon--defeated!$"

Leader_CandiceDefeat:
	.string "You’re mighty!\n"
	.string "You’re worthy of lots of respect.$"

Leader_FantinaDefeat:
	.string "You are so fantastically strong.\n"
	.string "I know why I have lost.$"

Leader_GardeniaDefeat:
	.string "Amazing!\n"
	.string "You’re very good, aren’t you?$"

Leader_MayleneDefeat:
	.string "I’m forced to admit defeat again...\n"
	.string "You are much too strong.$"

Leader_RoarkDefeat:
	.string "W-what? That can’t be!\n"
	.string "My buffed-up Pokémon!$"

Leader_VolknerDefeat:
	.string "I even felt thrilled during our\n"
	.string "match.\p"
	.string "That was a very good battle.$"

Leader_Volkner_Fight_AreaDefeat:
	.string "Your toughness is something else.\n"
	.string "We were completely overwhelmed!$"

Leader_WakeDefeat:
	.string "That puts a grin on my face!\n"
	.string "Guhahaha! That was a blast!$"

Maid_BelindaDefeat:
	.string "You’re so strong!$"

Maid_ClareDefeat:
	.string "You’re so strong!!!!!$"

Maid_ElenaDefeat:
	.string "You’re so strong!!!!$"

Maid_EmilyDefeat:
	.string "You’re so strong!!!$"

Maid_SophieDefeat:
	.string "You’re so strong!!$"

Marley_BattlegroundDefeat:
	.string "...Awww.$"

Mira_BattlegroundDefeat:
	.string "Mira wonders if she can get very far in\n"
	.string "the Battle Tower.$"

Ninja_Boy_BrennanDefeat:
	.string "I concede defeat...$"

Ninja_Boy_BrennanPostBattle:
	.string "While I hid in the tall grass, I\n"
	.string "sensed Pokémon all around me!\p"
	.string "Furtive sounds of movement...\n"
	.string "Stifled cries... I heard them!$"

Ninja_Boy_BrennanIntro:
	.string "I am one of the Ninja Trio!\n"
	.string "Being discovered means I must battle!$"

Ninja_Boy_BrennanRematch:
	.string "You don’t remember me?\n"
	.string "I am one of the Ninja Trio!\p"
	.string "Being discovered means I must battle!$"

Ninja_Boy_BruceDefeat:
	.string "I concede defeat...$"

Ninja_Boy_BrucePostBattle:
	.string "A Pokémon Trainer’s good at finding\n"
	.string "stuff, I guess.$"

Ninja_Boy_BruceIntro:
	.string "I am one of the Ninja Trio!\n"
	.string "Being discovered means I must battle!\p"
	.string "But how did you discover me?\n"
	.string "Don’t tell me you’re a ninja, too!$"

Ninja_Boy_BruceRematch:
	.string "You should join us so we can form\n"
	.string "the Ninja Quartet!\p"
	.string "Anyway, let’s battle!$"

Ninja_Boy_DavidoDefeat:
	.string "Hmm...\n"
	.string "My ninja techniques failed to work...$"

Ninja_Boy_DavidoPostBattle:
	.string "There’s a ninja Gym Leader somewhere\n"
	.string "far away.\p"
	.string "I should become a devotee of theirs.$"

Ninja_Boy_DavidoIntro:
	.string "A ninja can use all kinds of skills.\n"
	.string "Like this and like that!$"

Ninja_Boy_DavidoRematch:
	.string "What’s with you?\n"
	.string "You’re not a ninja yet?$"

Ninja_Boy_EthanDefeat:
	.string "I’m not much of a ninja either way...$"

Ninja_Boy_EthanPostBattle:
	.string "I wonder why everyone stops being\n"
	.string "a ninja when they grow up?$"

Ninja_Boy_EthanIntro:
	.string "There are several clans of ninjas.\n"
	.string "Are you from the Iga clan? Or Kouga?$"

Ninja_Boy_EthanRematch:
	.string "I forged my willpower in the snow!\n"
	.string "Witness my snowy might!$"

Ninja_Boy_FabianDefeat:
	.string "I concede defeat...$"

Ninja_Boy_FabianPostBattle:
	.string "My cover is blown, so what should\n"
	.string "I do?\p"
	.string "Maybe I’ll go catch some Contests in\n"
	.string "Hearthome City. Maybe I’ll do that.$"

Ninja_Boy_FabianIntro:
	.string "I am one of the Ninja Trio!\n"
	.string "Being discovered means I must battle!$"

Ninja_Boy_FabianRematch:
	.string "Do you remember me?\n"
	.string "I am one of the Ninja Trio!\p"
	.string "Being discovered means I must battle!$"

Ninja_Boy_JoelDefeat:
	.string "Oh, what’s that?\n"
	.string "You’re supposed to be fumbling more.$"

Ninja_Boy_JoelPostBattle:
	.string "I wanted a better reaction from you.\n"
	.string "Now I feel silly for hiding!$"

Ninja_Boy_JoelIntro:
	.string "I just startled you!\p"
	.string "While you’re still struggling to\n"
	.string "recover, I’ll already be the winner!$"

Ninja_Boy_JoelRematch:
	.string "You just saw me, and I bet you\n"
	.string "thought, “Long time no see.”\p"
	.string "While you’re still thinking that, I’ll\n"
	.string "already be the winner!$"

Ninja_Boy_MatthewDefeat:
	.string "You also saw through my weak\n"
	.string "spots...$"

Ninja_Boy_MatthewPostBattle:
	.string "I’ll play with my Pokémon--even in a\n"
	.string "blizzard!$"

Ninja_Boy_MatthewIntro:
	.string "Poof!\p"
	.string "You’ve got a good eye spotting me!$"

Ninja_Boy_MatthewRematch:
	.string "Poof!\p"
	.string "You saw through my camouflage again!$"

Ninja_Boy_NathanDefeat:
	.string "I didn’t expect to lose...$"

Ninja_Boy_NathanPostBattle:
	.string "While hiding, I think about what Pokémon\n"
	.string "must be thinking inside their Poké Balls.$"

Ninja_Boy_NathanIntro:
	.string "We ninjas appear where you least\n"
	.string "expect us!$"

Ninja_Boy_NathanRematch:
	.string "Wah! Another chance encounter with\n"
	.string "a foe who defeated me before!$"

Ninja_Boy_NickDefeat:
	.string "I did a lot to conceal myself, too...$"

Ninja_Boy_NickPostBattle:
	.string "I’ll wait here for a weaker-looking\n"
	.string "Trainer and then ambush them!$"

Ninja_Boy_NickIntro:
	.string "Speed is a ninja’s best weapon!\n"
	.string "Can you keep up?$"

Ninja_Boy_NickRematch:
	.string "I became even faster!\n"
	.string "How can you hope to keep up?$"

Ninja_Boy_ZachDefeat:
	.string "What’s with you?\n"
	.string "You didn’t give me any openings!$"

Ninja_Boy_ZachPostBattle:
	.string "Sowing confusion among the foe is\n"
	.string "one way a ninja battles.\p"
	.string "A Pokémon can’t overcome its\n"
	.string "confusion unless it switches out.$"

Ninja_Boy_ZachIntro:
	.string "ZUBAT! Doesn’t that sound like a\n"
	.string "ninja bursting from cover?$"

Ninja_Boy_ZachRematch:
	.string "The shinobi live by speed!\n"
	.string "I’ll get in my attacks before you!$"

Parasol_Lady_AlexaDefeat:
	.string "Like rain, my tears fall from losing...\n"
	.string "They call me Rain Woman...$"

Parasol_Lady_AlexaPostBattle:
	.string "I want to show off my pretty parasol,\n"
	.string "but it will get dirty in the rain.\p"
	.string "Oh, such a big dilemma!$"

Parasol_Lady_AlexaIntro:
	.string "There are Pokémon that grow stronger\n"
	.string "when it’s raining.$"

Parasol_Lady_AlexaRematch:
	.string "On rainy days, I get more energetic!$"

Parasol_Lady_SabrinaDefeat:
	.string "It’s not very easy trying to battle\n"
	.string "while holding an umbrella.$"

Parasol_Lady_SabrinaPostBattle:
	.string "If it rained every day, I could have\n"
	.string "my umbrella open all the time.$"

Parasol_Lady_SabrinaIntro:
	.string "When it rains, I get more tense!$"

Parasol_Lady_SabrinaRematch:
	.string "It’s not because it’s raining.\n"
	.string "I just love umbrellas!$"

Pi_CarlosDefeat:
	.string "I guessed wrong too often.$"

Pi_CarlosPostBattle:
	.string "I flipped a coin when I was ten.\n"
	.string "I decided to live in Sinnoh then.$"

Pi_CarlosIntro:
	.string "When I toss this coin, you call it.\n"
	.string "Heads, we battle.\p"
	.string "Tails, we battle!\p"
	.string "Now, how will this play out, my friend?$"

Pi_CarlosRematch:
	.string "I wasn’t lucky the other day.\n"
	.string "Things will be different today.$"

Pi_KendrickDefeat:
	.string "My luck’s run out...$"

Picnicker_AnaDefeat:
	.string "That wasn’t any fun for me!$"

Picnicker_AnaPostBattle:
	.string "Why have a picnic here? I don’t know.\n"
	.string "There’s no deep meaning to it.$"

Picnicker_AnaIntro:
	.string "What every good picnic needs is a\n"
	.string "cute setting, good food, and a fun\p"
	.string "battle!$"

Picnicker_CheyenneDefeat:
	.string "Your toughness...\n"
	.string "It’s something new to me.$"

Picnicker_CheyennePostBattle:
	.string "I’ve learned that Pokémon are fun\n"
	.string "’cause everyone plays with ’em!$"

Picnicker_CheyenneIntro:
	.string "I’m not afraid of picnicking anywhere,\n"
	.string "so I’ve learned all sorts of things.$"

Picnicker_KarinaDefeat:
	.string "Oh, boo!\n"
	.string "How insulting!$"

Picnicker_KarinaPostBattle:
	.string "Listen very closely...\n"
	.string "Can you hear the cries of Pokémon?$"

Picnicker_KarinaIntro:
	.string "Oh, I don’t know.\n"
	.string "Should I play a little?$"

Picnicker_KarinaRematch:
	.string "Oh, I don’t know.\n"
	.string "Should I play a little again?$"

Picnicker_LaurenDefeat:
	.string "Oh...\n"
	.string "We lost...$"

Picnicker_LaurenPostBattle:
	.string "I think we’ll visit the TV station in\n"
	.string "Jubilife City next.\p"
	.string "Or maybe we should go to the Global\n"
	.string "Terminal?$"

Picnicker_LaurenIntro:
	.string "Go do it, my Pokémon!\n"
	.string "I’ll work hard, too!$"

Picnicker_LaurenRematch:
	.string "Umm, aren’t you that Trainer who beat\n"
	.string "us before?\p"
	.string "We feel good today, so we’ll be happy\n"
	.string "to face you again!$"

Picnicker_SienaDefeat:
	.string "I’m shocked!\n"
	.string "How did I lose?$"

Picnicker_SienaPostBattle:
	.string "I know all sorts of things about\n"
	.string "Pokémon!\p"
	.string "Let’s see... There are males and\n"
	.string "females, and some aren’t either!$"

Picnicker_SienaIntro:
	.string "What kinds of Pokémon live around\n"
	.string "here, I wonder?$"

Picnicker_SienaRematch:
	.string "Oh, hi! We meet again!\n"
	.string "Have you seen any rare Pokémon?$"

Picnicker_SummerDefeat:
	.string "We’re not going to win if we play\n"
	.string "around like that...$"

Picnicker_SummerPostBattle:
	.string "I’m going home to play with my\n"
	.string "Pokémon!$"

Picnicker_SummerIntro:
	.string "May we have a battle, please?\p"
	.string "It will be something to lighten up this\n"
	.string "boring picnic with.$"

Picnicker_ToriDefeat:
	.string "OK, so we’re both Trainers.\n"
	.string "That’s a start, right?$"

Picnicker_ToriPostBattle:
	.string "I just wanted to have a picnic under\n"
	.string "the Cycling Road.\p"
	.string "I didn’t think I would get lost\n"
	.string "in a place like this...$"

Picnicker_ToriIntro:
	.string "Where am I? Am I lost? Who are you?\n"
	.string "Are you a Pokémon Trainer?$"

Poke_Kid_ArielDefeat:
	.string "Pi-Pikachu!$"

Poke_Kid_Ariel_UnusedDefeat:
	.string "Pi-Pikachu!$"

Poke_Kid_Ariel_UnusedPostBattle:
	.string "I need to find a way to get more into\n"
	.string "the character of a Pokémon...$"

Poke_Kid_Ariel_UnusedIntro:
	.string "Po-Po-Pokémon!\n"
	.string "Do you think I’m a real Pokémon?$"

Poke_Kid_DanielleDefeat:
	.string "I’m so angry...$"

Poke_Kid_DaniellePostBattle:
	.string "I don’t want to be a Trainer.\n"
	.string "I want to be a Pokémon!$"

Poke_Kid_DanielleIntro:
	.string "Hi, hi!\n"
	.string "I’m a Pokémon!$"

Poke_Kid_DanielleRematch:
	.string "Hi, hi!\n"
	.string "I’m a Pokémon!\p"
	.string "...You knew that, didn’t you?$"

Poke_Kid_JanetDefeat:
	.string "Pikachu...$"

Poke_Kid_JanetPostBattle:
	.string "Pika...\p"
	.string "I’ll need a lot more practice to\n"
	.string "become a real PIKACHU...$"

Poke_Kid_JanetIntro:
	.string "Bika bikabika!\n"
	.string "Pigachu!$"

Poke_Kid_MeghanDefeat:
	.string "I was being serious!\n"
	.string "Don’t laugh at me! I mean it!$"

Poke_Kid_MeghanPostBattle:
	.string "I dress this way so I can get a feel for\n"
	.string "how electric Pokémon think.\p"
	.string "Would you like to try, too?$"

Poke_Kid_MeghanIntro:
	.string "Look at the way I’m dressed.\n"
	.string "Can’t you see that I’m hardcore?$"

Pokefan_LeonardDefeat:
	.string "Hunh?!\n"
	.string "What was I just doing?!$"

Pokefan_LeonardPostBattle:
	.string "The desire to do battle lingers on...\p"
	.string "Do such spirits of Pokémon still roam\n"
	.string "within these walls?$"

Pokefan_LeonardIntro:
	.string "I can’t explain it...\n"
	.string "Being here compels me to battle!$"

Pokefan_MeredithDefeat:
	.string "No one’s hurt?$"

Pokefan_RebekahDefeat:
	.string "My sorrow has deepened...$"

Pokefan_RebekahPostBattle:
	.string "I won’t ever forget the Pokémon that\n"
	.string "I’ve spent time with, however fleeting.$"

Pokefan_RebekahIntro:
	.string "I need to shake off my sorrow...\n"
	.string "Please, battle with me!$"

Policeman_AlexDefeat:
	.string "Now, just hold on. I didn’t say that\n"
	.string "you were shady looking!$"

Policeman_AlexPostBattle:
	.string "Don’t go hanging out with any\n"
	.string "shady-looking characters! You hear?$"

Policeman_AlexIntro:
	.string "I’m keeping my eyes open for crime.\n"
	.string "Anyone arousing suspicion here?$"

Policeman_AlexRematch:
	.string "Any shady-looking characters around?\n"
	.string "I’m always on the lookout for punks.\p"
	.string "Expecting some shady dude to actually\n"
	.string "pop up... Does that make me weird?$"

Policeman_BobbyDefeat:
	.string "You’ve got tough partners with you.\n"
	.string "Carry on, citizen. Carry on.$"

Policeman_BobbyPostBattle:
	.string "Out so late? Does your mother\n"
	.string "know you’re out so late?$"

Policeman_BobbyIntro:
	.string "Hold it right there, citizen!\n"
	.string "Walking around at night is unsafe!$"

Policeman_BobbyRematch:
	.string "Didn’t I already give you a warning?\n"
	.string "It’s unsafe to walk around at night!$"

Policeman_CalebDefeat:
	.string "Big trouble! Officer in need\n"
	.string "of assistance!$"

Policeman_CalebPostBattle:
	.string "Your toughness is too much!\n"
	.string "I’m in serious trouble!$"

Policeman_CalebIntro:
	.string "Whether there are problems or not, or\n"
	.string "if crimes have been committed or not,\p"
	.string "I still go out on patrol.$"

Policeman_CalebRematch:
	.string "Let me ask you a question!\n"
	.string "Are you tough enough to take me?$"

Policeman_DannyDefeat:
	.string "Beaten by sneakiness again...$"

Policeman_DannyPostBattle:
	.string "I mistook your toughness as shadiness!\n"
	.string "It’s an honest mistake!$"

Policeman_DannyIntro:
	.string "Your whole atmosphere is shady.\n"
	.string "Cooperate in this investigation!$"

Policeman_DannyRematch:
	.string "Whoa! Hold it right there!\n"
	.string "I’ve spotted a sneaky Trainer!$"

Policeman_DylanDefeat:
	.string "I need to explain, all right?\n"
	.string "It was too dark and hard to see.$"

Policeman_DylanPostBattle:
	.string "Oops, I’d better get back to my\n"
	.string "beat before the boss radios me...$"

Policeman_DylanIntro:
	.string "Let’s enjoy a fierce battle in the\n"
	.string "chilly night winds! Brrrr! Refreshing!$"

Policeman_DylanRematch:
	.string "Still training this late?\p"
	.string "That makes you either a bad kid or\n"
	.string "a good Trainer. Which one is it?$"

Policeman_ThomasDefeat:
	.string "I happen to be rather jumpy, so\n"
	.string "everyone looks suspicious to me.$"

Policeman_ThomasPostBattle:
	.string "I’m easy to scare, and yet here I am\n"
	.string "on patrol. Funny how things go.$"

Policeman_ThomasIntro:
	.string "Who’s there?!\n"
	.string "What do you think you’re doing?!$"

Policeman_ThomasRematch:
	.string "I’ll repeat myself! Who’s there?!\n"
	.string "What do you think you’re doing?!$"

Psychic_AbigailDefeat:
	.string "My plan to spook you didn’t go over\n"
	.string "at all.$"

Psychic_AbigailPostBattle:
	.string "You might be tough, but let down\n"
	.string "your guard at your own risk!$"

Psychic_AbigailIntro:
	.string "There!\n"
	.string "Behind you!$"

Psychic_AbigailRematch:
	.string "Wah! That thing curled around your\n"
	.string "neck!\p"
	.string "...Nice scarf, kid!$"

Psychic_BrittneyDefeat:
	.string "The power that slumbers within you...\n"
	.string "It is rather marvelous...$"

Psychic_BrittneyPostBattle:
	.string "A place where nothing else exists...\p"
	.string "A place such as that is better suited\n"
	.string "to awaken the power within.$"

Psychic_BrittneyIntro:
	.string "There is nothing here... And yet\n"
	.string "there is a power lurking...\p"
	.string "Were you drawn by it, as well?$"

Psychic_BrittneyRematch:
	.string "See?\n"
	.string "You’ve come back again.\p"
	.string "There must be something that draws\n"
	.string "you here...$"

Psychic_BryceDefeat:
	.string "So be it! I will now divulge what\n"
	.string "I know of your future... Hmm!$"

Psychic_BrycePostBattle:
	.string "I see it now!\p"
	.string "You will battle the Elite Four of the\n"
	.string "Pokémon League!$"

Psychic_BryceIntro:
	.string "I am a Psychic!\n"
	.string "I can see your future!$"

Psychic_ChelseyDefeat:
	.string "That’s what I get for making idle\n"
	.string "claims...$"

Psychic_ChelseyPostBattle:
	.string "Psychic power is a mystery that\n"
	.string "defies explanation.\p"
	.string "But if everything could be explained,\n"
	.string "it would be a boring world.$"

Psychic_ChelseyIntro:
	.string "I’ll use my mystifying psychic power\n"
	.string "to pulverize you!$"

Psychic_CorbinDefeat:
	.string "What I saw in the future turned out\n"
	.string "to be true...$"

Psychic_CorbinPostBattle:
	.string "I lost, but my vision of the future\n"
	.string "came true...$"

Psychic_CorbinIntro:
	.string "You’re going to win!\n"
	.string "That’s the future I saw!$"

Psychic_CorbinRematch:
	.string "You’re going to win again!\n"
	.string "That’s the future I saw!$"

Psychic_DaisyDefeat:
	.string "Right after this, I have to pay\n"
	.string "out your prize money...$"

Psychic_DaisyPostBattle:
	.string "What will you do after this?\p"
	.string "Why don’t you decide for yourself?\n"
	.string "It would be much more fun that way!$"

Psychic_DaisyIntro:
	.string "Right after this, you will send out your\n"
	.string "Pokémon to do battle!$"

Psychic_DaisyRematch:
	.string "Right after this, you will hurl a Poké\n"
	.string "Ball in an astonishingly cool manner!$"

Psychic_DeandreDefeat:
	.string "But... I thought I could win!$"

Psychic_DeandrePostBattle:
	.string "Psychic power...\p"
	.string "I know it isn’t easy to believe in\n"
	.string "something that you can’t see.\p"
	.string "But love, friendship...\n"
	.string "You can’t see those, either.$"

Psychic_DeandreIntro:
	.string "A battle is a clash of willpower!\p"
	.string "The one who wants the win the most\n"
	.string "will emerge the victor!$"

Psychic_DesireeDefeat:
	.string "Did I get to show you anything...?\n"
	.string "Anything at all?$"

Psychic_DesireePostBattle:
	.string "What can psychic power be used for?\p"
	.string "Well, one mustn’t use it for committing\n"
	.string "crimes.\p"
	.string "But, I don’t use it for doing good,\n"
	.string "either.\p"
	.string "Using psychic power leaves me too worn\n"
	.string "out!$"

Psychic_DesireeIntro:
	.string "Allow me to demonstrate how a true\n"
	.string "Psychic conducts a battle!$"

Psychic_ElijahDefeat:
	.string "Urmmm...\n"
	.string "Urrrrmmmmm...$"

Psychic_ElijahPostBattle:
	.string "There still remain many mysteries yet\n"
	.string "to be solved in this strange world...$"

Psychic_ElijahIntro:
	.string "When a Trainer and a Pokémon bond\n"
	.string "as one, a wondrous power is born...$"

Psychic_KendraDefeat:
	.string "The future...is different!\n"
	.string "Why?!$"

Psychic_KendraPostBattle:
	.string "Your efforts have altered the very\n"
	.string "path of the future!$"

Psychic_KendraIntro:
	.string "I see it!\n"
	.string "I see a victory for me!$"

Psychic_KodyDefeat:
	.string "Oh, no!\n"
	.string "My MEDITITE!$"

Psychic_KodyPostBattle:
	.string "The Old Chateau... I sense...\n"
	.string "a particularly strong presence there.$"

Psychic_KodyIntro:
	.string "A strange presence has been felt...\n"
	.string "It is emanating from...you!$"

Psychic_LandonDefeat:
	.string "...!$"

Psychic_LandonPostBattle:
	.string "I can use psychic powers, but\n"
	.string "battling isn’t so simple...\p"
	.string "It takes much more to win!$"

Psychic_LandonIntro:
	.string "Now we shall battle, and from it will\n"
	.string "emerge one loser...$"

Psychic_LindseyDefeat:
	.string "It is I that has gone down in defeat.$"

Psychic_LindseyPostBattle:
	.string "The Old Chateau...\n"
	.string "There should be none alive in it...\p"
	.string "And yet there is a pervasive sense of\n"
	.string "a presence...$"

Psychic_LindseyIntro:
	.string "I see it...\n"
	.string "I see it...\p"
	.string "I see you going down in defeat...$"

Psychic_MaxwellDefeat:
	.string "I see...\p"
	.string "So that’s what it was...$"

Psychic_MaxwellPostBattle:
	.string "I feel... I feel some sort of a mystic\n"
	.string "presence emanating from here...$"

Psychic_MaxwellIntro:
	.string "For some reason I was drawn here,\n"
	.string "and it is here that I met you...\p"
	.string "I want to know what all this means!$"

Psychic_MaxwellRematch:
	.string "Why have you come back to this spot?\n"
	.string "I want to know what all this means!$"

Psychic_MitchellDefeat:
	.string "Defeating you will be no easy matter.$"

Psychic_MitchellPostBattle:
	.string "Is it possible to become more\n"
	.string "powerful by understanding Pokémon?$"

Psychic_MitchellIntro:
	.string "I’d sensed the presence of a\n"
	.string "Trainer for a while. It was you!$"

Psychic_MitchellRematch:
	.string "I was certain that you’d return.\n"
	.string "I sensed your presence, you see.$"

Psychic_RachaelDefeat:
	.string "Your victory...\n"
	.string "There is nothing strange about it.$"

Psychic_RachaelPostBattle:
	.string "Forests are mystifying... They seem\n"
	.string "to gather such unexplainable energy.$"

Psychic_RachaelIntro:
	.string "This forest is strange, you know...\n"
	.string "It seems to fill me with energy...$"

Psychic_SterlingDefeat:
	.string "There’s nothing wonderful about this!$"

Psychic_SterlingPostBattle:
	.string "Is my sense of premonition nothing\n"
	.string "to write home about?$"

Psychic_SterlingIntro:
	.string "I had a revelation this morning.\p"
	.string "I knew that I would have a wonderful\n"
	.string "encounter here today.$"

Psychic_ValenciaDefeat:
	.string "Your past...\n"
	.string "You’ve been through a lot...$"

Psychic_ValenciaPostBattle:
	.string "Let me guess.\n"
	.string "Have you met any legendary Pokémon?$"

Psychic_ValenciaIntro:
	.string "I am a Psychic!\n"
	.string "I can see your past!$"

Rancher_MarcoDefeat:
	.string "Hahahah! Your Pokémon sure can be\n"
	.string "counted on!$"

Rancher_MarcoPostBattle:
	.string "When I cuddle with my Pokémon, I can\n"
	.string "feel not just their bodies’ warmth, but\p"
	.string "their compassion.$"

Rancher_MarcoIntro:
	.string "My Pokémon toughened up while working\n"
	.string "on the ranch.\p"
	.string "I’m right proud of them!$"

Rancher_MarcoRematch:
	.string "Whoa! You’re that real-tough\n"
	.string "Trainer from before!\p"
	.string "Here are my ranch-toughened Pokémon!\n"
	.string "I’m right proud of them!$"

Ranger_AllisonDefeat:
	.string "We have to get tougher than this...$"

Ranger_AllisonPostBattle:
	.string "I love how natural it is here.\n"
	.string "I wish I could live out here.$"

Ranger_AllisonIntro:
	.string "Protect the natural environment.\n"
	.string "That’s what we Rangers do!$"

Ranger_AllisonRematch:
	.string "What do you think? The environment\n"
	.string "is unharmed in this area.$"

Ranger_AshleeDefeat:
	.string "My, you are tough.$"

Ranger_AshleePostBattle:
	.string "It doesn’t matter where they grow.\p"
	.string "Pokémon can be made tougher\n"
	.string "anywhere if you set your mind to it.$"

Ranger_AshleeIntro:
	.string "In the embrace of Mother Nature,\n"
	.string "people and Pokémon grow strong!$"

Ranger_AshleeRematch:
	.string "By battling tough opponents, both\n"
	.string "people and Pokémon grow tough!$"

Ranger_DeshawnDefeat:
	.string "Oh, my gosh!\n"
	.string "My poor Pokémon!$"

Ranger_DeshawnPostBattle:
	.string "Everyone can do their part to keep\n"
	.string "nature clean. It doesn’t take much.$"

Ranger_DeshawnIntro:
	.string "I work to protect beautiful, natural\n"
	.string "environments.\p"
	.string "My Pokémon are my constant\n"
	.string "companions while I work.$"

Ranger_DeshawnRematch:
	.string "I’m on patrol in pristine nature\n"
	.string "with my Pokémon like usual.\p"
	.string "Come to think of it, you’re always\n"
	.string "with Pokémon, too.$"

Ranger_DwayneDefeat:
	.string "Thanks much!$"

Ranger_DwaynePostBattle:
	.string "Using the Pokémon ability Pickup for\n"
	.string "gathering dropped items is a good thing.\p"
	.string "I think it’s ecological, even.\n"
	.string "I am cleaning up the environment!$"

Ranger_DwayneIntro:
	.string "We go on patrol to make sure there’s\n"
	.string "nothing strange going on.\p"
	.string "And occasionally, we battle!$"

Ranger_DwayneRematch:
	.string "Patrols day in and day out!\n"
	.string "And the occasional battle!$"

Ranger_FeliciaDefeat:
	.string "You’re really tough, aren’t you?!$"

Ranger_FeliciaPostBattle:
	.string "Look around you at this wildly\n"
	.string "contorted terrain.\p"
	.string "It’s no wonder that Pokémon would\n"
	.string "grow tough in a place like this.$"

Ranger_FeliciaIntro:
	.string "We’ve grown strong together in\n"
	.string "nature and in the concrete jungle.\p"
	.string "We make everywhere we go our\n"
	.string "playground!$"

Ranger_FeliciaRematch:
	.string "We’re tough, but we know you’re just\n"
	.string "as tough!\p"
	.string "Let’s battle it out to see which one of\n"
	.string "us is tougher!$"

Ranger_JeffreyDefeat:
	.string "Good. You seem to be a kindhearted\n"
	.string "Trainer.$"

Ranger_JeffreyPostBattle:
	.string "Listen, people and Pokémon, we’re all a\n"
	.string "part of Mother Nature.$"

Ranger_JeffreyIntro:
	.string "Heya, Trainer!\n"
	.string "Are you being good to Mother Nature?$"

Ranger_JeffreyRematch:
	.string "Heya, long time!\p"
	.string "Are you enjoying your nature-filled\n"
	.string "adventure with Pokémon?$"

Ranger_KristaDefeat:
	.string "You’re not tired at all?!$"

Ranger_KristaPostBattle:
	.string "The world is full of Pokémon and all\n"
	.string "sorts of Trainers.$"

Ranger_KristaIntro:
	.string "Are you getting worn out from all\n"
	.string "the running you’ve done?$"

Ranger_KristaRematch:
	.string "What do you think of the Battle\n"
	.string "Zone?\p"
	.string "You’ve met so many Pokémon...\n"
	.string "I’ve got to battle you again!$"

Ranger_KylerDefeat:
	.string "You’re A-OK!$"

Ranger_KylerPostBattle:
	.string "Protecting Pokémon and nature.\n"
	.string "Think of what that means.$"

Ranger_KylerIntro:
	.string "People! Nature! Pokémon!\n"
	.string "Harmony is essential!$"

Ranger_KylerRematch:
	.string "Do you remember my slogan?\n"
	.string "People! Nature! Pokémon!\p"
	.string "That’s right. Harmony is essential!$"

Ranger_TaylorDefeat:
	.string "You’ve got energy to burn!$"

Ranger_TaylorPostBattle:
	.string "Even if a battle gets heated, don’t\n"
	.string "break branches off trees or anything.$"

Ranger_TaylorIntro:
	.string "Hi, Trainer!\n"
	.string "Can you keep up with me?$"

Ranger_TaylorRematch:
	.string "Hey! You’re that high-energy Trainer!\n"
	.string "I bet you can’t keep up with us now!$"

Reporter_KinseyDefeat:
	.string "The press is the victim!$"

Reporter_Kinsey_UnusedDefeat:
	.string "The media is the victim!$"

Reporter_Kinsey_UnusedPostBattle:
	.string "Interviews are about taking the\n"
	.string "initiative. The people need to know.$"

Reporter_Kinsey_UnusedIntro:
	.string "Join me in this on-the-spot report,\n"
	.string "live at the scene of a battle!$"

Reporter_ValerieDefeat:
	.string "Hmm...\n"
	.string "I should have expected this.$"

Rich_Boy_JasonDefeat:
	.string "What? Over already?\n"
	.string "Well, that’s fine.\p"
	.string "Rich people like me don’t fight.$"

Rich_Boy_JasonPostBattle:
	.string "Oh, no.\n"
	.string "My Pokémon is worn out.\p"
	.string "I’d better let it sleep it off in the\n"
	.string "bed I had sent from overseas.$"

Rich_Boy_JasonIntro:
	.string "My Pokémon sleeps in a bed I got from\n"
	.string "overseas.\p"
	.string "I’m very well off, if you haven’t\n"
	.string "noticed!$"

Rich_Boy_JasonRematch:
	.string "I do this only because I love my\n"
	.string "Pokémon. Winning isn’t that important.$"

Rich_Boy_LiamDefeat:
	.string "Too much for me!$"

Rich_Boy_RomanDefeat:
	.string "I never thought I’d lose at\n"
	.string "Papa’s restaurant...$"

Rich_Boy_TreyDefeat:
	.string "The monotony was broken, but...$"

Rich_Boy_TreyPostBattle:
	.string "I’m going back to the hotel to rest!\n"
	.string "I find you exceedingly tiresome!$"

Rich_Boy_TreyIntro:
	.string "I need to escape these doldrums...\n"
	.string "You can keep me company.$"

Rich_Boy_TreyRematch:
	.string "Ah, it’s you. I’m bored yet again.\n"
	.string "Care to break the monotony?$"

Riley_BattlegroundDefeat:
	.string "At times we battle, and sometimes we\n"
	.string "team up...\p"
	.string "It’s great how Trainers can interact.$"

Rival_Canalave_City_ChimcharDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Canalave_City_PiplupDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Canalave_City_TurtwigDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Pastoria_City_ChimcharDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Pastoria_City_PiplupDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Pastoria_City_TurtwigDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Pokemon_League_ChimcharDefeat:
	.string "What just went down?!\n"
	.string "My team still needs raising?!$"

Rival_Pokemon_League_PiplupDefeat:
	.string "What just went down?!\n"
	.string "My team still needs raising?!$"

Rival_Pokemon_League_TurtwigDefeat:
	.string "What just went down?!\n"
	.string "My team still needs raising?!$"

Rival_Route_209_ChimcharDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Route_209_PiplupDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Route_209_TurtwigDefeat:
	.string "What just happened?!\n"
	.string "You’re telling me I lost?!$"

Rival_Survival_Area_1_ChimcharDefeat:
	.string "What just went down?!\n"
	.string "You’re telling me I lost again?!$"

Rival_Survival_Area_1_PiplupDefeat:
	.string "What just went down?!\n"
	.string "You’re telling me I lost again?!$"

Rival_Survival_Area_1_TurtwigDefeat:
	.string "What just went down?!\n"
	.string "You’re telling me I lost again?!$"

Rival_Survival_Area_2_ChimcharDefeat:
	.string "What was that about?!\p"
	.string "I’m going to get tougher, though!\n"
	.string "Tougher with these guys!$"

Rival_Survival_Area_2_PiplupDefeat:
	.string "What was that about?!\p"
	.string "I’m going to get tougher, though!\n"
	.string "Tougher with these guys!$"

Rival_Survival_Area_2_TurtwigDefeat:
	.string "What was that about?!\p"
	.string "I’m going to get tougher, though!\n"
	.string "Tougher with these guys!$"

Rival_Survival_Area_Unused_ChimcharDefeat:
	.string "What just went down?!\n"
	.string "You wait! I’ll get tougher!$"

Rival_Survival_Area_Unused_PiplupDefeat:
	.string "What just went down?!\n"
	.string "You wait! I’ll get tougher!$"

Rival_Survival_Area_Unused_TurtwigDefeat:
	.string "What just went down?!\n"
	.string "You wait! I’ll get tougher!$"

Roughneck_KirbyDefeat:
	.string "Gwaaaaaah!$"

Roughneck_KirbyPostBattle:
	.string "I’m not doing my Pokémon any favors\n"
	.string "by ruining its memory like this...\p"
	.string "I can’t be wallowing around forever.\n"
	.string "I gotta move on and turn the page.$"

Roughneck_KirbyIntro:
	.string "My Pokémon were taken from me...\n"
	.string "Team Galactic did it...\p"
	.string "Ever since, I’ve never forgiven\n"
	.string "their faces...$"

Ruin_Maniac_BryanDefeat:
	.string "It’s a challenge trying to win with\n"
	.string "Pokémon one isn’t familiar with...$"

Ruin_Maniac_BryanPostBattle:
	.string "Discovery is the treasure I seek.\n"
	.string "Collecting a lot is my life!$"

Ruin_Maniac_BryanIntro:
	.string "Ah-ha! I found me a Trainer!\p"
	.string "I challenge you to battle with\n"
	.string "the Pokémon I’ve found!$"

Ruin_Maniac_BryanRematch:
	.string "Ah-ha! I found me a Trainer!\p"
	.string "I challenge you to battle with\n"
	.string "the Pokémon I’ve found!$"

Ruin_Maniac_CalvinDefeat:
	.string "I can’t win.\n"
	.string "You’re too strong for me to win.$"

Ruin_Maniac_CalvinPostBattle:
	.string "If one’s after treasures, maybe the\n"
	.string "Underground is the better choice.$"

Ruin_Maniac_CalvinIntro:
	.string "I’m a treasure hunter.\p"
	.string "Today, the loot is a victory from\n"
	.string "you!$"

Ruin_Maniac_CalvinRematch:
	.string "I’m a treasure hunter.\p"
	.string "This time for sure, the loot is\n"
	.string "victory over you!$"

Ruin_Maniac_GeraldDefeat:
	.string "Your awesome power...\n"
	.string "It’s mystifying.$"

Ruin_Maniac_GeraldPostBattle:
	.string "I’ve scoured every inch of this\n"
	.string "place... Most of it while I was lost.\p"
	.string "Anyway, if there’s one thing I can\n"
	.string "say, this place can’t be called ruins!$"

Ruin_Maniac_GeraldIntro:
	.string "In deep tunnels and caves, there’re\n"
	.string "a couple things you’re sure to see.\p"
	.string "ZUBAT and Ruin Maniacs!$"

Ruin_Maniac_HarryDefeat:
	.string "My investigation revealed the Trainer\n"
	.string "to be tough!$"

Ruin_Maniac_HarryPostBattle:
	.string "Celestic Town is an old town.\n"
	.string "I’m sure to find something cool.$"

Ruin_Maniac_HarryIntro:
	.string "Whilst exploring the ruins, I spotted\n"
	.string "a Trainer! I must investigate!$"

Ruin_Maniac_HarryRematch:
	.string "Whilst exploring the ruins, I spotted\n"
	.string "you again! I will investigate!$"

Ruin_Maniac_KarlDefeat:
	.string "The search must continue!$"

Ruin_Maniac_KarlPostBattle:
	.string "The significance of the ancient ruins...\p"
	.string "Only Pokémon that look like the letters\n"
	.string "of some strange language...\p"
	.string "Can they be trying to convey a message\n"
	.string "to us?$"

Ruin_Maniac_KarlIntro:
	.string "Ancient ruins rife with the UNOWN...\n"
	.string "There has to be a meaning!\p"
	.string "But its significance eludes me, and\n"
	.string "that’s gotten me cranky!$"

Ruin_Maniac_LarryDefeat:
	.string "My Pokémon!\n"
	.string "My treasures!$"

Ruin_Maniac_LarryPostBattle:
	.string "I heard there’s an intriguing stone\n"
	.string "monument around, so I came running.$"

Ruin_Maniac_LarryIntro:
	.string "I don’t care who you are--no one\n"
	.string "interferes with my treasure hunting!$"

Ruin_Maniac_LarryRematch:
	.string "I’m still here...and still searching\n"
	.string "for treasures.\p"
	.string "However, a battle with you\n"
	.string "is a treasure I can’t pass up!$"

Ruin_Maniac_RonaldDefeat:
	.string "Gasp... One more... Gasp...\n"
	.string "It’s like I went on a diet...$"

Ruin_Maniac_RonaldPostBattle:
	.string "There are mysteries waiting for me\n"
	.string "to investigate around the world.\p"
	.string "This is no time to be feeling sorry\n"
	.string "for myself.$"

Ruin_Maniac_RonaldIntro:
	.string "I travel all over the world in search of\n"
	.string "mysteries.$"

Ruin_Maniac_RonaldRematch:
	.string "There’s an endless supply of\n"
	.string "mysteries around the world.\p"
	.string "Running into you here just happens\n"
	.string "to be one such mystery!$"

Sailor_DamianDefeat:
	.string "You!\n"
	.string "You’re truly top-class tough!$"

Sailor_DamianPostBattle:
	.string "If you were to go around the world,\n"
	.string "I’m sure you’d meet tougher Pokémon.$"

Sailor_DamianIntro:
	.string "I’ve been around the world, going from\n"
	.string "place to place training Pokémon.\p"
	.string "It’s this Gym I’ve chosen to make my\n"
	.string "home!\p"
	.string "You can bet it’s tough!$"

Sailor_LutherDefeat:
	.string "I lost, but I am one step closer to\n"
	.string "realizing my dream!$"

Sailor_LutherPostBattle:
	.string "Listen, you! Whatever happens, never\n"
	.string "lose sight of your dream!$"

Sailor_LutherIntro:
	.string "My dream’s a big one!\p"
	.string "I want to battle every kind of Pokémon\n"
	.string "from around the world!$"

Sailor_LutherRematch:
	.string "All right, you!\p"
	.string "Help me realize my dream of battling\n"
	.string "every kind of Pokémon there is!$"

Sailor_MarcDefeat:
	.string "Your Pokémon...\n"
	.string "They’re looking good!$"

Sailor_MarcPostBattle:
	.string "You ought to think about becoming\n"
	.string "a Sailor yourself.\p"
	.string "It’s been great to be able to visit\n"
	.string "different places around the world.$"

Sailor_MarcIntro:
	.string "Oh, we’ll ride upon the sea,\n"
	.string "in a boat, just you and me!\p"
	.string "That’s the way of the Sailor!\n"
	.string "Way of the Sailor. Sing it!$"

Sailor_MarcRematch:
	.string "Oh, we’ll ride upon the sea,\n"
	.string "in a boat, just you and me!\p"
	.string "That’s the way of the Sailor!\n"
	.string "Way of the Sailor. You sing, too!$"

Sailor_PaulDefeat:
	.string "You’re good, pip-squeak!$"

Sailor_PaulPostBattle:
	.string "Maybe I’ll go work out down at the\n"
	.string "restaurant again.\p"
	.string "That place gets different people in\n"
	.string "every day, and they all like battles.$"

Sailor_PaulIntro:
	.string "Traveling alone, are you? That’s\n"
	.string "impressive! How about we battle?$"

Sailor_PaulRematch:
	.string "Hey, lonesome traveler! Let’s break\n"
	.string "the monotony with another battle!$"

Sailor_SamsonDefeat:
	.string "That wave didn’t even wash\n"
	.string "my hands...$"

Sailor_SamsonPostBattle:
	.string "I’m now becalmed like a waveless\n"
	.string "sea...$"

Sailor_SamsonIntro:
	.string "Like the raging sea, I crash down\n"
	.string "and wash away everything before me!\p"
	.string "That’s just how I roll!$"

Sailor_SkylerDefeat:
	.string "Anchors away!$"

Sailor_SkylerPostBattle:
	.string "You’ve got what it takes to be\n"
	.string "a Trainer among Trainers!$"

Sailor_SkylerIntro:
	.string "A man of the sea is also a man of\n"
	.string "Pokémon!$"

Sailor_SkylerRematch:
	.string "Hard to starboard!\n"
	.string "That’s a sharp turn to the right!\p"
	.string "Hard to port!\n"
	.string "And that’s a sharp turn to the left!$"

Sailor_ZachariahDefeat:
	.string "I’m shocked...\n"
	.string "No, really.$"

Sailor_ZachariahPostBattle:
	.string "The way I battle now, well, I can\n"
	.string "only look at the Pokémon League!\p"
	.string "You, go on! You go to the Pokémon\n"
	.string "League for me, too!$"

Sailor_ZachariahIntro:
	.string "I came out here because I wanted to\n"
	.string "see the Pokémon League for myself.$"

Sailor_ZachariahRematch:
	.string "I’ve been training here in hopes of\n"
	.string "going to the Pokémon League.$"

School_Kid_ChanceDefeat:
	.string "Let me guess.\n"
	.string "You are enjoying yourself.$"

School_Kid_ChancePostBattle:
	.string "Whatever happens in life, it’s better to\n"
	.string "try to enjoy it the best one can.\p"
	.string "Being in the dark here, I came to\n"
	.string "realize that.$"

School_Kid_ChanceIntro:
	.string "Are you lost?\n"
	.string "Are you enjoying yourself?$"

School_Kid_ChristineDefeat:
	.string "I like to study a lot...\n"
	.string "I thought I could win...$"

School_Kid_EstebanDefeat:
	.string "Wow... You’re out there.$"

School_Kid_ForrestDefeat:
	.string "...You’re tough.$"

School_Kid_ForrestPostBattle:
	.string "You just showed me that there’s\n"
	.string "still lots I need to learn.\p"
	.string "The world of Pokémon is deep!$"

School_Kid_ForrestIntro:
	.string "This is the toughest Gym in Sinnoh.\p"
	.string "That’s why I’m here--to learn the\n"
	.string "best battle techniques around!$"

School_Kid_HarrisonDefeat:
	.string "Ugh...\n"
	.string "I didn’t use items effectively.$"

School_Kid_MackenzieDefeat:
	.string "Your strength is dazzling!\n"
	.string "I have to shield my eyes!$"

School_Kid_MackenziePostBattle:
	.string "I’m going over the reasons why I\n"
	.string "lost. That way, I’ll win next time.$"

School_Kid_MackenzieIntro:
	.string "Eek! That’s so bright!\p"
	.string "Surprise attack!$"

School_Kid_TieraDefeat:
	.string "The gears spin round and round...\n"
	.string "I spin down and out...$"

School_Kid_TieraPostBattle:
	.string "Our Gym’s trick walkways are sure\n"
	.string "to make your head spin!$"

School_Kid_TieraIntro:
	.string "Can you make it to the Gym Leader?\n"
	.string "You sure now?$"

Scientist_DarriusDefeat:
	.string "I got whipped...\n"
	.string "I look pathetic...$"

Scientist_DarriusPostBattle:
	.string "Our boss is a scientific genius!\p"
	.string "He will make the power of mythical\n"
	.string "Pokémon his own!$"

Scientist_DarriusIntro:
	.string "I won’t let you disrupt our research!\n"
	.string "This is for Team Galactic!$"

Scientist_EmilioDefeat:
	.string "Hmm... I failed to foresee this\n"
	.string "outcome...$"

Scientist_FredrickDefeat:
	.string "You and your Pokémon weren’t part\n"
	.string "of my calculations...$"

Scientist_FredrickPostBattle:
	.string "Our boss is trying to create an\n"
	.string "entirely new world.\p"
	.string "A world only for us!\n"
	.string "For Team Galactic!$"

Scientist_FredrickIntro:
	.string "Hey, now! Our HQ is a state-of-the-\n"
	.string "art facility!\p"
	.string "A snot-nosed kid like you ought to\n"
	.string "keep your dirty hands to yourself!$"

Scientist_ShaunDefeat:
	.string "Our research arrived at this one\n"
	.string "conclusion: you’re tough!$"

Scientist_ShaunPostBattle:
	.string "A huge variety of Pokémon live in the\n"
	.string "Great Marsh.\p"
	.string "You see, countless years ago,\n"
	.string "this whole area was under the sea.$"

Scientist_ShaunIntro:
	.string "Oh? Here comes a nice-looking\n"
	.string "Trainer. This is worth evaluation.$"

Scientist_ShaunRematch:
	.string "Oh, how do you do? May I investigate\n"
	.string "how much tougher you’ve become since\p"
	.string "our last encounter?$"

Scientist_StefanoDefeat:
	.string "Ufufufufu...\n"
	.string "You had to beat me...$"

Scientist_StefanoPostBattle:
	.string "It feels good to mope here after a\n"
	.string "loss... Ufufufufu...$"

Scientist_StefanoIntro:
	.string "I find it reassuring to be on this\n"
	.string "damp soil...$"

Scientist_StefanoRematch:
	.string "Is Damp my favorite Pokémon ability?\n"
	.string "Fufufu... Anything will do...$"

Scientist_TravonDefeat:
	.string "This won’t go unpunished...$"

Scientist_TravonPostBattle:
	.string "I’m willing to do anything to get ahead\n"
	.string "in Team Galactic.\p"
	.string "One day you’ll see what we are all\n"
	.string "about.\p"
	.string "It’s wonder, compassion, splendor,\n"
	.string "humor, power, awe, and tragedy!$"

Scientist_TravonIntro:
	.string "Our mission is to implement our\n"
	.string "operations without question.\p"
	.string "It is all for the new world order\n"
	.string "that our boss will lead!$"

Skier_AndreaDefeat:
	.string "The winds of victory shifted...$"

Skier_AndreaPostBattle:
	.string "It’s so cold here, but here you are,\n"
	.string "so full of energy.\p"
	.string "I guess you kids are made tougher\n"
	.string "than people my age.$"

Skier_AndreaIntro:
	.string "How do you expect to battle in this\n"
	.string "heavy snow?$"

Skier_AndreaRematch:
	.string "Why would you wander around here?\n"
	.string "You must really like it here.$"

Skier_BjornDefeat:
	.string "I got a good taste of your power!$"

Skier_BjornPostBattle:
	.string "Trainers get an appreciation of life\n"
	.string "through Pokémon. At least I think so.$"

Skier_BjornIntro:
	.string "We Skiers feel Mother Nature through\n"
	.string "the soles of our feet!$"

Skier_BjornRematch:
	.string "I knew you were headed back here.\n"
	.string "I felt it with the soles of my feet!$"

Skier_BradleyDefeat:
	.string "...I’ve hit an ice patch!$"

Skier_BradleyPostBattle:
	.string "I quite enjoyed that battle!\n"
	.string "Let us meet again. Slalom!$"

Skier_BradleyIntro:
	.string "I’m skiing right now, but OK.\n"
	.string "As we Skiers say, “Spur thing!”$"

Skier_BradleyRematch:
	.string "We might get snowbound, but why not?\n"
	.string "It’s on the “spur” of the moment!$"

Skier_EdwardDefeat:
	.string "I can see why you’re an expert...$"

Skier_EdwardPostBattle:
	.string "You know how to play your Pokémon\n"
	.string "with an edge!$"

Skier_EdwardIntro:
	.string "Are you a novice?\n"
	.string "Or around midlevel?$"

Skier_EdwardRematch:
	.string "Knowing you to be an expert,\n"
	.string "I challenge you to a rematch!$"

Skier_KaitlynDefeat:
	.string "Snivel...$"

Skier_KaitlynPostBattle:
	.string "If it was skiing, I wouldn’t lose.\n"
	.string "I should go ski with my Pokémon...$"

Skier_KaitlynIntro:
	.string "The fun things about winter!\n"
	.string "One, skiing! Two, Pokémon!$"

Skier_KaitlynRematch:
	.string "You’re a better Trainer than a skier.\n"
	.string "But I’ll challenge you again anyway!$"

Skier_LexieDefeat:
	.string "Hunh, what...?\n"
	.string "I repeat, hunh, what...?$"

Skier_LexiePostBattle:
	.string "The scenery doesn’t change very much\n"
	.string "around here. Don’t go getting lost!$"

Skier_LexieIntro:
	.string "I’ve been skiing with Pokémon since\n"
	.string "I was just five years old.$"

Skier_LexieRematch:
	.string "Oh... Did you maybe get lost again?\n"
	.string "You should pay more attention!$"

Skier_MadisonDefeat:
	.string "The conditions weren’t very good.$"

Skier_MadisonPostBattle:
	.string "Can any of your Pokémon use that\n"
	.string "hidden move to climb cliffs?$"

Skier_MadisonIntro:
	.string "Rainy days make me feel blue...\p"
	.string "But the instant it starts to snow,\n"
	.string "I’m as happy as can be!$"

Skier_MadisonRematch:
	.string "You really must like snow.\p"
	.string "After all, if you didn’t, I doubt that\n"
	.string "you’d come here so often!$"

Skier_ShawnDefeat:
	.string "I don’t believe it...\n"
	.string "My techniques were rebuffed...$"

Skier_ShawnPostBattle:
	.string "Maybe I should’ve studied at the\n"
	.string "Trainers’ school instead...$"

Skier_ShawnIntro:
	.string "I’ll show you the techniques I had\n"
	.string "drummed into me at ski school!$"

Skier_ShawnRematch:
	.string "Since I lost to you last time,\n"
	.string "I redid my training at ski school!$"

Socialite_RebeccaDefeat:
	.string "So young, and yet so strong!\n"
	.string "How very remarkable!$"

Socialite_ReinaDefeat:
	.string "Oh, dear... This isn’t anything like\n"
	.string "battling with my friends.$"

Socialite_ReinaPostBattle:
	.string "Usually, I’ll have matches with\n"
	.string "members of my social club.$"

Socialite_ReinaIntro:
	.string "I’ve never battled a young Trainer like\n"
	.string "yourself. It’s quite nerve wracking.$"

Socialite_ReinaRematch:
	.string "Oh, it’s you again, dear?\p"
	.string "It makes me a little nervous, but\n"
	.string "may I have a rematch?$"

Swimmer_AdrianDefeat:
	.string "Oh, yeah, that was fun!\n"
	.string "I learned something good!$"

Swimmer_AdrianPostBattle:
	.string "It’s what I live for!\n"
	.string "Pokémon!$"

Swimmer_AdrianIntro:
	.string "I only live to swim. Teach me what’s\n"
	.string "so fun about Pokémon!$"

Swimmer_AdrianRematch:
	.string "Hey, didn’t you teach me what’s so fun\n"
	.string "about Pokémon?\p"
	.string "Teach me more.\n"
	.string "I’m eager to learn!$"

Swimmer_AubreeDefeat:
	.string "Was I multitasking too much, battling\n"
	.string "and swimming at the same time?$"

Swimmer_AubreePostBattle:
	.string "When I’m in my bikini, I’m at a loss\n"
	.string "about where to carry my Poké Balls!$"

Swimmer_AubreeIntro:
	.string "Excuse me for wearing my bikini!$"

Swimmer_AubreeRematch:
	.string "Giggle...\n"
	.string "Excuse me for wearing my bikini!$"

Swimmer_CassandraDefeat:
	.string "I’m speechless!\n"
	.string "I never lose when I’m in my swimsuit!$"

Swimmer_CassandraPostBattle:
	.string "I shouldn’t be worried about what bikini\n"
	.string "to wear.\p"
	.string "The first thing to do is consider what\n"
	.string "Pokémon I should be using!$"

Swimmer_CassandraIntro:
	.string "Did you know, I was crowned the\n"
	.string "champion of a swimsuit contest!\p"
	.string "So now, I’m trying to win a title\n"
	.string "at a Pokémon Contest!$"

Swimmer_CassandraRematch:
	.string "I’m so wonderful, I won a swimsuit\n"
	.string "contest.\p"
	.string "I’m going to take you on so that I can\n"
	.string "win a Pokémon Contest!$"

Swimmer_ClaireDefeat:
	.string "Psssssh!$"

Swimmer_ClairePostBattle:
	.string "I bought the wrong size of bikini.\n"
	.string "It’s a little too snug...$"

Swimmer_ClaireIntro:
	.string "I bought a new bikini!\n"
	.string "It’s this year’s newest model!$"

Swimmer_ClaireRematch:
	.string "Did I show you already?\n"
	.string "My bikini, new for this year!$"

Swimmer_ColtonDefeat:
	.string "Boo!\n"
	.string "I’m not done with my dream!$"

Swimmer_ColtonPostBattle:
	.string "What is the sea like in places like the\n"
	.string "Kanto and Hoenn regions?$"

Swimmer_ColtonIntro:
	.string "To swim every sea there is...\n"
	.string "That’s my dream!$"

Swimmer_ColtonRematch:
	.string "Challenging every Pokémon League...\n"
	.string "That’s another of my dreams!$"

Swimmer_CrystalDefeat:
	.string "I’ve had my fill...$"

Swimmer_CrystalPostBattle:
	.string "While floating here, I think about\n"
	.string "everything and nothing.\p"
	.string "Like how I should battle next, and\n"
	.string "what’s for dinner tomorrow, and...$"

Swimmer_CrystalIntro:
	.string "Your Pokémon doesn’t seem to be tiring\n"
	.string "at all from carrying you on its back.\p"
	.string "Let me see how strong it is!$"

Swimmer_CrystalRematch:
	.string "How much stronger did your Pokémon\n"
	.string "become?\p"
	.string "Let me check for you, OK?$"

Swimmer_DillonDefeat:
	.string "I’m finally feeling fatigued...$"

Swimmer_DillonPostBattle:
	.string "I may look like I’m swimming\n"
	.string "gracefully, but beneath the surface\p"
	.string "I’m kicking furiously.$"

Swimmer_DillonIntro:
	.string "Well? Does it look like I’m swimming\n"
	.string "gracefully?$"

Swimmer_DillonRematch:
	.string "You were attracted by my graceful\n"
	.string "swimming again, weren’t you?$"

Swimmer_EricaDefeat:
	.string "The sea is salty, but all I taste is\n"
	.string "bitterness...$"

Swimmer_EricaPostBattle:
	.string "I’ve got that sinking feeling...$"

Swimmer_EricaIntro:
	.string "The human body floats more easily in\n"
	.string "the sea, so it’s easy to swim!$"

Swimmer_EricaRematch:
	.string "Pokémon can stay afloat even while\n"
	.string "carrying someone. That’s so cool!$"

Swimmer_ErikDefeat:
	.string "Yow-ow-ow-ow!\n"
	.string "My leg’s cramped up!$"

Swimmer_ErikPostBattle:
	.string "I forgot to do my stretching\n"
	.string "exercises...$"

Swimmer_ErikIntro:
	.string "On your marks, get set, go!\p"
	.string "...When I say that, let’s start.$"

Swimmer_ErikRematch:
	.string "Hi, I was waiting for you!\n"
	.string "Ready? On your marks, get set...$"

Swimmer_EvanDefeat:
	.string "The chill of the sea, and the\n"
	.string "coldness of defeat...\p"
	.string "It’s a double whammy.$"

Swimmer_EvanPostBattle:
	.string "Look at my lips...\n"
	.string "They’re the color of prunes!$"

Swimmer_EvanIntro:
	.string "Brr... I’m starting to get chilly.\n"
	.string "I could use a win to get warmed up.$"

Swimmer_EvanRematch:
	.string "Brr... I’m starting to feel chilly.\n"
	.string "How about a hot Pokémon battle?$"

Swimmer_FranciscoDefeat:
	.string "The world remains as harsh as\n"
	.string "ever...$"

Swimmer_FranciscoPostBattle:
	.string "What? You’ve got that many Gym\n"
	.string "Badges? No wonder you’re so tough...$"

Swimmer_FranciscoIntro:
	.string "The sea around these parts is harsh.\n"
	.string "As am I!$"

Swimmer_FranciscoRematch:
	.string "It’s me again! The harsh sea here\n"
	.string "should have toughened me up!$"

Swimmer_GabrielleDefeat:
	.string "The tide is going out...$"

Swimmer_GabriellePostBattle:
	.string "Don’t get me wrong, it’s not as if I\n"
	.string "don’t like mountain men.\p"
	.string "But, you know, my most favorite kind of\n"
	.string "guy looks great with Pokémon!$"

Swimmer_GabrielleIntro:
	.string "My favorite kind of guy is someone\n"
	.string "that looks good out on the open sea!$"

Swimmer_GabrielleRematch:
	.string "Hello again! You’re that Trainer who\n"
	.string "looks keen with your Pokémon!$"

Swimmer_GlennDefeat:
	.string "Awesome!\n"
	.string "You’re a real wild child!$"

Swimmer_GlennPostBattle:
	.string "You ride atop the waves while riding on\n"
	.string "a Pokémon!\p"
	.string "And you rode right over me!$"

Swimmer_GlennIntro:
	.string "A Trainer riding a Pokémon!\n"
	.string "I like that! Let’s battle it out!$"

Swimmer_GlennRematch:
	.string "Yo, Pokémon-riding Trainer!\n"
	.string "How about a rematch?$"

Swimmer_HaleyDefeat:
	.string "You sure schooled me there.$"

Swimmer_HaleyPostBattle:
	.string "Maybe I should switch to surfing,\n"
	.string "too...$"

Swimmer_HaleyIntro:
	.string "Hi, wave-riding Trainer!\n"
	.string "How about a battle on the sea?$"

Swimmer_HaleyRematch:
	.string "Hi, we meet again!\n"
	.string "Wave-riding Trainer!$"

Swimmer_JessicaDefeat:
	.string "Sunk like a stone!$"

Swimmer_JessicaPostBattle:
	.string "Well, Pokémon’s one thing, but you\n"
	.string "should take up swimming, too!$"

Swimmer_JessicaIntro:
	.string "Swimming is a workout for your entire\n"
	.string "body.\p"
	.string "Jump in and swim!\n"
	.string "Swim, you!$"

Swimmer_JessicaRematch:
	.string "Hiya, Pokémon-riding Trainer!\n"
	.string "You should be swimming like me!$"

Swimmer_JoannaDefeat:
	.string "OK, we lost.$"

Swimmer_JoannaPostBattle:
	.string "I wanted to be alone, but swatting\n"
	.string "away immature boys on the prowl...\p"
	.string "Well, my Pokémon grew tough without\n"
	.string "me really even trying.$"

Swimmer_JoannaIntro:
	.string "People keep coming to us for battles.\n"
	.string "I really don’t know why! Teehee!$"

Swimmer_JoannaRematch:
	.string "People still keep coming to us for\n"
	.string "battles! Why?!$"

Swimmer_KatelynDefeat:
	.string "I lost, but at least I had fun.$"

Swimmer_KatelynPostBattle:
	.string "If it were an underwater Pokémon\n"
	.string "show, I would have shined.$"

Swimmer_KatelynIntro:
	.string "I may not look it now, but I’m a\n"
	.string "star. I’m always with my Pokémon.$"

Swimmer_KatelynRematch:
	.string "Oh, hi! Are you back to see our\n"
	.string "Pokémon show again?$"

Swimmer_KurtDefeat:
	.string "I’ve got a muscular physique, but\n"
	.string "there’s no strength behind it...$"

Swimmer_KurtPostBattle:
	.string "Seeing a Pokémon use Surf to carry you\n"
	.string "out on the sea...\p"
	.string "It strikes an emotional chord with me\n"
	.string "somewhere deep down.$"

Swimmer_KurtIntro:
	.string "Check out my physique! The rough\n"
	.string "seas sculpted this awesome body!$"

Swimmer_KurtRematch:
	.string "The rough seas almost drowned...\n"
	.string "...I mean, sculpted this awesome body!\p"
	.string "Let my chiseled physique inspire you!$"

Swimmer_LydiaDefeat:
	.string "Glub glub...\n"
	.string "I’m sinking...$"

Swimmer_LydiaPostBattle:
	.string "I thought that everyone would be all\n"
	.string "dedicated to training out here.\p"
	.string "But most people are really laid back.\n"
	.string "It’s not like what I imagined.\p"
	.string "I guess being with Pokémon, people get\n"
	.string "all mellowed out.$"

Swimmer_LydiaIntro:
	.string "I want to be with my water Pokémon!\n"
	.string "That’s why I swim!$"

Swimmer_LydiaRematch:
	.string "I want to be with water Pokémon!\n"
	.string "That’s why I’m going to get tougher!$"

Swimmer_MalloryDefeat:
	.string "Losing...\n"
	.string "Makes my tears well up.$"

Swimmer_MalloryPostBattle:
	.string "A mermaid’s tears are so salty...$"

Swimmer_MalloryIntro:
	.string "I’m a mermaid drifting among the\n"
	.string "waves...\p"
	.string "And a high-spirited gal who battles with\n"
	.string "Pokémon!$"

Swimmer_MalloryRematch:
	.string "I’m still a mermaid drifting among the\n"
	.string "waves...\p"
	.string "And a high-spirited gal who battles with\n"
	.string "Pokémon!$"

Swimmer_MaryDefeat:
	.string "What’s saltier?\n"
	.string "My tears or the sea...$"

Swimmer_MaryPostBattle:
	.string "There aren’t many sea routes that\n"
	.string "you can swim in Sinnoh.\p"
	.string "It makes me want to take a vacation\n"
	.string "in the Hoenn region.$"

Swimmer_MaryIntro:
	.string "Hello, there!\n"
	.string "Aren’t you going to swim?$"

Swimmer_MaryRematch:
	.string "When I see people surfing, I don’t\n"
	.string "feel jealous or anything.\p"
	.string "I just simply love to swim!$"

Swimmer_MirandaDefeat:
	.string "Th-this is so hard...$"

Swimmer_MirandaPostBattle:
	.string "Losing won’t make me quit.\n"
	.string "I mean, this is my dream!\p"
	.string "The Pokémon League isn’t going\n"
	.string "anywhere, either.$"

Swimmer_MirandaIntro:
	.string "I’m determined to go to the Pokémon\n"
	.string "League, no matter how hard it is.$"

Swimmer_MirandaRematch:
	.string "It doesn’t matter how long it takes,\n"
	.string "I’m going to the Pokémon League!$"

Swimmer_OscarDefeat:
	.string "Master Wake...\n"
	.string "I mean, Crasher Wake, sorry!$"

Swimmer_OscarPostBattle:
	.string "What to do... Train at the Gym again,\n"
	.string "or train by myself...$"

Swimmer_OscarIntro:
	.string "I train at a Pokémon Gym, too.\p"
	.string "Don’t think you’re going to win\n"
	.string "easily!$"

Swimmer_OscarRematch:
	.string "I trained at the Gym after you beat\n"
	.string "me. Let’s do it, gang!$"

Swimmer_PaigeDefeat:
	.string "Breathe in...and out.\n"
	.string "Breathe in...and out!$"

Swimmer_PaigePostBattle:
	.string "Deep breathing after battle, too!\n"
	.string "Breathe in...and out!$"

Swimmer_PaigeIntro:
	.string "Deep breathing before battle!\n"
	.string "Breathe in...and out!$"

Swimmer_PaigeRematch:
	.string "Deep breathing always!\n"
	.string "Breathe in...and out!$"

Swimmer_RicardoDefeat:
	.string "You’ve got the upper hand on me.$"

Swimmer_RicardoPostBattle:
	.string "But you can be sure that there will\n"
	.string "be bigger challenges in front of you.\p"
	.string "Go! Go as far as you can! You alone can\n"
	.string "broaden your horizons.$"

Swimmer_RicardoIntro:
	.string "It might not look like it, but I’m\n"
	.string "traveling now.$"

Swimmer_RicardoRematch:
	.string "I’m still on my journey...\n"
	.string "Let’s have a battle!$"

Swimmer_SamDefeat:
	.string "Oh.\n"
	.string "That’s how it is.$"

Swimmer_SamPostBattle:
	.string "Being a good swimmer doesn’t make\n"
	.string "me any better as a Trainer...$"

Swimmer_SamIntro:
	.string "Check out my dynamic form!\n"
	.string "Victory is assured!$"

Swimmer_SamRematch:
	.string "Hi! You’re that kid who’s great with\n"
	.string "Pokémon!\p"
	.string "I’ll battle with an even more dynamic\n"
	.string "form than before! Watch me now!$"

Swimmer_SheltinDefeat:
	.string "I lost at sea! But I swim here the\n"
	.string "whole year round!$"

Swimmer_SheltinPostBattle:
	.string "When you’re out at sea, Water-type\n"
	.string "Pokémon look more lively.$"

Swimmer_SheltinIntro:
	.string "I swim the whole year round.\n"
	.string "I’m not losing a battle at sea!$"

Swimmer_SheltinRematch:
	.string "I love the sea. It was only by fluke\n"
	.string "that I lost last time.$"

Swimmer_SophiaDefeat:
	.string "Maybe too grown up!$"

Swimmer_SophiaPostBattle:
	.string "I’ve grown with my Pokémon, too.\n"
	.string "My swimsuit’s getting a little tight...$"

Swimmer_SophiaIntro:
	.string "Are your Pokémon growing properly?$"

Swimmer_SophiaRematch:
	.string "Did your Pokémon grow any more?\p"
	.string "My Pokémon?\n"
	.string "Mine are doing awesome!$"

Swimmer_TroyDefeat:
	.string "Kaploosh!$"

Swimmer_TroyPostBattle:
	.string "If you don’t know how, I’m willing to\n"
	.string "show you how to swim.$"

Swimmer_TroyIntro:
	.string "Yes, I know I can surf, but I’d\n"
	.string "rather swim instead.\p"
	.string "It does seem weird, I agree.$"

Swimmer_TroyRematch:
	.string "If you rely on your Pokémon all the\n"
	.string "time, you’ll never learn how to swim!$"

Swimmer_VanessaDefeat:
	.string "I can’t boast when I lose...\n"
	.string "I’m so disappointed...$"

Swimmer_VanessaPostBattle:
	.string "Sure I lost, but watch me! I’ll get\n"
	.string "tougher with water Pokémon.$"

Swimmer_VanessaIntro:
	.string "One thing about Water-type Pokémon:\n"
	.string "There’s a huge variety!\p"
	.string "I’ll show you the Water-type Pokémon I\n"
	.string "chose and why I’m so proud of them!$"

Swimmer_VanessaRematch:
	.string "This time, my water Pokémon will show\n"
	.string "you why I’m so proud of them!$"

Swimmer_VincentDefeat:
	.string "I let my momentum falter...$"

Swimmer_VincentPostBattle:
	.string "Listen, I have something important to\n"
	.string "say to you.\p"
	.string "Don’t drown in your own talent.$"

Swimmer_VincentIntro:
	.string "OK! Get your breathing in order!\n"
	.string "OK! You’re ready to go!$"

Swimmer_VincentRematch:
	.string "OK! You’re ready to go!\n"
	.string "This time, I’m going for the win!$"

Swimmer_WadeDefeat:
	.string "Our muscles are deflating...$"

Swimmer_WadePostBattle:
	.string "Overwhelm with our dazzling physiques!\n"
	.string "That was our game plan...$"

Swimmer_WadeIntro:
	.string "Me and my Pokémon are pumped up\n"
	.string "and ready to go all out!$"

Swimmer_WadeRematch:
	.string "Me and my Pokémon are pumped up!\n"
	.string "See, our muscles are twitching!$"

Swimmer_WesleyDefeat:
	.string "Blblblblugh...$"

Swimmer_WesleyPostBattle:
	.string "It’s OK. Just let me float away\n"
	.string "like driftwood...$"

Swimmer_WesleyIntro:
	.string "I’ve decided!\n"
	.string "I’m off to the Pokémon League if I win!$"

Swimmer_WesleyRematch:
	.string "I’ve decided! If I finally beat you,\n"
	.string "I’m challenging the Pokémon League!$"

Tuber_CaitlynDefeat:
	.string "Groan...\n"
	.string "You’re too much.$"

Tuber_CaitlynPostBattle:
	.string "Maybe I’ll do like Wake...\p"
	.string "I mean, Crasher Wake, and use\n"
	.string "the same kinds of Pokémon.$"

Tuber_CaitlynIntro:
	.string "I want to become a strong Trainer\n"
	.string "like Crasher Wake!$"

Tuber_ChelseaDefeat:
	.string "I lost, and now I feel hungry.$"

Tuber_ChelseaPostBattle:
	.string "That cloud looks like giant ice cream!\n"
	.string "I bet it tastes yummy!$"

Tuber_ChelseaIntro:
	.string "Ehehe...\n"
	.string "I can battle, too!$"

Tuber_ChelseaRematch:
	.string "I’ve been lounging here all this\n"
	.string "time!$"

Tuber_ConnerDefeat:
	.string "Wowee! I had to hold on tight to\n"
	.string "my inflatable tube!$"

Tuber_ConnerPostBattle:
	.string "Pools are OK, but I like the sea\n"
	.string "because Pokémon live there.$"

Tuber_ConnerIntro:
	.string "Look, look! Look at my Pokémon!\n"
	.string "It’s really cool!$"

Tuber_ConnerRematch:
	.string "Yay! You came to see my Pokémon\n"
	.string "again, right? Look, look!$"

Tuber_HollyDefeat:
	.string "You’re so tough. I’m stunned...$"

Tuber_HollyPostBattle:
	.string "I want to hang on to a BUIZEL and\n"
	.string "just bob around.$"

Tuber_HollyIntro:
	.string "Listen, listen! Can you tell me what\n"
	.string "kind of Pokémon you have?$"

Tuber_HollyRematch:
	.string "Listen, listen! Did you find any new\n"
	.string "kinds of Pokémon?$"

Tuber_JackyDefeat:
	.string "Wow, Trainer! You just might be\n"
	.string "tougher than our Gym Leader!$"

Tuber_JackyPostBattle:
	.string "Maybe I’ll do like Wake,\p"
	.string "I mean, Crasher Wake, and wear\n"
	.string "the same kind of mask.$"

Tuber_JackyIntro:
	.string "My body isn’t the only thing I\n"
	.string "work on toughening up here.\p"
	.string "I also work on my Pokémon and my\n"
	.string "spirit!$"

Tuber_JaredDefeat:
	.string "I couldn’t move very well because\n"
	.string "my inflatable tube got in the way!$"

Tuber_JaredPostBattle:
	.string "Mom blew up my inflatable tube for me.\n"
	.string "I ran out of breath just opening it!$"

Tuber_JaredIntro:
	.string "Isn’t this nice?\n"
	.string "I love my inflatable tube!$"

Tuber_JaredRematch:
	.string "You can come back all you like, but\n"
	.string "you can’t have my inflatable tube!$"

Tuber_MarielDefeat:
	.string "They weren’t tough, my Pokémon...$"

Tuber_MarielPostBattle:
	.string "My mommy said that Professor Rowan\n"
	.string "is really kindhearted.$"

Tuber_MarielIntro:
	.string "I can’t swim without my inflatable tube.\n"
	.string "But my Pokémon might be strong!$"

Tuber_MarielRematch:
	.string "Oh! You’re the Trainer who played\n"
	.string "with us before!\p"
	.string "Can you see if my Pokémon have grown\n"
	.string "stronger?$"

Tuber_TrentonDefeat:
	.string "I’m drifting away...$"

Tuber_TrentonPostBattle:
	.string "I wish Professor Rowan would\n"
	.string "give me a Pokédex.\p"
	.string "But that old guy looks kind of\n"
	.string "scary.$"

Tuber_TrentonIntro:
	.string "I love my inflatable tube.\n"
	.string "So I admire jellyfish Pokémon!$"

Tuber_TrentonRematch:
	.string "I love my inflatable tube.\n"
	.string "So I admire jellyfish Pokémon.\p"
	.string "Won’t you hang out with us and just\n"
	.string "bob around on the waves?$"

Veteran_ArmandoDefeat:
	.string "I see...\n"
	.string "Simply outstanding.$"

Veteran_ArmandoPostBattle:
	.string "I’ve seen countless Trainers and\n"
	.string "even more Pokémon.\p"
	.string "You’re a strong Trainer.\n"
	.string "Moreover, your heart is strong.$"

Veteran_ArmandoIntro:
	.string "I’ve seen countless Trainers and\n"
	.string "even more Pokémon!\p"
	.string "So, what kind of a Trainer are you?$"

Veteran_ArmandoRematch:
	.string "I am indeed a Veteran, but I don’t\n"
	.string "use that as an excuse to slack off.\p"
	.string "I take pride in challenging those\n"
	.string "who have bested me before!$"

Veteran_BrendenDefeat:
	.string "All I can manage now is to wheeze\n"
	.string "out a few meek sighs...$"

Veteran_BrendenPostBattle:
	.string "I don’t see what my age has to do\n"
	.string "with playing with Pokémon, frankly.$"

Veteran_BrendenIntro:
	.string "I’ll wheel out some wicked Pokémon\n"
	.string "and even wickeder moves!$"

Veteran_BrianDefeat:
	.string "The power of youth...\n"
	.string "It’s startling.$"

Veteran_BrianPostBattle:
	.string "Yes! This is fun!\n"
	.string "Pokémon are fun!\p"
	.string "Retire? Perish that thought!\p"
	.string "I’ll become a lot tougher.\n"
	.string "Next time, victory is mine!$"

Veteran_BrianIntro:
	.string "Very well. I’ve decided.\p"
	.string "I’ll battle one last time, with you,\n"
	.string "then I’m retiring as a Trainer.$"

Veteran_BrianRematch:
	.string "Your young power against my veteran\n"
	.string "technique...\p"
	.string "Let us battle again to see who wins\n"
	.string "this time!$"

Veteran_ClaytonDefeat:
	.string "Brilliant!$"

Veteran_ClaytonPostBattle:
	.string "Rather than navigating Victory Road,\n"
	.string "I have a much better time putting\p"
	.string "young Trainers like you to the test.$"

Veteran_ClaytonIntro:
	.string "Let me see how well your Pokémon can\n"
	.string "battle!$"

Veteran_EdgarDefeat:
	.string "Ah, I understand it now!$"

Veteran_EdgarPostBattle:
	.string "Neither Pokémon nor people live\n"
	.string "forever.\p"
	.string "But it is the very frailty of life that\n"
	.string "allows us to shine!$"

Veteran_EdgarIntro:
	.string "I can sense that your Pokémon have\n"
	.string "a lot of trust in you.\p"
	.string "You and your Pokémon...\n"
	.string "You seem to be aglow.$"

Veteran_EmanuelDefeat:
	.string "Tough, aren’t you...?$"

Veteran_GrantDefeat:
	.string "Grrr...\n"
	.string "So young, and yet so talented!$"

Veteran_GrantPostBattle:
	.string "I’ll always remain young at heart.\n"
	.string "Never let them say you’re too old!$"

Veteran_GrantIntro:
	.string "I’m a Veteran, yes, but don’t you\n"
	.string "dare treat me like a senior citizen!$"

Veteran_HarlanDefeat:
	.string "You’ve earned the right to be here.\n"
	.string "Both you and your Pokémon.$"

Veteran_HarlanPostBattle:
	.string "You may find it odd, but the stink\n"
	.string "of sulfur from the volcanic gas\p"
	.string "is what draws me here.$"

Veteran_HarlanIntro:
	.string "What do you expect to achieve here?\n"
	.string "I’ll be the one to make that call!$"

Veteran_TerrellDefeat:
	.string "My sorrow deepens...$"

Veteran_TerrellPostBattle:
	.string "You may be a child, but you’ve taught\n"
	.string "me a whole lot. I thank you humbly.$"

Veteran_TerrellIntro:
	.string "What it means to battle...\n"
	.string "Its joys, its sorrows...\p"
	.string "I’ve experienced it all!$"

Waitress_KatiDefeat:
	.string "I take losses with an unusually big\n"
	.string "smile! Do you find that odd at all?$"

Waitress_KatiPostBattle:
	.string "After a match, you should have some\n"
	.string "Moomoo Milk to quench your thirst!\p"
	.string "Just chug it right down! Glug glug!$"

Waitress_KatiIntro:
	.string "Welcome!\n"
	.string "This place is my pride and joy!$"

Worker_BradenDefeat:
	.string "A-OK! Looks safe to me!\n"
	.string "Not a problem in sight!$"

Worker_BradenPostBattle:
	.string "I routinely check the lifts here.\n"
	.string "You can be sure of their safety!$"

Worker_BradenIntro:
	.string "While I’m making sure the lifts are\n"
	.string "safe, I’ll focus on a battle with you!$"

Worker_BrendonDefeat:
	.string "You played me like an amateur!$"

Worker_BrendonPostBattle:
	.string "They were going to close this place\n"
	.string "up so no one could get in.\p"
	.string "But, they left it open so people and\n"
	.string "Pokémon can get together here.$"

Worker_BrendonIntro:
	.string "Hey! This is no playground!\n"
	.string "If you’re gonna play, battle me!$"

Worker_ColinDefeat:
	.string "Wahaha!\n"
	.string "Mercy, I cry mercy!$"

Worker_ColinPostBattle:
	.string "I’d better get on back to work...\p"
	.string "You know, I’d rather be traveling\n"
	.string "around with Pokémon the way you do.$"

Worker_ColinIntro:
	.string "Fine, all righty then.\n"
	.string "Just a quick battle on my break!$"

Worker_ConradDefeat:
	.string "I’m going down in flames!$"

Worker_ConradPostBattle:
	.string "The sweat of a working man is\n"
	.string "beautiful to behold...\p"
	.string "There is also beauty in the tears\n"
	.string "wept from defeat...$"

Worker_ConradIntro:
	.string "Are you maybe getting annoyed by\n"
	.string "where the floor panels take you?$"

Worker_DillanDefeat:
	.string "I burned out...$"

Worker_DillanPostBattle:
	.string "I toughened up my muscles from\n"
	.string "honest work.\p"
	.string "Pokémon have nothing on me!$"

Worker_DillanIntro:
	.string "I work in the fiery foundry.\n"
	.string "You bet I’m hot and sweaty!$"

Worker_GaryDefeat:
	.string "That move was devastating!$"

Worker_GaryPostBattle:
	.string "I get to work all day with my\n"
	.string "Pokémon, and even battle sometimes.\p"
	.string "I get all the fun I need every day!$"

Worker_GaryIntro:
	.string "A Pokémon Gym isn’t only about seeing\n"
	.string "how tough your Pokémon happen to be.\p"
	.string "It’s so much deeper than just that.\n"
	.string "It’s a test of you as a person.$"

Worker_GerardoDefeat:
	.string "A spectacular loss!\n"
	.string "But it’s still a loss!$"

Worker_GerardoPostBattle:
	.string "The way you helped each other...\n"
	.string "That is what made you prevail!$"

Worker_GerardoIntro:
	.string "Pokémon and people have worked\n"
	.string "together for many years.\p"
	.string "Let us show you an example of that\n"
	.string "history!$"

Worker_HoldenDefeat:
	.string "Fire! And once more, only because I\n"
	.string "feel like it, fiyaaaah!$"

Worker_HoldenPostBattle:
	.string "The floor panels move automatically.\n"
	.string "We’re pretty proud of them here!$"

Worker_HoldenIntro:
	.string "Well! It’s not often we get a visitor\n"
	.string "like you to the ironworks!\p"
	.string "Let’s mark the occasion with\n"
	.string "a battle!$"

Worker_JacksonDefeat:
	.string "You’ve got me feeling down!$"

Worker_JacksonPostBattle:
	.string "I can’t keep this up!\n"
	.string "I’ll go back to working on the lifts.$"

Worker_JacksonIntro:
	.string "Up and down you go on the lifts.\n"
	.string "Me? I like to battle!$"

Worker_MasonDefeat:
	.string "Well, now aren’t you something!$"

Worker_MasonPostBattle:
	.string "OK, OK, time for work! I’ll work up\n"
	.string "a thirst with my Pokémon!$"

Worker_MasonIntro:
	.string "I’m gonna let you in on a secret...\n"
	.string "I snuck my Pokémon to work!$"

Worker_NoelDefeat:
	.string "The working-class hero waves bye...$"

Worker_NoelPostBattle:
	.string "I used to work here a long time\n"
	.string "ago, before it shut down.\p"
	.string "I worked at the ironworks near\n"
	.string "Floaroma Town, too.\p"
	.string "You might say I’m drawn by iron\n"
	.string "as if by magnet!$"

Worker_NoelIntro:
	.string "The working-class hero says hi!$"

Worker_QuentinDefeat:
	.string "Maybe I should head to the Gym and\n"
	.string "work out there...$"

Worker_QuentinPostBattle:
	.string "Roark spent his childhood playing\n"
	.string "here, I think...$"

Worker_QuentinIntro:
	.string "The Canalave Gym folks use this place\n"
	.string "as their training grounds.$"

Youngster_AustinDefeat:
	.string "I couldn’t win with just energy...\n"
	.string "Nothing’s really that easy!$"

Youngster_AustinPostBattle:
	.string "Pokémon don’t wear clothes.\n"
	.string "I worry about them getting cold.$"

Youngster_AustinIntro:
	.string "I wear shorts the whole year!\n"
	.string "I’ve got energy to burn!$"

Youngster_AustinRematch:
	.string "I wear shorts! I have lots of\n"
	.string "energy! I’m not losing to you!$"

Youngster_DallasRematch:
	.string "I’m always with my Pokémon.\p"
	.string "Actually, you’re always with your\n"
	.string "Pokémon too, aren’t you?$"

Youngster_DonnyDefeat:
	.string "Argh! I should’ve dazzled you by\n"
	.string "shining my light in your eyes!$"

Youngster_DonnyPostBattle:
	.string "Just walk around and look for the blue\n"
	.string "marks on the tiles.$"

Youngster_DonnyIntro:
	.string "Hey, now!\n"
	.string "You’re not even close to the door yet.\p"
	.string "You have to beat me before you can\n"
	.string "go, you know?$"

Youngster_JonathonDefeat:
	.string "Now I understand why you decided to\n"
	.string "battle with me.$"

Youngster_JonathonPostBattle:
	.string "You should go whichever way you\n"
	.string "want, shortcut or the long way!$"

Youngster_JonathonIntro:
	.string "You avoided the long way around?\n"
	.string "Let’s see why you’d do that!$"

Youngster_LoganRematch:
	.string "Let’s have another Pokémon battle!\n"
	.string "This time, I’m gonna win!$"

Youngster_MichaelRematch:
	.string "Hey, I remember your face, Trainer.\n"
	.string "You’ll battle me again, won’t you?$"

Youngster_Norman_Unused_1Defeat:
	.string "Losing makes me mad, but that\n"
	.string "was still a bunch of fun!$"

Youngster_Norman_Unused_1PostBattle:
	.string "With Pokémon that tough, I bet you\n"
	.string "could go anywhere in Sinnoh!$"

Youngster_Norman_Unused_1Intro:
	.string "You’re a Pokémon Trainer, and so\n"
	.string "am I.\p"
	.string "When Trainers lock eyes, that means\n"
	.string "a battle is on!$"

Youngster_Norman_Unused_2Defeat:
	.string "Losing makes me mad, but that\n"
	.string "was still a bunch of fun!$"

Youngster_Norman_Unused_2PostBattle:
	.string "With Pokémon that tough, I bet you\n"
	.string "could go anywhere in Sinnoh!$"

Youngster_Norman_Unused_2Intro:
	.string "You’re a Pokémon Trainer, and so\n"
	.string "am I.\p"
	.string "When Trainers lock eyes, that means\n"
	.string "a battle is on!$"

Youngster_Norman_Unused_3Defeat:
	.string "Losing makes me mad, but that\n"
	.string "was still a bunch of fun!$"

Youngster_Norman_Unused_3PostBattle:
	.string "With Pokémon that tough, I bet you\n"
	.string "could go anywhere in Sinnoh!$"

Youngster_Norman_Unused_3Intro:
	.string "You’re a Pokémon Trainer, and so\n"
	.string "am I.\p"
	.string "When Trainers lock eyes, that means\n"
	.string "a battle is on!$"

Youngster_OliverDefeat:
	.string "Hey...\n"
	.string "You’re no ghost...$"

Youngster_OliverPostBattle:
	.string "I had to come to the Lost Tower on\n"
	.string "a dare...\p"
	.string "I have to go to the top and use Defog\n"
	.string "there...$"

Youngster_OliverIntro:
	.string "Waah! Ghost! Get away! Eek!\n"
	.string "Help me, team!$"

Youngster_Roland_Unused_1Defeat:
	.string "I give up! You’re too much!\n"
	.string "Are you maybe a Pokémon genius?$"

Youngster_Roland_Unused_1PostBattle:
	.string "Making Pokémon battle each other\n"
	.string "makes them tougher, you know?$"

Youngster_Roland_Unused_1Intro:
	.string "You got Pokémon! I got Pokémon!\n"
	.string "Let’s see whose Pokémon is the best!$"

Youngster_Roland_Unused_2Defeat:
	.string "I give up! You’re too much!\n"
	.string "Are you maybe a Pokémon genius?$"

Youngster_Roland_Unused_2PostBattle:
	.string "Making Pokémon battle each other\n"
	.string "makes them tougher.$"

Youngster_Roland_Unused_2Intro:
	.string "You got Pokémon! I got Pokémon!\n"
	.string "Let’s see whose Pokémon is the best!$"

Youngster_Roland_Unused_3Defeat:
	.string "I give up! You’re too much!\n"
	.string "Are you maybe a Pokémon genius?$"

Youngster_Roland_Unused_3PostBattle:
	.string "Making Pokémon battle each other\n"
	.string "makes them tougher.$"

Youngster_Roland_Unused_3Intro:
	.string "You got Pokémon! I got Pokémon!\n"
	.string "Let’s see whose Pokémon is the best!$"

Youngster_SebastianRematch:
	.string "I’m about ready to challenge the\n"
	.string "Pokémon Gym Leader.\p"
	.string "But before I do, let me test my\n"
	.string "strength on you again!$"

Youngster_TristanRematch:
	.string "Did you get better since we met?\n"
	.string "I... Well, here, just look!$"

Youngster_TylerRematch:
	.string "This time, I’ll beat you with the\n"
	.string "Pokémon my dad gave me!$"

Youngster_WayneDefeat:
	.string "You were just toying with me!$"

Youngster_WaynePostBattle:
	.string "I’m playing hide-and-seek here.\n"
	.string "I like some underground tag, too.$"

Youngster_WayneIntro:
	.string "Did you come to play, too?\n"
	.string "Wanna play battle with me?$"
