OreburghCity_TowerA_1F_MapScripts::
	.byte 0

OreburghCity_TowerA_1F_EventScript_Youngster::
	msgbox OreburghCity_TowerA_1F_Text_JustAnyTrainer, MSGBOX_NPC
	end

OreburghCity_TowerA_1F_EventScript_PokefanF::
	msgbox OreburghCity_TowerA_1F_Text_LetsUsTrain, MSGBOX_NPC
	end

OreburghCity_TowerA_1F_EventScript_Breeder::
	msgbox OreburghCity_TowerA_1F_Text_ThereAreEight, MSGBOX_NPC
	end

OreburghCity_TowerA_1F_Text_JustAnyTrainer:
	.string "A Gym Leader isn't like just any Trainer\n"
	.string "you meet.\p"
	.string "Obviously, they're a lot tougher.\n"
	.string "A lot.\p"
	.string "I'd take as many Pokémon as possible\n"
	.string "if I were you.$"

OreburghCity_TowerA_1F_Text_LetsUsTrain:
	.string "Roark lets us train our Pokémon in\n"
	.string "the mine.$"

OreburghCity_TowerA_1F_Text_ThereAreEight:
	.string "There are eight Gym leaders in the\n"
	.string "Sinnoh region.\p"
	.string "The objective for Trainers is to get\n"
	.string "Gym Badges from all of them."
	.string "That means you have to defeat all of\n"
	.string "them in battles at their Gyms!$"
