JubilifeCity_TowerA_1F_MapScripts::
	.byte 0

JubilifeCity_TowerA_1F_EventScript_AceTrainerM::
	msgbox JubilifeCity_TowerA_1F_Text_PokemonAreWonderful, MSGBOX_NPC
	end

JubilifeCity_TowerA_1F_EventScript_Lass::
	msgbox JubilifeCity_TowerA_1F_Text_HelloThereTrainer, MSGBOX_NPC
	end

JubilifeCity_TowerA_1F_EventScript_Pachirisu::
	msgbox JubilifeCity_TowerA_1F_Text_Pachirisu, MSGBOX_NPC
	end

JubilifeCity_TowerA_1F_Text_PokemonAreWonderful:
	.string "Pokémon are wonderful, deeply\n"
	.string "mysterious creatures.\p"
	.string "But to Trainers, the key thing is to do\n"
	.string "battle with their Pokémon.\p"
	.string "That’s what it boils down to.$"

JubilifeCity_TowerA_1F_Text_HelloThereTrainer:
	.string "Hello there, Trainer!\p"
	.string "If you get stumped and don’t know\n"
	.string "what to do...\p"
	.string "Talk to people!\n"
	.string "Talk to everyone you see!\p"
	.string "Go places!\n"
	.string "Go wherever you can!\p"
	.string "You’ll find many new places by\n"
	.string "doing just that.$"

JubilifeCity_TowerA_1F_Text_Pachirisu:
	.string "PACHIRISU: Kukkuuh!$"
