JubilifeCity_TowerA_2F_MapScripts::
	.byte 0

JubilifeCity_TowerA_2F_EventScript_Youngster::
	msgbox JubilifeCity_TowerA_2F_Text_DidYouKnow, MSGBOX_NPC
	end

JubilifeCity_TowerA_2F_EventScript_PokeFanF::
	msgbox JubilifeCity_TowerA_2F_Text_EvolutionMakes, MSGBOX_NPC
	end

JubilifeCity_TowerA_2F_EventScript_AromaLady::
	msgbox JubilifeCity_TowerA_2F_Text_ConductResearch, MSGBOX_NPC
	end

JubilifeCity_TowerA_2F_Text_DidYouKnow:
	.string "Did you know?\p"
	.string "Some kinds of Pokémon evolve when\n"
	.string "they get stronger from battling!\p"
	.string "When they evolve, they can take on\n"
	.string "completely different forms!$"

JubilifeCity_TowerA_2F_Text_EvolutionMakes:
	.string "Evolution makes Pokémon just that\n"
	.string "much more fascinating.\p"
	.string "The mysteries of evolution... Can that\n"
	.string "dandy Prof. Rowan unravel them?$"
	
JubilifeCity_TowerA_2F_Text_ConductResearch:
	.string "Didn’t Prof. Rowan conduct research\n"
	.string "with Prof. Oak of the Kanto region?$"
